Repository inverse-inc/packetfence, pull requests merged in 2018-10, with the labels that each got.

#3624 Update devel rule in Makefile
  Makefile
Labels: Status: For review, Type: Feature / Enhancement

#3450 Fixes #3387
  html/pfappserver/root/graph/dashboard.tt
  lib/pfconfig/namespaces/config/Stats.pm
Labels: Status: For review

#3380 Feature/deprecate api user
  db/upgrade-X.X.X-X.Y.Z.sql
  docs/api/spec/paths/api_user.yaml
  docs/api/spec/paths/api_users.yaml
  docs/api/spec/paths/api_users/search.yaml
  go/caddy/api-aaa/api-aaa.go
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/ApiUsers.pm
  lib/pf/dal/_api_user.pm
  lib/pf/dal/api_user.pm
Labels: Priority: Low, Type: Feature / Enhancement

#3617 Use several email addresses in alerting.emailaddr
  conf/documentation.conf
  conf/keepalived.conf.example
  conf/pf.conf.defaults
  lib/pf/config/util.pm
  lib/pf/constants.pm
  lib/pf/services/manager/keepalived.pm
  lib/pf/util.pm
Labels: Status: For review, Type: Bug

#3242 Feature/rapid7 scan
  conf/documentation.conf
  conf/nexpose-responses.txt
  conf/pf.conf.defaults
  docs/PacketFence_Installation_Guide.asciidoc
  docs/images/rapid7/rapid7-connection-profile.png
  docs/images/rapid7/rapid7-node-tab.png
  docs/images/rapid7/rapid7-pf-1.png
  docs/images/rapid7/rapid7-pf-2.png
  docs/images/rapid7/rapid7-pf-3.png
  docs/images/rapid7/rapid7-syslog-parser.png
  docs/images/rapid7/rapid7-syslog.png
  docs/images/rapid7/rapid7-user-create-1.png
  docs/images/rapid7/rapid7-user-create-2.png
  docs/images/rapid7/rapid7-violation-trigger.png
  html/pfappserver/lib/pfappserver/Form/Config/Pfdetect/nexpose.pm
  html/pfappserver/lib/pfappserver/Form/Config/Scan/Rapid7.pm
  html/pfappserver/lib/pfappserver/I18N/en.po
  html/pfappserver/lib/pfappserver/Model/Node/Tab/Rapid7.pm
  html/pfappserver/lib/pfappserver/PacketFence/Controller/Node.pm
  html/pfappserver/root/config/pfdetect/type/nexpose.tt
  html/pfappserver/root/config/scan/type/rapid7.tt
  html/pfappserver/root/node/tab_Rapid7_view.tt
  html/pfappserver/root/node/view.tt
  html/pfappserver/root/static/app/application.css
  html/pfappserver/root/static/js/node.js
  lib/pf/api.pm
  lib/pf/constants/trigger.pm
  lib/pf/factory/condition/violation.pm
  lib/pf/file_paths.pm
  lib/pf/scan/rapid7.pm
Labels: Priority: Medium, Type: Feature / Enhancement

#3476 Email templates improvements
  html/captive-portal/templates/emails/Makefile
  html/captive-portal/templates/emails/_footer.mjml
  html/captive-portal/templates/emails/_header.mjml
  html/captive-portal/templates/emails/emails-billing_confirmation.html
  html/captive-portal/templates/emails/emails-billing_confirmation.mjml
  html/captive-portal/templates/emails/emails-billing_stripe_customer.subscription.deleted.html
  html/captive-portal/templates/emails/emails-billing_stripe_customer.subscription.deleted.mjml
  html/captive-portal/templates/emails/emails-guest_admin_pregistration.html
  html/captive-portal/templates/emails/emails-guest_admin_pregistration.mjml
  html/captive-portal/templates/emails/emails-guest_email_activation.html
  html/captive-portal/templates/emails/emails-guest_email_activation.mjml
  html/captive-portal/templates/emails/emails-guest_email_preregistration.html
  html/captive-portal/templates/emails/emails-guest_email_preregistration.mjml
  html/captive-portal/templates/emails/emails-guest_email_preregistration_confirmed.html
  html/captive-portal/templates/emails/emails-guest_email_preregistration_confirmed.mjml
  html/captive-portal/templates/emails/emails-guest_local_account_creation.html
  html/captive-portal/templates/emails/emails-guest_local_account_creation.mjml
  html/captive-portal/templates/emails/emails-guest_sponsor_activation.html
  html/captive-portal/templates/emails/emails-guest_sponsor_activation.mjml
  html/captive-portal/templates/emails/emails-guest_sponsor_confirmed.html
  html/captive-portal/templates/emails/emails-guest_sponsor_confirmed.mjml
  html/captive-portal/templates/emails/emails-guest_sponsor_preregistration.html
  html/captive-portal/templates/emails/emails-guest_sponsor_preregistration.mjml
  html/captive-portal/templates/emails/emails-violation-triggered.html
  html/captive-portal/templates/emails/emails-violation-triggered.mjml
  html/captive-portal/templates/emails/emails.css
  html/captive-portal/templates/emails/package.json
Labels: Status: For review

#3397 Feature/improve netdata cluster graph
  html/pfappserver/lib/pfappserver/PacketFence/Controller/Graph.pm
  html/pfappserver/root/graph/dashboard.tt
  html/pfappserver/root/static/admin/status.js
  lib/pf/StatsD.pm
  src/ntlm_auth_wrap.c
Labels: Status: For review, Type: Feature / Enhancement

#3645 put HAProxy stats files in var/run/ and rename them
  conf/haproxy-db.conf.example
  conf/haproxy-portal.conf.example
Labels: Status: For review, Type: Feature / Enhancement

#3571 Various fixes for pfdhcp
  go/dhcp/main.go
  go/dhcp/pool.go
  go/dhcp/rawClient.go
  go/dhcp/server.go
  go/vendor/vendor.json
Labels: Status: For review, Type: Feature / Enhancement

#3594 feature/manage-filters-api
  html/pfappserver/lib/pfappserver/PacketFence/Controller/Config/Filters.pm
  lib/pf/ConfigStore.pm
  lib/pf/IniFiles.pm
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config/Filters.pm
  lib/pf/config/builder.pm
  lib/pf/config/builder/scoped_filter_engines.pm
  lib/pf/pfcmd/checkup.pm
  lib/pfconfig/config.pm
  lib/pfconfig/manager.pm
  lib/pfconfig/namespaces/FilterEngine/AccessScopes.pm
  lib/pfconfig/namespaces/config.pm
  lib/pfconfig/namespaces/config/AdminRoles.pm
  lib/pfconfig/namespaces/config/DNS_Filters.pm
  lib/pfconfig/namespaces/config/Documentation.pm
  lib/pfconfig/namespaces/config/Pf.pm
  lib/pfconfig/namespaces/config/PfDefault.pm
  lib/pfconfig/namespaces/config/Pfqueue.pm
  lib/pfconfig/namespaces/config/PortalModules.pm
  lib/pfconfig/namespaces/config/Profiles.pm
  lib/pfconfig/namespaces/config/Report.pm
  lib/pfconfig/namespaces/config/Roles.pm
  lib/pfconfig/namespaces/config/Switch.pm
  lib/pfconfig/namespaces/config/Violations.pm
  lib/pfconfig/namespaces/config/VlanFilters.pm
  t/unittest/UnifiedApi/Controller/Config/Filters.t
Labels: Status: For review, Type: Feature / Enhancement

#3637 Update sudoers and Makefile
  Makefile
  UPGRADE.asciidoc
  packetfence.sudoers
Labels: Priority: Medium, Status: For review, Type: Bug

#3285 Password of the day
  conf/pfmon.conf.defaults
  db/pf-schema-X.Y.Z.sql
  db/upgrade-X.X.X-X.Y.Z.sql
  docs/PacketFence_Installation_Guide.asciidoc
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Login.pm
  html/captive-portal/templates/emails/emails-guest_password_of_the_day.html
  html/pfappserver/lib/pfappserver/Base/Form/Role/PasswordLength.pm
  html/pfappserver/lib/pfappserver/Form/Config/Pfmon/password_of_the_day.pm
  html/pfappserver/lib/pfappserver/Form/Config/Source.pm
  html/pfappserver/lib/pfappserver/Form/Config/Source/Potd.pm
  html/pfappserver/root/config/source/type/Potd.tt
  lib/pf/Authentication/Source/PotdSource.pm
  lib/pf/dal/_person.pm
  lib/pf/password.pm
  lib/pf/pfmon/task/password_of_the_day.pm
  lib/pf/web/guest.pm
  t/data/authentication.conf
  t/unittest/authentication.t
Labels: Status: For review, Type: Feature / Enhancement

#3642 Added SMTP test function in Alerting
  html/pfappserver/lib/pfappserver/PacketFence/Controller/Configuration.pm
  html/pfappserver/root/configuration/section.tt
  html/pfappserver/root/static/admin/configuration.js
Labels: Priority: Low, Type: Feature / Enhancement

#3657 Give privileges to pf user to dump stored routines
  UPGRADE.asciidoc
  addons/packages/packetfence.spec
  addons/upgrade/to-8.2-upgrade-pf-privileges.sh
  debian/rules
  html/pfappserver/lib/pfappserver/Model/DB.pm
Labels: Priority: Medium, Status: For review, Type: Bug

#3514 Fix/rogue detection
  lib/pf/dhcp/processor.pm
  lib/pfconfig/namespaces/resource/network_config.pm
Labels: Priority: Medium, Status: For review, Type: Bug

#3638 add logger config to pfdns.conf
  conf/pfdns.conf.example
  go/coredns/core/dnsserver/zdirectives.go
  go/coredns/core/zplugin.go
  go/coredns/plugin.cfg
  go/coredns/plugin/logger/logger.go
  go/coredns/plugin/pfdns/pfdns.go
Labels: Priority: Medium, Type: Feature / Enhancement

#3372 Add the VOIP and the Downloadable ACLs support to Aruba 5400 switch module
  lib/pf/Switch/Aruba/5400.pm
Labels: Status: For review, Type: Feature / Enhancement

#3502 add explicit output for database-backup-and-maintenance.sh in cluster env
  addons/database-backup-and-maintenance.sh
Labels: Priority: Low, Type: Feature / Enhancement

#3583 Feature/switch filter instantiate
  conf/switch_filters.conf.example
  lib/pf/SwitchFactory.pm
  lib/pf/api.pm
  lib/pf/radius.pm
Labels: Status: Not ready, Type: Feature / Enhancement

#3659 Adjust the Aruba Web authentication documentation
  docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
Labels: Status: For review

#3261 Fix for 3069
  UPGRADE.asciidoc
  conf/radius_filters.conf.example
  conf/switch_filters.conf.example
  conf/vlan_filters.conf.defaults
  conf/vlan_filters.conf.example
  db/upgrade-X.X.X-X.Y.Z.sql
  docs/PacketFence_Installation_Guide.asciidoc
  lib/pf/config.pm
  lib/pf/role.pm
Labels: Type: Feature / Enhancement

#2842 Juniper SRX Firewall SSO
  docs/PacketFence_Installation_Guide.asciidoc
  docs/firewall/junipersrx.asciidoc
  go/firewallsso/factory.go
  go/firewallsso/junipersrx.go
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/JuniperSRX.pm
  lib/pf/constants/firewallsso.pm
  lib/pf/firewallsso.pm
Labels: Status: For review, Type: Feature / Enhancement

#3662 Generate javacript and css in the debian packaging
  debian/control
  debian/packetfence.conffiles
  debian/rules
  html/common/Makefile
  html/pfappserver/root/static.alt/Makefile
  html/pfappserver/root/static/Makefile
Labels: Status: For review, Type: Feature / Enhancement

#3639 Pfappserver Updates
  html/pfappserver/root/static.alt/README.md
  html/pfappserver/root/static.alt/src/components/pfCSVParse.vue
  html/pfappserver/root/static.alt/src/components/pfFormChosen.vue
  html/pfappserver/root/static.alt/src/components/pfFormDatetime.vue
  html/pfappserver/root/static.alt/src/components/pfFormInput.vue
  html/pfappserver/root/static.alt/src/components/pfFormPrefixMultiplier.vue
  html/pfappserver/root/static.alt/src/components/pfFormSortableFields.vue
  html/pfappserver/root/static.alt/src/components/pfMixinValidation.js
  html/pfappserver/root/static.alt/src/components/pfSearchBoolean.vue
  html/pfappserver/root/static.alt/src/globals/pfField.js
  html/pfappserver/root/static.alt/src/globals/pfSearch.js
  html/pfappserver/root/static.alt/src/globals/pfValidators.js
  html/pfappserver/root/static.alt/src/main.js
  html/pfappserver/root/static.alt/src/store/modules/config.js
  html/pfappserver/root/static.alt/src/utils/bytes.js
  html/pfappserver/root/static.alt/src/utils/locale.js
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesCreate.vue
  html/pfappserver/root/static.alt/src/views/Users/_components/UsersCreate.vue
Labels: Priority: Low, Status: In progress, Status: Not ready

#3597 feature/test-syslog-parser-via-api
  docs/api/spec/components/schemas/configsyslogparser_dry_run.yaml
  docs/api/spec/paths/config/syslog_parsers_dry_run.yaml
  html/pfappserver/lib/pfappserver/Form/Config/Pfdetect/regex.pm
  html/pfappserver/lib/pfappserver/Form/Field/PfdetectRegexRule.pm
  html/pfappserver/lib/pfappserver/Form/Field/RE2.pm
  html/pfappserver/root/config/pfdetect/test_regex_parser.tt
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config/SyslogParsers.pm
  lib/pf/detect/parser/regex.pm
  t/unittest/UnifiedApi/Controller/Config/SyslogParsers.t
  t/unittest/detect/parser/regex.t
Labels: Status: For review, Type: Feature / Enhancement

#3593 feature/wrix_endpoint
  docs/api/spec/components/schemas/wrixlocation.yaml
  docs/api/spec/components/schemas/wrixlocationslist.yaml
  docs/api/spec/paths/wrix_location.yaml
  docs/api/spec/paths/wrix_locations.yaml
  docs/api/spec/paths/wrix_locations/search.yaml
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/WrixLocations.pm
  t/unittest/UnifiedApi/Controller/WrixLocations.t
Labels: Status: For review, Type: Feature / Enhancement

#3590 feature/return_count_from_api_search
  docs/api/spec/components/schemas/base.yaml
  docs/api/spec/components/schemas/search.yaml
  lib/pf/UnifiedApi/Controller/Crud.pm
  lib/pf/UnifiedApi/Search/Builder.pm
  t/unittest/UnifiedApi/Controller/Nodes.t
  t/unittest/UnifiedApi/Search/Builder/Nodes.t
Labels: Status: For review, Type: Feature / Enhancement

#3587 feature/config-provisioning
  docs/api/spec/components/schemas/configprovisioning.yaml
  docs/api/spec/components/schemas/configprovisioningslist.yaml
  docs/api/spec/openapi.json
  docs/api/spec/openapi.yaml
  docs/api/spec/paths/config/provisioning.yaml
  docs/api/spec/paths/config/provisionings.yaml
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config/Provisionings.pm
  t/unittest/UnifiedApi/Controller/Config/Provisionings.t
Labels: Status: For review, Type: Feature / Enhancement

#3588 feature/config-syslog_forwarder
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config/SyslogForwarders.pm
  t/unittest/UnifiedApi/Controller/Config/SyslogForwarders.t
Labels: Status: For review, Type: Feature / Enhancement

#3589 feature/test_source_from_api
  docs/api/spec/paths/config/sources_test.yaml
  html/pfappserver/lib/pfappserver/Form/Config/Source/Htpasswd.pm
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config/Sources.pm
  t/unittest/UnifiedApi/Controller/Config/Sources.t
Labels: Status: For review, Type: Feature / Enhancement

#3698 fix/3670
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Sponsor.pm
  lib/pf/activation.pm
Labels: Type: Bug

#3714 Reworked dhcp statistics
  conf/monitoring/statsd.d/packetfence.conf.example
  conf/stats.conf.example
  go/dhcp/api.go
  html/pfappserver/root/graph/dashboard.tt
  lib/pf/services/manager/netdata.pm
  lib/pfconfig/namespaces/config/Stats.pm
Labels: Status: For review, Type: Feature / Enhancement

#3718 fix/admin-styling
  html/pfappserver/root/config/domain/index.tt
  html/pfappserver/root/config/pfmon/index.tt
  html/pfappserver/root/config/realm/index.tt
  html/pfappserver/root/config/roles/index.tt
  html/pfappserver/root/config/scan/index.tt
  html/pfappserver/root/config/switch/index.tt
  html/pfappserver/root/config/trafficshaping/index.tt
  html/pfappserver/root/config/wmi/index.tt
Labels: Priority: Low
