Repository inverse-inc/packetfence, pull requests merged in 2018-07, with the labels that each got.

#3346 Change paths used in documentation (images and includes)
  Makefile
  addons/packages/packetfence.spec
  debian/rules
  docs/PacketFence_Clustering_Guide.asciidoc
  docs/PacketFence_Developers_Guide.asciidoc
  docs/PacketFence_Installation_Guide.asciidoc
  docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
  docs/docbook/xsl/packetfence-fo.xsl
  docs/docinfo.xml
  docs/enforcement/inline.asciidoc
  docs/enforcement/out-of-band.asciidoc
  docs/firewall/barracuda.asciidoc
  docs/firewall/checkpoint.asciidoc
  docs/firewall/fortigate.asciidoc
  docs/firewall/jsonrpc.asciidoc
  docs/firewall/paloalto.asciidoc
  docs/fonts/fop-config.xml
  docs/images/aruba-registration-acl.png
  docs/includes/global-attributes.asciidoc
  docs/networkdevice/aerohive.asciidoc
  docs/networkdevice/anyfi.asciidoc
  docs/networkdevice/coovachilli.asciidoc
  docs/networkdevice/hostapd.asciidoc
  docs/pki/microsoft.asciidoc
  docs/pki/packetfence.asciidoc
  docs/provisioner/mobileiron.asciidoc
  docs/provisioner/opswat.asciidoc
  docs/provisioner/sentinelone.asciidoc
  docs/provisioner/sepm.asciidoc
Labels: Priority: Low, Type: Feature / Enhancement

#3338 Review PacketFence Guides
  docs/PacketFence_Clustering_Guide.asciidoc
  docs/PacketFence_Installation_Guide.asciidoc
  docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
  docs/enforcement/inline.asciidoc
  docs/enforcement/out-of-band.asciidoc
  docs/images/packetfence-pki-provider.png
  docs/images/packetfence-pki-provider2.png
  docs/networkdevice/aerohive.asciidoc
  docs/pki/packetfence.asciidoc
Labels: Priority: Low, Type: Feature / Enhancement

#3358 pfappserver updates
  html/pfappserver/root/static.alt/src/components/DeleteButton.vue
  html/pfappserver/root/static.alt/src/components/pfMixinSavedSearch.vue
  html/pfappserver/root/static.alt/src/components/pfMixinSearchable.js
  html/pfappserver/root/static.alt/src/components/pfMixinSelectable.js
  html/pfappserver/root/static.alt/src/components/pfSearch.vue
  html/pfappserver/root/static.alt/src/globals/pfSearch.js
  html/pfappserver/root/static.alt/src/main.js
  html/pfappserver/root/static.alt/src/store/base/searchable.js
  html/pfappserver/root/static.alt/src/store/modules/config.js
  html/pfappserver/root/static.alt/src/utils/locale.js
  html/pfappserver/root/static.alt/src/views/Nodes/_api/index.js
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodeView.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesSearch.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_router/index.js
  html/pfappserver/root/static.alt/src/views/Nodes/_store/index.js
  html/pfappserver/root/static.alt/src/views/Nodes/index.vue
  html/pfappserver/root/static.alt/src/views/Users/_api/index.js
  html/pfappserver/root/static.alt/src/views/Users/_components/UserView.vue
  html/pfappserver/root/static.alt/src/views/Users/_components/UsersSearch.vue
  html/pfappserver/root/static.alt/src/views/Users/_router/index.js
  html/pfappserver/root/static.alt/src/views/Users/_store/index.js
  html/pfappserver/root/static.alt/src/views/Users/index.vue
Labels: Status: For review

#3375 Pfappserver Updates
  html/pfappserver/root/static.alt/README.md
  html/pfappserver/root/static.alt/package.json
  html/pfappserver/root/static.alt/src/main.js
  html/pfappserver/root/static.alt/src/utils/network.js
  html/pfappserver/root/static.alt/src/views/Nodes/_api/index.js
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodeView.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesSearch.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_store/index.js
  html/pfappserver/root/static.alt/src/views/Users/_components/UsersSearch.vue
Labels: Status: For review, Status: In progress

#3395 Fix/person lookup strip
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Login.pm
  lib/pf/lookup/person.pm
  lib/pf/radius.pm
  lib/pf/registration.pm
  lib/pf/role.pm
  lib/pf/task/person_lookup.pm
Labels: Status: For review

#3392 Pfappserver Updates
  html/pfappserver/root/static.alt/src/components/pfMixinSearchable.js
  html/pfappserver/root/static.alt/src/globals/pfReports.js
  html/pfappserver/root/static.alt/src/globals/pfSearch.js
  html/pfappserver/root/static.alt/src/main.js
  html/pfappserver/root/static.alt/src/store/modules/config.js
  html/pfappserver/root/static.alt/src/styles/_sidebar.scss
  html/pfappserver/root/static.alt/src/utils/api.js
  html/pfappserver/root/static.alt/src/views/Nodes/_api/index.js
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodeView.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesCreate.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesSearch.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_store/index.js
  html/pfappserver/root/static.alt/src/views/Nodes/index.vue
  html/pfappserver/root/static.alt/src/views/Reports/_components/ReportTable.vue
  html/pfappserver/root/static.alt/src/views/Reports/_router/index.js
  html/pfappserver/root/static.alt/src/views/Reports/index.vue
  lib/pf/UnifiedApi/SearchBuilder/Nodes.pm
Labels: Status: In progress, Status: Not ready

#3270 feature/pfqueue-tenant-id
  lib/pf/pfqueue/consumer/redis.pm
  lib/pf/pfqueue/producer/redis.pm
Labels: Type: Feature / Enhancement

#3272 feature/jsonrpc-tenant-id
  lib/pf/WebAPI/JSONRPC.pm
  lib/pf/api/jsonrpcclient.pm
  t/unittest/api/jsonrpcclient.t
Labels: Type: Feature / Enhancement
