Repository inverse-inc/packetfence, pull requests merged in 2018-12, with the labels that each got.

#3801 Pfappserver updates
  html/pfappserver/root/static.alt/src/components/pfButtonDelete.vue
  html/pfappserver/root/static.alt/src/components/pfCSVParse.vue
  html/pfappserver/root/static.alt/src/components/pfConfigView.vue
  html/pfappserver/root/static.alt/src/components/pfFieldAction.vue
  html/pfappserver/root/static.alt/src/components/pfFieldCondition.vue
  html/pfappserver/root/static.alt/src/components/pfFieldRule.vue
  html/pfappserver/root/static.alt/src/components/pfFormActions.vue
  html/pfappserver/root/static.alt/src/components/pfFormChosen.vue
  html/pfappserver/root/static.alt/src/components/pfFormDatetime.vue
  html/pfappserver/root/static.alt/src/components/pfFormFields.vue
  html/pfappserver/root/static.alt/src/components/pfFormInput.vue
  html/pfappserver/root/static.alt/src/components/pfFormPassword.vue
  html/pfappserver/root/static.alt/src/components/pfFormPrefixMultiplier.vue
  html/pfappserver/root/static.alt/src/components/pfFormSelect.vue
  html/pfappserver/root/static.alt/src/components/pfFormSortableFields.vue
  html/pfappserver/root/static.alt/src/components/pfFormUpload.vue
  html/pfappserver/root/static.alt/src/components/pfMixinCtrlKey.js
  html/pfappserver/root/static.alt/src/components/pfMixinSelectable.js
  html/pfappserver/root/static.alt/src/components/pfMixinValidation.js
  html/pfappserver/root/static.alt/src/components/pfSearchBoolean.vue
  html/pfappserver/root/static.alt/src/globals/pfAuthenticationConditions.js
  html/pfappserver/root/static.alt/src/globals/pfConfiguration.js
  html/pfappserver/root/static.alt/src/globals/pfField.js
  html/pfappserver/root/static.alt/src/globals/pfValidators.js
  html/pfappserver/root/static.alt/src/main.js
  html/pfappserver/root/static.alt/src/styles/_input-group.scss
  html/pfappserver/root/static.alt/src/views/Configuration/_components/AuthenticationSourceView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/AuthenticationSourcesView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/DomainView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/FloatingDeviceView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/PortalModuleView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/RealmView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/RoleView.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodeView.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesCreate.vue
  html/pfappserver/root/static.alt/src/views/Users/_components/UserView.vue
  html/pfappserver/root/static.alt/src/views/Users/_components/UsersCreate.vue
Labels: Status: For review

#3826 Feature/billing tiers new admin
  html/pfappserver/root/static.alt/src/components/pfFieldRule.vue
  html/pfappserver/root/static.alt/src/components/pfFormInput.vue
  html/pfappserver/root/static.alt/src/globals/pfConfiguration.js
  html/pfappserver/root/static.alt/src/globals/pfValidators.js
  html/pfappserver/root/static.alt/src/views/Configuration/_api/index.js
  html/pfappserver/root/static.alt/src/views/Configuration/_components/BillingTierView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/BillingTiersList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_router/index.js
  html/pfappserver/root/static.alt/src/views/Configuration/_store/billingTiers.js
  html/pfappserver/root/static.alt/src/views/Configuration/_store/floatingDevices.js
  html/pfappserver/root/static.alt/src/views/Configuration/_store/portalModules.js
  html/pfappserver/root/static.alt/src/views/Configuration/index.vue
Labels: Status: For review

#3633 New Clickatell Authentication Source
  conf/portal_modules.conf.defaults
  docs/PacketFence_Installation_Guide.asciidoc
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/SMS.pm
  html/pfappserver/lib/pfappserver/Form/Config/Source/Clickatell.pm
  html/pfappserver/root/config/source/type/Clickatell.tt
  lib/pf/Authentication/Source/ClickatellSource.pm
Labels: Status: For review, Type: Feature / Enhancement

#3819 add a random VLAN pool algorithm
  conf/documentation.conf
  docs/PacketFence_Installation_Guide.asciidoc
  lib/pf/constants/role.pm
  lib/pf/role/pool.pm
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#3811 pfdhcp parallel configuration generation
  go/dhcp/api.go
  go/dhcp/config.go
  go/dhcp/main.go
  go/dhcp/utils.go
Labels: Priority: Low, Status: For review, Type: Feature / Enhancement

#3808 Fix minor typos for Layer 3 clustering
  docs/PacketFence_Clustering_Guide.asciidoc
Labels: Status: For review

#3783 DHCP Ip reservation
  docs/api/spec/openapi.json
  docs/api/spec/openapi.yaml
  docs/api/spec/paths/dhcp.yaml
  go/dhcp/api.go
  go/dhcp/config.go
  go/dhcp/main.go
  go/dhcp/utils.go
  go/pfconfigdriver/structs.go
  go/vendor/vendor.json
  html/pfappserver/lib/pfappserver/Form/Config/Network.pm
  html/pfappserver/lib/pfappserver/Form/Field/IPAssigned.pm
  html/pfappserver/root/config/networks/view.tt
Labels: Status: For review, Type: Feature / Enhancement

#3799 Feature/fingerbank device class change
  addons/packages/packetfence.spec
  conf/documentation.conf
  conf/pf.conf.defaults
  conf/violations.conf.defaults
  debian/control
  docs/PacketFence_Installation_Guide.asciidoc
  html/captive-portal/templates/violations/invalid_device_transition.html
  html/pfappserver/lib/pfappserver/Form/Config/Pf.pm
  html/pfappserver/lib/pfappserver/I18N/en.po
  html/pfappserver/lib/pfappserver/PacketFence/Controller/Configuration.pm
  lib/pf/ConfigStore/Pf.pm
  lib/pf/api.pm
  lib/pf/constants/pfconf.pm
  lib/pf/fingerbank.pm
  lib/pfconfig/namespaces/config/Pf.pm
  t/data/pf.conf
  t/unittest/fingerbank.t
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#3753 Updated acct_stop procedure to avoid acct_stop packet if it's duplicate
  db/pf-schema-X.Y.Z.sql
  db/upgrade-X.X.X-X.Y.Z.sql
  raddb/mods-config/sql/main/mysql/queries.conf
Labels: Status: For review, Type: Bug, Type: Feature / Enhancement

#3648 Added callingstationssid and nasidentifierin radius_acct sql table
  db/pf-schema-X.Y.Z.sql
  db/upgrade-X.X.X-X.Y.Z.sql
  raddb/mods-config/sql/main/mysql/queries.conf
Labels: Status: For review, Type: Feature / Enhancement

#3614 Feature/logoff page
  conf/profiles.conf.defaults
  html/captive-portal/content/release.js
  html/captive-portal/lib/captiveportal/Controller/NetworkLogoff.pm
  html/captive-portal/lib/captiveportal/PacketFence/Controller/NetworkLogoff.pm
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Application.pm
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module.pm
  html/captive-portal/templates/networklogoff.html
  html/captive-portal/templates/release.html
  html/common/pf.js
  html/pfappserver/lib/pfappserver/Form/Config/ProfileCommon.pm
  lib/pf/web/constants.pm
Labels: Priority: Medium, Type: Feature / Enhancement

#3786 add file to track fingerbank collector env variables
  addons/packages/packetfence.spec
  conf/fingerbank-collector.env.defaults
  debian/packetfence.conffiles
  lib/pf/file_paths.pm
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#3429 Make userPrincipalName available for 802.1x authentication (ntlm_auth)
  conf/pf.conf.defaults
  conf/radiusd/ldap_packetfence.conf.example
  conf/radiusd/packetfence-tunnel.example
  html/pfappserver/lib/pfappserver/Form/Config/Realm.pm
  html/pfappserver/lib/pfappserver/Form/Config/Source.pm
  html/pfappserver/lib/pfappserver/Form/Config/Source/LDAP.pm
  html/pfappserver/root/config/realm/view.tt
  html/pfappserver/root/config/source/type/LDAP.tt
  lib/pf/Authentication/Source/LDAPSource.pm
  lib/pf/ConfigStore/Source.pm
  lib/pf/config.pm
  lib/pf/services/manager/radiusd_child.pm
  lib/pfconfig/namespaces/config/Authentication.pm
  raddb/dictionary
  raddb/mods-available/cache_password
  raddb/mods-available/mschap
Labels: Status: For review, Status: Not ready, Type: Feature / Enhancement

#3802 Feature/no empty fields portal
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication.pm
  html/captive-portal/templates/signin.html
  html/common/aup-autosubmit.js
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#3716 Run some pfstats task only on the Master of the cluster or on the standalone
  conf/stats.conf.example
  go/pfconfigdriver/structs.go
  go/stats/main.go
Labels: Status: For review, Type: Feature / Enhancement

#3286 Fixes #604 and add password length
  conf/radiusd/sql.conf.example
  docs/PacketFence_Installation_Guide.asciidoc
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication.pm
  html/pfappserver/lib/pfappserver/Base/Form/Role/SourceLocalAccount.pm
  html/pfappserver/lib/pfappserver/Form/Config/Source.pm
  lib/pf/Authentication/CreateLocalAccountRole.pm
  lib/pf/Authentication/constants.pm
  lib/pf/password.pm
  lib/pf/services/manager/radiusd_child.pm
Labels: Status: For review, Type: Feature / Enhancement

#3278 Radius Proxy integration
  UPGRADE.asciidoc
  addons/packages/packetfence.spec
  addons/upgrade/to-8.3-rename-pf-conf-parameters.pl
  conf/documentation.conf
  conf/pf.conf.defaults
  conf/radius_filters.conf.example
  conf/radiusd/packetfence-tunnel.example
  conf/radiusd/packetfence.example
  conf/radiusd/proxy.conf.inc.example
  conf/radiusd/rest.conf.example
  debian/control
  docs/PacketFence_Installation_Guide.asciidoc
  docs/images/ACME1.png
  docs/images/acme.com.2.png
  docs/images/acme.com.png
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Login.pm
  html/pfappserver/lib/pfappserver/Base/Form/Role/InternalSource.pm
  html/pfappserver/lib/pfappserver/Form/Config/Realm.pm
  html/pfappserver/lib/pfappserver/Form/Config/Source/Authorization.pm
  html/pfappserver/lib/pfappserver/Form/Config/Source/RADIUS.pm
  html/pfappserver/lib/pfappserver/I18N/en.po
  html/pfappserver/lib/pfappserver/I18N/fr.po
  html/pfappserver/root/admin/configuration.tt
  html/pfappserver/root/config/realm/list.tt
  html/pfappserver/root/config/realm/view.tt
  html/pfappserver/root/config/source/type/Authorization.tt
  lib/pf/Authentication/Source/AuthorizationSource.pm
  lib/pf/Authentication/Source/RADIUSSource.pm
  lib/pf/ConfigStore/Realm.pm
  lib/pf/ConfigStore/Source.pm
  lib/pf/UnifiedApi/Controller/Config/Sources.pm
  lib/pf/WebAPI/REST.pm
  lib/pf/access_filter/radius.pm
  lib/pf/api.pm
  lib/pf/config.pm
  lib/pf/constants/pfconf.pm
  lib/pf/radius.pm
  lib/pf/services/manager/radiusd_child.pm
  lib/pf/util.pm
  lib/pfconfig/namespaces/config/Authentication.pm
  raddb/dictionary.inverse
Labels: Status: For review, Type: Feature / Enhancement
