Repository inverse-inc/packetfence, pull requests merged in 2018-08, with the labels that each got.

#3445 various improvements to maintenance script
  addons/pf-maint.pl
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#3422 Pfappserver Updates
  html/pfappserver/root/static.alt/package.json
  html/pfappserver/root/static.alt/src/components/pfFormDatetime.vue
  html/pfappserver/root/static.alt/src/components/pfMixinSearchable.js
  html/pfappserver/root/static.alt/src/components/pfReportChart.vue
  html/pfappserver/root/static.alt/src/components/pfSearch.vue
  html/pfappserver/root/static.alt/src/components/pfSearchBoolean.vue
  html/pfappserver/root/static.alt/src/globals/pfReports.js
  html/pfappserver/root/static.alt/src/globals/pfSearch.js
  html/pfappserver/root/static.alt/src/main.js
  html/pfappserver/root/static.alt/src/store/base/searchable.js
  html/pfappserver/root/static.alt/src/styles/_variables.scss
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodeView.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesSearch.vue
  html/pfappserver/root/static.alt/src/views/Nodes/index.vue
  html/pfappserver/root/static.alt/src/views/Reports/_components/ReportTable.vue
  html/pfappserver/root/static.alt/src/views/Reports/_router/index.js
  html/pfappserver/root/static.alt/src/views/Reports/index.vue
  html/pfappserver/root/static.alt/src/views/Users/_components/UsersSearch.vue
Labels: Status: In progress, Status: Not ready

#3461 remove queue_stats pfmon job
  addons/upgrade/to-8.2-pfmon-conf.pl
  conf/pfmon.conf.defaults
  html/pfappserver/lib/pfappserver/Form/Config/Pfmon/queue_stats.pm
  lib/pf/UnifiedApi/Controller/Config/MaintenanceTasks.pm
Labels: Priority: Low, Status: For review, Type: Feature / Enhancement

#3501 enable/disable connection profile in web admin
  html/pfappserver/lib/pfappserver/Form/Config/ProfileCommon.pm
Labels: Priority: Low, Type: Feature / Enhancement

#3447 Add Monit docs to Installation Guide
  docs/PacketFence_Installation_Guide.asciidoc
Labels: Priority: Low, Status: For review

#3495 clarify difference between attribute and value directives
  conf/vlan_filters.conf.example
Labels: Priority: Low, Type: Feature / Enhancement

#3513 Syslog config for pfsso and etcd
  lib/pf/constants/syslog.pm
Labels: Priority: Low, Type: Feature / Enhancement

#3466 Pfappserver Updates
  html/pfappserver/root/static.alt/README.md
  html/pfappserver/root/static.alt/package.json
  html/pfappserver/root/static.alt/src/components/DeleteButton.vue
  html/pfappserver/root/static.alt/src/components/pfFormDatetime.vue
  html/pfappserver/root/static.alt/src/components/pfFormInput.vue
  html/pfappserver/root/static.alt/src/components/pfFormPrefixMultiplier.vue
  html/pfappserver/root/static.alt/src/components/pfFormToggle.vue
  html/pfappserver/root/static.alt/src/components/pfFormUpload.vue
  html/pfappserver/root/static.alt/src/components/pfMixinSavedSearch.vue
  html/pfappserver/root/static.alt/src/components/pfMixinSearchable.js
  html/pfappserver/root/static.alt/src/components/pfMixinSelectable.js
  html/pfappserver/root/static.alt/src/components/pfNotificationCenter.vue
  html/pfappserver/root/static.alt/src/components/pfSearch.vue
  html/pfappserver/root/static.alt/src/components/pfSearchBoolean.vue
  html/pfappserver/root/static.alt/src/globals/mysqlLimits.js
  html/pfappserver/root/static.alt/src/globals/pfFormatters.js
  html/pfappserver/root/static.alt/src/globals/pfRegExp.js
  html/pfappserver/root/static.alt/src/globals/pfReports.js
  html/pfappserver/root/static.alt/src/globals/pfSearch.js
  html/pfappserver/root/static.alt/src/main.js
  html/pfappserver/root/static.alt/src/store/base/searchable.js
  html/pfappserver/root/static.alt/src/store/modules/notification.js
  html/pfappserver/root/static.alt/src/utils/convert.js
  html/pfappserver/root/static.alt/src/utils/locale.js
  html/pfappserver/root/static.alt/src/views/Auditing/_components/RadiusLogsSearch.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodeView.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesCreate.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesSearch.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_router/index.js
  html/pfappserver/root/static.alt/src/views/Nodes/_store/index.js
  html/pfappserver/root/static.alt/src/views/Nodes/index.vue
  html/pfappserver/root/static.alt/src/views/Reports/_router/index.js
  html/pfappserver/root/static.alt/src/views/Status/_components/Services.vue
  html/pfappserver/root/static.alt/src/views/Users/_components/UserView.vue
  html/pfappserver/root/static.alt/src/views/Users/_components/UsersSearch.vue
  html/pfappserver/root/static.alt/src/views/Users/_router/index.js
  html/pfappserver/root/static.alt/src/views/Users/index.vue
Labels: Priority: Low, Status: For review

#3576 add CoA support to Meraki switches
  lib/pf/Switch/Meraki/MS220_8.pm
Labels: Priority: Low, Status: For review, Type: Feature / Enhancement

#3452 Advanced Filter improvement
  docs/PacketFence_Installation_Guide.asciidoc
  lib/pf/radius.pm
Labels: Status: For review, Type: Feature / Enhancement

#3484 Replace pfdhcp backend for options
  addons/monit/monit_checks_configurations/00_packetfence.tt
  addons/packages/packetfence.spec
  conf/documentation.conf
  conf/etcd.conf.yml.example
  conf/iptables.conf.example
  conf/pf.conf.defaults
  conf/systemd/packetfence-etcd.service
  db/pf-schema-X.Y.Z.sql
  db/upgrade-X.X.X-X.Y.Z.sql
  debian/control
  debian/packetfence-etcd.service
  debian/patches/debianize.patch
  debian/rules
  go/dhcp/README.md
  go/dhcp/api.go
  go/dhcp/etcd.go
  go/dhcp/keysoption.go
  go/dhcp/main.go
  go/vendor/vendor.json
  html/pfappserver/lib/pfappserver/I18N/en.po
  html/pfappserver/lib/pfappserver/I18N/fr.po
  lib/pf/cmd/pf/service.pm
  lib/pf/services/manager/etcd.pm
Labels: Status: For review, Type: Feature / Enhancement

#3463 Reorder iptables
  conf/iptables.conf.example
  lib/pf/iptables.pm
Labels: Status: For review, Type: Feature / Enhancement
