Repository inverse-inc/packetfence, pull requests merged in 2018-03, with the labels that each got.

#2959 Feature/go api namespace
  docs/api/spec/components/parameters/base.yaml
  docs/api/spec/components/responses/dhcp.yaml
  docs/api/spec/components/responses/ipset.yaml
  docs/api/spec/components/schemas/dhcp.yaml
  docs/api/spec/components/schemas/ipset.yaml
  docs/api/spec/paths/dhcp.yaml
  docs/api/spec/paths/ipset.yaml
  go/caddy/pfipset/handlers.go
  go/caddy/pfipset/pfipset.go
  go/caddy/pfipset/utils.go
  go/coredns/plugin/pfdns/pfdns.go
  go/dhcp/README.md
  go/dhcp/api.go
  go/dhcp/main.go
  go/unifiedapiclient/client_test.go
  go/vendor/vendor.json
  lib/pf/ipset.pm
  lib/pf/node.pm
  lib/pf/parking.pm
Labels: Priority: Low, Status: Not ready, Type: Feature / Enhancement

#2993 feature/remove-pfsetvlan
  addons/monit/monit_checks_configurations/10_packetfence-portsec.tt
  addons/packages/packetfence.spec
  conf/documentation.conf
  conf/log.conf.d/pfsetvlan.conf.example
  conf/pf.conf.defaults
  conf/systemd/packetfence-pfsetvlan.service
  debian/rules
  docs/PacketFence_Developers_Guide.asciidoc
  html/pfappserver/lib/pfappserver/I18N/en.po
  html/pfappserver/lib/pfappserver/I18N/fr.po
  lib/pf/Switch/Juniper.pm
  lib/pf/Switch/MockedSwitch.pm
  lib/pf/Switch/PacketFence.pm
  lib/pf/cmd/pf/service.pm
  lib/pf/enforcement.pm
  lib/pf/services/manager/pfsetvlan.pm
  lib/pf/services/manager/snmptrapd.pm
  packetfence.init
  sbin/pfqueue
  sbin/pfsetvlan
  t/TestUtils.pm
  t/pfsetvlan.t
Labels: Status: For review

#2992 feature/api-search
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Crud.pm
  lib/pf/UnifiedApi/Controller/Locationlogs.pm
  lib/pf/UnifiedApi/Plugin/RestCrud.pm
  lib/pf/UnifiedApi/Search.pm
  lib/pf/dal.pm
  lib/pf/error.pm
  t/unittest/UnifiedApi/Controller/Locationlogs.t
  t/unittest/UnifiedApi/Plugin/RestCrud.t
  t/unittest/UnifiedApi/Search.t
Labels: Status: For review

#2797 JAMF provisionner
  html/captive-portal/templates/provisioner/jamf.html
  html/pfappserver/lib/pfappserver/Form/Config/Provisioning/jamf.pm
  html/pfappserver/root/config/provisioning/type/jamf.tt
  lib/pf/provisioner/jamf.pm
Labels: Priority: Low, Status: For review, Type: Feature / Enhancement

#3002 Remap DHCP JSON response to accommodate draft-04 of the API specification
  docs/api/spec/components/schemas/dhcp.yaml
  docs/api/spec/components/schemas/ipset.yaml
  docs/api/spec/paths/services.yaml
  go/dhcp/README.md
  go/dhcp/api.go
  go/dhcp/main.go
Labels: Priority: High, Status: For review, Type: Bug, Type: Feature / Enhancement

#3024 Add statsd metrics
  conf/stats.conf.example
  go/interval/README.md
  go/interval/interval.go
  go/pfconfigdriver/structs.go
  go/stats/main.go
  go/stats/metrics.go
  go/stats/utils.go
Labels: Priority: High, Status: In progress, Type: Feature / Enhancement

#3039 Feature/rework pfipset sync
  conf/iptables.conf.example
  go/caddy/pfipset/handlers.go
  go/caddy/pfipset/pfipset.go
  go/caddy/pfipset/utils.go
  go/pfconfigdriver/fetch.go
  go/pfconfigdriver/structs.go
  go/sharedutils/util.go
  go/sharedutils/util_test.go
Labels: Priority: High, Status: For review, Type: Feature / Enhancement

#3058 Added cluster services status to API
  docs/api/spec/paths/services.yaml
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Services.pm
Labels: Priority: Medium, Status: Not ready, Type: Feature / Enhancement
