Repository inverse-inc/packetfence, pull requests merged in 2018-11, with the labels that each got.

#3727 adjustments to pfdhcp for multi-zone cluster
  go/dhcp/main.go
  go/dhcp/pool.go
Labels: Priority: Critical, Status: For review, Type: Bug

#3717 added cluster zones doc
  docs/PacketFence_Clustering_Guide.asciidoc
  docs/images/cluster-zones-registration.png
Labels: Status: For review, Type: Feature / Enhancement

#3756 Update Kickbox API docs
  docs/PacketFence_Installation_Guide.asciidoc
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement, Type: Nice to have

#3759 Remove old footnote, add note in LinkedIn Source.
  docs/PacketFence_Installation_Guide.asciidoc
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#3746 fix/password-of-the-day-template
  html/captive-portal/templates/emails/emails-guest_password_of_the_day.html
  html/captive-portal/templates/emails/emails-guest_password_of_the_day.mjml
Labels: Type: Bug

#3764 Add Twilio OAuth2 setup information to installation docs.
  docs/PacketFence_Installation_Guide.asciidoc
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement, Type: Nice to have

#3700 Pfappserver updates
  html/pfappserver/root/static.alt/package-lock.json
  html/pfappserver/root/static.alt/package.json
  html/pfappserver/root/static.alt/src/components/pfButtonDelete.vue
  html/pfappserver/root/static.alt/src/components/pfCSVParse.vue
  html/pfappserver/root/static.alt/src/components/pfConfigList.vue
  html/pfappserver/root/static.alt/src/components/pfConfigView.vue
  html/pfappserver/root/static.alt/src/components/pfFormSortableFields.vue
  html/pfappserver/root/static.alt/src/components/pfMixinEscapeKey.js
  html/pfappserver/root/static.alt/src/components/pfMixinSelectable.js
  html/pfappserver/root/static.alt/src/components/pfReportChart.vue
  html/pfappserver/root/static.alt/src/components/pfSavedSearch.vue
  html/pfappserver/root/static.alt/src/components/pfSearch.vue
  html/pfappserver/root/static.alt/src/components/pfSearchBoolean.vue
  html/pfappserver/root/static.alt/src/globals/pfValidators.js
  html/pfappserver/root/static.alt/src/views/Auditing/_components/RadiusLogsSearch.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/DomainView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/DomainsList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/FloatingDeviceView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/FloatingDevicesList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/RealmView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/RealmsList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/RoleView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/RolesList.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodeView.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesSearch.vue
  html/pfappserver/root/static.alt/src/views/Nodes/index.vue
  html/pfappserver/root/static.alt/src/views/Users/_components/UsersSearch.vue
  html/pfappserver/root/static.alt/src/views/Users/index.vue
Labels: Priority: Medium, Status: For review, Status: In progress

#3780 Use rsyslog.service in place syslog.service in Debian
  debian/rules
Labels: Priority: High, Status: For review

#3779 Feature/pfdhcp no roaring
  go/dhcp/api.go
  go/dhcp/config.go
  go/dhcp/main.go
  go/dhcp/pool/pool.go
  go/dhcp/pool/pool_test.go
  go/dhcp/utils.go
  go/dhcp/workers_pool.go
  go/vendor/vendor.json
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#3792 Add anchors and links on section titles in HTML doc
  docs/includes/global-attributes.asciidoc
Labels: Type: Feature / Enhancement

#3790 Fix/ntlm auth cache
  lib/pf/domain/ntlm_cache.pm
  lib/pf/util.pm
Labels: Status: For review

#3374 Feature/pfconfigpool locking timeout
  go/caddy/pfconfig/pool.go
  go/pfconfigdriver/pool.go
  go/timedlock/rw_lock.go
  go/timedlock/rw_lock_test.go
Labels: Priority: Medium, Status: For review

#3795 Avoid duplicates ip address sent by the dhcp
  go/dhcp/api.go
  go/dhcp/main.go
  go/dhcp/pool/pool.go
  go/dhcp/pool/pool_test.go
  go/dhcp/rawClient.go
  go/dhcp/utils.go
Labels: Status: For review, Type: Bug
