Repository inverse-inc/packetfence, pull requests merged in 2018-02, with the labels that each got.

#2803 Inline traffic shaping
  .gitignore
  addons/packages/packetfence.spec
  conf/documentation.conf
  conf/pf.conf.defaults
  conf/systemd/packetfence-tc.service
  conf/traffic_shaping.conf.example
  debian/packetfence-tc.service
  debian/rules
  docs/PacketFence_Inline_Deployment_Quick_Guide_ZEN.asciidoc
  html/pfappserver/lib/pfappserver/Controller/Config/TrafficShaping.pm
  html/pfappserver/lib/pfappserver/Form/Config/TrafficShaping.pm
  html/pfappserver/lib/pfappserver/Model/Config/Roles.pm
  html/pfappserver/lib/pfappserver/Model/Config/Switch.pm
  html/pfappserver/lib/pfappserver/Model/Config/TrafficShaping.pm
  html/pfappserver/lib/pfappserver/PacketFence/Controller/Config/Roles.pm
  html/pfappserver/lib/pfappserver/PacketFence/Controller/Config/TrafficShaping.pm
  html/pfappserver/lib/pfappserver/PacketFence/Controller/Configuration.pm
  html/pfappserver/root/config/roles/index.tt
  html/pfappserver/root/config/roles/list.tt
  html/pfappserver/root/config/roles/search.tt
  html/pfappserver/root/config/trafficshaping/clone.tt
  html/pfappserver/root/config/trafficshaping/create.tt
  html/pfappserver/root/config/trafficshaping/create_or_update.tt
  html/pfappserver/root/config/trafficshaping/create_type.tt
  html/pfappserver/root/config/trafficshaping/index.tt
  html/pfappserver/root/config/trafficshaping/list.tt
  html/pfappserver/root/config/trafficshaping/view.tt
  lib/pf/ConfigStore.pm
  lib/pf/ConfigStore/Switch.pm
  lib/pf/ConfigStore/TrafficShaping.pm
  lib/pf/api.pm
  lib/pf/config/traffic_shaping.pm
  lib/pf/config/util.pm
  lib/pf/constants/admin_roles.pm
  lib/pf/file_paths.pm
  lib/pf/generate_filter.pm
  lib/pf/ipset.pm
  lib/pf/services/manager/tc.pm
  lib/pf/util.pm
  lib/pfconfig/namespaces/config/TrafficShaping.pm
  packetfence.sudoers
  t/ConfigStore/Base.t
  t/unittest/generate_filter.t
Labels: Status: For review, Type: Feature / Enhancement

#2840 Doc/clustering shutdown upgrade
  docs/PacketFence_Clustering_Guide-docinfo.xml
  docs/PacketFence_Clustering_Guide.asciidoc
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#2918 Removed useless virtualhost in httpd.admin config
  conf/iptables.conf.example
  conf/pf.conf.defaults
  lib/pf/clustermgmt.pm
  lib/pf/dhcp/processor_v4.pm
  lib/pf/iptables.pm
  sbin/pfdhcplistener
Labels: Status: For review

#2940 Feature/api dhcpoption82
  docs/api/spec/components/schemas/dhcpoption82.yaml
  docs/api/spec/openapi.yaml
  docs/api/spec/paths/dhcpoption82s.yaml
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/DhcpOption82s.pm
  t/unittest/UnifiedApi/Controller/DhcpOption82s.t
Labels: Priority: Low, Status: For review, Type: Feature / Enhancement

#2953 Feature/api violation
  docs/api/spec/components/schemas/macaddress.yaml
  docs/api/spec/components/schemas/violation.yaml
  docs/api/spec/paths/violations.yaml
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Violations.pm
  t/unittest/UnifiedApi/Controller/Violations.t
Labels: Priority: Low, Status: For review, Type: Feature / Enhancement

#2952 Feature/api ip4log
  docs/api/spec/components/schemas/ip4log.yaml
  docs/api/spec/paths/ip4logs.yaml
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Ip4logs.pm
  t/unittest/UnifiedApi/Controller/Ip4logs.t
Labels: Priority: Low, Status: For review, Type: Feature / Enhancement

#2830 Network Device Doc Adding of the HP1910 Switch
  docs/PacketFence_Network_Devices_Configuration_Guide-docinfo.xml
  docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
Labels: Priority: Low, Status: For review, Type: Feature / Enhancement

#2685 Deregister a device on accounting stop
  conf/documentation.conf
  conf/pf.conf.defaults
  lib/pf/api.pm
Labels: Status: For review, Type: Feature / Enhancement

#2944 Feature/api service
  docs/api/spec/components/schemas/services.yaml
  docs/api/spec/paths/services.yaml
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller.pm
  lib/pf/UnifiedApi/Controller/Crud.pm
  lib/pf/UnifiedApi/Controller/Services.pm
  lib/pf/services.pm
  t/unittest/UnifiedApi/Controller/Services.t
Labels: Priority: Low, Status: For review, Type: Feature / Enhancement

#2961 Feature/api frontend token info
  docs/api/spec/paths/token_info.yaml
  go/api-frontend/aaa/authorization.go
  go/caddy/api-aaa/api-aaa.go
  go/caddy/api-aaa/api-aaa_test.go
Labels: Priority: Low, Status: For review, Type: Feature / Enhancement

#2909 Realm based username stripping
  addons/upgrade/to-8.0-authentication-conf.pl
  html/captive-portal/lib/captiveportal/Base/Actions.pm
  html/captive-portal/lib/captiveportal/PacketFence/Controller/Activate/Email.pm
  html/captive-portal/lib/captiveportal/PacketFence/Controller/Authenticate.pm
  html/captive-portal/lib/captiveportal/PacketFence/Controller/DeviceRegistration.pm
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Login.pm
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/SAML.pm
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Sponsor.pm
  html/pfappserver/lib/pfappserver/Authentication/Credential/Proxy.pm
  html/pfappserver/lib/pfappserver/Authentication/Store/PacketFence/User.pm
  html/pfappserver/lib/pfappserver/Base/Form/Role/InternalSource.pm
  html/pfappserver/lib/pfappserver/Form/Config/Realm.pm
  html/pfappserver/root/config/realm/view.tt
  lib/pf/Authentication/InternalRole.pm
  lib/pf/Authentication/Source/HtpasswdSource.pm
  lib/pf/Authentication/Source/KerberosSource.pm
  lib/pf/Authentication/Source/LDAPSource.pm
  lib/pf/Authentication/Source/RADIUSSource.pm
  lib/pf/api.pm
  lib/pf/authentication.pm
  lib/pf/config/util.pm
  lib/pf/constants/realm.pm
  lib/pf/pftest/authentication.pm
  lib/pf/radius.pm
  lib/pf/role.pm
  lib/pf/web/wispr.pm
  t/data/authentication.conf
  t/data/htpasswd-stripped.conf
  t/data/htpasswd-unstripped.conf
  t/data/realm.conf
  t/test_paths.pm
  t/unittest/authentication.t
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#2939 Feature/api auditlog
  docs/api/spec/components/schemas/radius_audit_log.yaml
  docs/api/spec/generate-openapi-spec.pl
  docs/api/spec/paths/radius_audit_logs.yaml
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/RadiusAuditLogs.pm
  t/unittest/UnifiedApi/Controller/RadiusAuditLogs.t
Labels: Priority: Low, Status: For review, Type: Feature / Enhancement

#2965 Adding CLI support on Aruba 5400 switches
  docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
  lib/pf/Switch/Aruba/5400.pm
Labels: Type: Feature / Enhancement

#2966 Feature/api authentication pf
  go/api-frontend/aaa/authentication.go
  go/api-frontend/aaa/authentication_backend.go
  go/api-frontend/aaa/db_authentication_backend.go
  go/api-frontend/aaa/pf_authentication_backend.go
  go/caddy/api-aaa/api-aaa.go
  html/pfappserver/lib/pfappserver/Authentication/Store/PacketFence/User.pm
  html/pfappserver/lib/pfappserver/Base/Form/Authentication/Action.pm
  html/pfappserver/lib/pfappserver/Form/Config/AdminRoles.pm
  html/pfappserver/lib/pfappserver/PacketFence/Model/User.pm
  lib/pf/Authentication/constants.pm
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller.pm
  lib/pf/UnifiedApi/Controller/Authentication.pm
  lib/pf/UnifiedApi/Controller/Crud.pm
  lib/pf/authentication.pm
  lib/pf/constants/admin_roles.pm
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#2982 Fix/captiveportal sms telephone validation v2
  conf/locale/en/LC_MESSAGES/packetfence.po
  html/captive-portal/lib/captiveportal/PacketFence/Form/Authentication.pm
Labels: Priority: Medium, Status: For review, Type: Bug
