Repository inverse-inc/packetfence, pull requests merged in 2018-09, with the labels that each got.

#3607 feature/pfdetect-config-error-handling
  lib/pf/config/builder.pm
  lib/pf/config/builder/pfdetect.pm
  lib/pf/pfcmd/checkup.pm
  lib/pfconfig/namespaces/config/Pfdetect.pm
Labels: Status: For review, Type: Feature / Enhancement

#3585 Pfappserver Updates
  html/pfappserver/root/static.alt/src/components/pfCSVParse.vue
  html/pfappserver/root/static.alt/src/components/pfFormUpload.vue
  html/pfappserver/root/static.alt/src/components/pfMixinSelectable.js
  html/pfappserver/root/static.alt/src/globals/pfFormatters.js
  html/pfappserver/root/static.alt/src/globals/pfValidators.js
  html/pfappserver/root/static.alt/src/main.js
  html/pfappserver/root/static.alt/src/views/Nodes/_api/index.js
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodeView.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesCreate.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesImport.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesSearch.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_router/index.js
  html/pfappserver/root/static.alt/src/views/Nodes/_store/index.js
  html/pfappserver/root/static.alt/src/views/Nodes/index.vue
  html/pfappserver/root/static.alt/src/views/Users/_store/index.js
Labels: Priority: Low, Status: In progress, Status: Not ready

#3621 require SSID field for Provisioner
  html/pfappserver/lib/pfappserver/Form/Config/Provisioning/mobileconfig.pm
Labels: Status: For review

#3586 feature/switch-invalidate-cache
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config/Switches.pm
Labels: Status: For review, Type: Feature / Enhancement

#3620 complete custom reports documentation
  docs/PacketFence_Installation_Guide.asciidoc
Labels: Status: For review, Type: Feature / Enhancement

#3500 Violation : improve doc
  html/pfappserver/lib/pfappserver/Form/Violation.pm
Labels: Priority: Low, Type: Feature / Enhancement

#3398 Improve PacketFence Developer's Guide
  docs/PacketFence_Developers_Guide.asciidoc
Labels: Priority: Low, Status: In progress, Type: Feature / Enhancement
