Repository inverse-inc/packetfence, pull requests merged in 2019-02, with the labels that each got.

#3970 Feature/api admin roles header
  go/api-frontend/aaa/authentication_backend.go
  go/api-frontend/aaa/authentication_backend_test.go
  go/api-frontend/aaa/authentication_test.go
  go/api-frontend/aaa/authorization.go
  go/api-frontend/aaa/authorization_test.go
  go/api-frontend/aaa/db_authentication_backend.go
  go/api-frontend/aaa/db_authentication_backend_test.go
  go/api-frontend/aaa/mem_token_backend.go
  go/api-frontend/aaa/mem_token_backend_test.go
  go/api-frontend/aaa/pf_authentication_backend.go
  go/api-frontend/aaa/token_backend.go
  go/caddy/api-aaa/api-aaa.go
  t/data/admin_roles.conf
Labels: Status: For review

#3944 Pfappserver Updates
  html/pfappserver/root/static.alt/src/components/InputRange.vue
  html/pfappserver/root/static.alt/src/components/pfFieldAccessDuration.vue
  html/pfappserver/root/static.alt/src/components/pfFieldTypeMatch.vue
  html/pfappserver/root/static.alt/src/components/pfFieldTypeValue.vue
  html/pfappserver/root/static.alt/src/components/pfFormFields.vue
  html/pfappserver/root/static.alt/src/components/pfFormRangeToggle.vue
  html/pfappserver/root/static.alt/src/components/pfFormRangeToggleDefault.vue
  html/pfappserver/root/static.alt/src/components/pfFormRangeTriple.vue
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfiguration.js
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationAccessDuration.js
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationSwitches.js
  html/pfappserver/root/static.alt/src/globals/pfAuthenticationConditions.js
  html/pfappserver/root/static.alt/src/globals/pfField.js
  html/pfappserver/root/static.alt/src/main.js
  html/pfappserver/root/static.alt/src/store/modules/config.js
  html/pfappserver/root/static.alt/src/views/Configuration/_api/index.js
  html/pfappserver/root/static.alt/src/views/Configuration/_components/AccessDurationView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/AuthenticationSourceView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/ConnectionProfileView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_router/index.js
  html/pfappserver/root/static.alt/src/views/Configuration/_store/bases.js
  html/pfappserver/root/static.alt/src/views/Configuration/index.vue
  html/pfappserver/root/static.alt/src/views/Users/_components/UsersCreate.vue
Labels: Status: For review

#3867 optimize voip detection for non-voip devices
  lib/pf/Switch.pm
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#4006 Configurable extraction of RADIUS Username
  conf/documentation.conf
  conf/pf.conf.defaults
  html/pfappserver/lib/pfappserver/I18N/en.po
  lib/pf/Switch.pm
  lib/pf/Switch/Avaya.pm
  lib/pf/Switch/Cisco/WLC.pm
  lib/pf/Switch/Meraki/MR_v2.pm
  lib/pf/Switch/Meraki/MS220_8.pm
  lib/pf/Switch/MockedSwitch.pm
  lib/pfconfig/namespaces/config/Pf.pm
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#3825 Add 802.1x + CoA support for FortiSwitch
  lib/pf/Switch/Fortinet/FortiSwitch.pm
Labels: Type: Feature / Enhancement

#4007 Added dimension filter to system dashboard graphs
  html/pfappserver/root/graph/dashboard.tt
Labels: Status: For review, Type: Feature / Enhancement

#3967 Unset the role on autoreg if no authentication source return a role
  conf/profiles.conf.defaults
  docs/api/spec/components/schemas/configconnectionprofile.yaml
  html/pfappserver/lib/pfappserver/Form/Config/Profile.pm
  html/pfappserver/lib/pfappserver/Form/Config/ProfileCommon.pm
  lib/pf/Connection/Profile.pm
  lib/pf/role.pm
  t/unittest/UnifiedApi/GenerateSpec.t
Labels: Status: For review, Type: Bug, Type: Feature / Enhancement

#4010 Fix sql request to detect the tenant id
  raddb/policy.d/packetfence
Labels: Priority: High, Status: For review, Type: Bug

#3961 Added a flag in node_cleanup task to bypass voip devices
  conf/pfmon.conf.defaults
  html/pfappserver/lib/pfappserver/Form/Config/Pfmon/node_cleanup.pm
  lib/pf/node.pm
  lib/pf/pfmon/task/node_cleanup.pm
Labels: Status: For review, Type: Feature / Enhancement

#4001 Feature/cluster servers api
  docs/api/spec/components/schemas/cluster.yaml
  docs/api/spec/paths/cluster.yaml
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Cluster.pm
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#3991 added hot-reload of passthroughs in pfdns
  conf/documentation.conf
  go/coredns/plugin/pfdns/pfconfig.go
  go/coredns/plugin/pfdns/pfdns.go
  go/coredns/plugin/pfdns/setup.go
Labels: Priority: Medium, Type: Feature / Enhancement

#3988 Feature/ssl certs api
  docs/api/spec/components/schemas/configcertificate.yaml
  docs/api/spec/paths/config/certificate.yaml
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config/Certificates.pm
  lib/pf/ssl.pm
  t/data/radius_ca.pem
  t/data/radius_server.crt
  t/data/radius_server.key
  t/data/server.crt
  t/data/server.key
  t/data/server.pem
  t/test_paths.pm
  t/unittest/UnifiedApi/Controller/Config/Certificates.t
  t/unittest/ssl.t
Labels: Status: For review, Type: Feature / Enhancement

#3966 Portal URL per network
  go/coredns/plugin/pfdns/pfdns.go
  go/coredns/plugin/pfdns/setup.go
  go/httpdispatcher/proxy.go
  go/httpdispatcher/proxy_test.go
  go/pfconfigdriver/structs.go
  html/captive-portal/lib/captiveportal/PacketFence/Model/Portal/Session.pm
  html/pfappserver/lib/pfappserver/Form/Config/Network.pm
  html/pfappserver/lib/pfappserver/I18N/en.po
  html/pfappserver/root/config/networks/view.tt
  lib/pf/ConfigStore/Network.pm
  lib/pf/factory/condition/profile.pm
  lib/pf/services/manager/haproxy_portal.pm
  lib/pf/validation/profile_filters.pm
Labels: Status: For review, Type: Feature / Enhancement
