Repository inverse-inc/packetfence, pull requests merged in 2019-12, with the labels that each got.

#4982 Added local_realm back in eduroam-cluster
  conf/radiusd/eduroam-cluster.example
  lib/pf/services/manager/radiusd_child.pm
Labels: Priority: High, Status: For review, Type: Bug

#4956 Deprecate 'AUTO-REGISTERED' string in node notes
  lib/pf/role.pm
Labels: Priority: Low, Status: For review, Type: Bug

#4835 Fix pfstats for ldaps and starttls
  go/stats/main.go
Labels: Priority: Low, Status: For review, Type: Bug

#4992 Don't call sudo to run scripts from security events
  UPGRADE.asciidoc
  html/pfappserver/root/static.alt/src/components/pfFormSecurityEventActions.vue
  lib/pf/action.pm
Labels: Priority: Medium, Status: For review

#4984 [CI] Install PacketFence packages built in the pipeline
  .gitlab-ci.yml
  addons/vagrant/.gitignore
  addons/vagrant/Vagrantfile
  addons/vagrant/collections_lockfile.yml
  addons/vagrant/inventory/group_vars/dev/gitlab_buildpkg_tools.yml
  addons/vagrant/inventory/group_vars/dev/packetfence_install.yml
  addons/vagrant/inventory/group_vars/nightly/gitlab_buildpkg_tools.yml
  addons/vagrant/inventory/group_vars/nightly/packetfence_install.yml
  addons/vagrant/requirements.yml
  addons/vagrant/site.yml
  ci/lib/install/Makefile
  ci/lib/install/manage-vagrant-vm.sh
  docs/PacketFence_Developers_Guide.asciidoc
Labels: Status: For review

#4970 Don't try to do firewall sso if the service is disabled
  lib/pf/firewallsso.pm
Labels: Priority: Low, Status: For review, Type: Feature / Enhancement

#5000 Various eduroam fix
  conf/radiusd/eduroam-cluster.example
  conf/radiusd/eduroam.example
  conf/radiusd/packetfence-cluster.example
  conf/radiusd/packetfence.example
  lib/pf/services/manager/radiusd_child.pm
Labels: Priority: Medium, Status: For review, Type: Bug
