Repository inverse-inc/packetfence, pull requests merged in 2019-05, with the labels that each got.

#4083 Fix scan engines && wmi tab
  html/pfappserver/lib/pfappserver/Model/Node/Tab/WMI.pm
  html/pfappserver/root/node/tab_WMI_process.tt
  html/pfappserver/root/node/tab_WMI_view.tt
  lib/pf/Connection/Profile.pm
  lib/pf/action.pm
  lib/pf/api.pm
  lib/pf/cmd/pf/schedule.pm
  lib/pf/node.pm
  lib/pf/registration.pm
  lib/pf/role.pm
  lib/pf/scan.pm
  lib/pf/security_event.pm
Labels: Status: For review, Type: Feature / Enhancement

#4281 Fix/4207
  lib/pf/constants.pm
  lib/pf/services/manager/pf.pm
  lib/pf/util/console.pm
Labels: Status: For review, Type: Bug

#4331 Remove Jessie and update docs for Stretch
  docs/PacketFence_Clustering_Guide.asciidoc
  docs/PacketFence_Installation_Guide.asciidoc
Labels: Status: For review

#4342 fix rights for monit scripts under Debian, fixes #4341
  debian/rules
Labels: Status: For review

#4376 Debian: move rsyslog restart **after** daemon-reload
  debian/packetfence.postinst
Labels: Status: For review

#4394 Debian9: fix permissions on server.key
  debian/packetfence.postinst
Labels: Status: For review

#4435 VoIP support for Dell switches
  docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
  lib/pf/Switch/Dell/N1500.pm
Labels: Status: For review, Type: Feature / Enhancement

#3999 fix/3854
  html/pfappserver/lib/pfappserver/Base/Form/Role/AllowedOptions.pm
  html/pfappserver/lib/pfappserver/PacketFence/Controller/Node.pm
  html/pfappserver/lib/pfappserver/PacketFence/Controller/User.pm
Labels: Priority: Medium, Type: Bug

#4529 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Type: Feature / Enhancement

#4541 Pfappserver - append "-copy" to id on clone
  html/pfappserver/root/static.alt/src/views/Configuration/_components/AdminRoleView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/AuthenticationSourceView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/BillingTierView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/ConnectionProfileView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/DeviceRegistrationView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/DomainView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/FingerbankCombinationView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/FingerbankDeviceView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/FingerbankDhcpFingerprintView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/FingerbankDhcpVendorView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/FingerbankDhcpv6EnterpriseView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/FingerbankDhcpv6FingerprintView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/FingerbankMacVendorView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/FingerbankUserAgentView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/FirewallView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/FloatingDeviceView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/PkiProviderView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/PortalModuleView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/ProvisioningView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/RealmView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/RoleView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/ScanEngineView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/SecurityEventView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/SwitchGroupView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/SwitchView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/SyslogForwarderView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/SyslogParserView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/WmiRuleView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/WrixLocationView.vue
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#4542 Pfappserver - User\Realm encoding
  html/pfappserver/root/static.alt/src/views/Users/_api/index.js
  lib/pf/UnifiedApi/Controller/Crud.pm
  t/unittest/UnifiedApi/Controller/Users.t
Labels: Priority: High, Status: For review, Type: Bug

#4562 Pfappserver add defaults to source rules
  html/pfappserver/root/static.alt/src/components/pfFieldRule.vue
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationAuthenticationSources.js
Labels: Priority: Medium, Status: For review

#4560 Pfappserver chosen improvements
  html/pfappserver/root/static.alt/src/components/pfFormChosen.vue
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfiguration.js
Labels: Priority: Medium, Status: For review
