Repository inverse-inc/packetfence, pull requests merged in 2019-07, with the labels that each got.

#4641 adjust lookup order of fingerbank devices classes
  lib/pf/fingerbank.pm
Labels: Priority: Medium, Status: For review

#4587 Pfappserver documentation viewer
  html/pfappserver/root/static.alt/README.md
  html/pfappserver/root/static.alt/package.json
  html/pfappserver/root/static.alt/src/App.vue
  html/pfappserver/root/static.alt/src/components/pfButtonHelp.vue
  html/pfappserver/root/static.alt/src/components/pfDocumentation.vue
  html/pfappserver/root/static.alt/src/router/index.js
  html/pfappserver/root/static.alt/src/store/index.js
  html/pfappserver/root/static.alt/src/store/modules/documentation.js
  html/pfappserver/root/static.alt/src/store/modules/events.js
  html/pfappserver/root/static.alt/src/styles/_navbar.scss
  html/pfappserver/root/static.alt/src/utils/api.js
  html/pfappserver/root/static.alt/src/views/Configuration/_components/AccessDurationView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/AdminRolesList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/AuthenticationSourcesList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/BillingTiersList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/ConnectionProfilesList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/DeviceRegistrationsList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/DomainsList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/FloatingDevicesList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/InlineView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/NetworkDevicesTabs.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/ParkingView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/ProvisioningsList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/RealmsList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/RolesList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/ScanEnginesList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/SecurityEventsList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/SnmpTrapView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/WmiRulesList.vue
  html/pfappserver/root/static.alt/src/views/Help/_router/index.js
  html/pfappserver/root/static.alt/src/views/Help/index.vue
Labels: Priority: Medium, Status: In progress, Status: Not ready, Type: Feature / Enhancement

#3934 PacketFence logs in the dashboard
  conf/monitoring/statsd.d/packetfence.conf.example
  conf/stats.conf.defaults
  go/stats/main.go
  go/vendor/vendor.json
  html/pfappserver/root/graph/dashboard.tt
  html/pfappserver/root/static.alt/src/views/Status/_components/Dashboard.vue
  lib/pf/constants/syslog.pm
  packetfence.rsyslog
Labels: Status: For review, Type: Feature / Enhancement

#4606 Family Zone firewall sso support
  go/firewallsso/factory.go
  go/firewallsso/familyzone.go
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/FamilyZone.pm
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationFirewalls.js
  html/pfappserver/root/static.alt/src/views/Configuration/_components/FirewallsList.vue
  lib/pf/UnifiedApi/Controller/Config/Firewalls.pm
  lib/pf/constants/firewallsso.pm
Labels: Status: For review, Type: Feature / Enhancement

#4663 Development environment can be set up automatically with Ansible and Vagrant
  .gitignore
  Makefile
  addons/dev-helpers/setup-dev-env.sh
  addons/dev-helpers/setup-go-env.sh
  addons/packages/build-go.sh
  addons/vagrant/.gitignore
  addons/vagrant/Vagrantfile
  addons/vagrant/ansible.cfg
  addons/vagrant/collections_lockfile.yml
  addons/vagrant/inventory/group_vars/dev/packetfence_install.yml
  addons/vagrant/inventory/group_vars/pfservers/packetfence_install.yml
  addons/vagrant/inventory/group_vars/pfservers/vagrant.yml
  addons/vagrant/inventory/hosts
  addons/vagrant/requirements.yml
  addons/vagrant/site.yml
  docs/PacketFence_Developers_Guide.asciidoc
  raddb/mods-available/mschap
Labels: Status: For review

#3938 Refactor pfdhcp
  go/dhcp/api.go
  go/dhcp/config.go
  go/dhcp/dictionary.go
  go/dhcp/keysoption.go
  go/dhcp/main.go
  go/dhcp/rawClient.go
  go/dhcp/server.go
  go/dhcp/serverif.go
  go/dhcp/utils.go
  go/dhcp/workers_pool.go
Labels: Status: For review, Type: Feature / Enhancement

#4079 Randomize the key balanced
  conf/documentation.conf
  conf/pf.conf.defaults
  conf/radiusd/packetfence-cluster.example
  conf/radiusd/packetfence-pre-proxy.example
  conf/radiusd/packetfence.example
  lib/pf/services/manager/radiusd_child.pm
  raddb/dictionary.inverse
  raddb/mods-available/attr_filter
  raddb/policy.d/packetfence
Labels: Status: For review, Type: Feature / Enhancement

#4642 Feature/sentinel one v2.0
  lib/pf/error.pm
  lib/pf/provisioner/sentinelone.pm
Labels: Status: For review

#4210 eduroam local realm proxy
  conf/radiusd/eduroam-cluster.example
  conf/radiusd/eduroam.example
  conf/radiusd/proxy.conf.inc.example
  html/pfappserver/lib/pfappserver/Form/Config/Realm.pm
  html/pfappserver/root/config/realm/view.tt
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationRealms.js
  lib/pf/services/manager/radiusd_child.pm
Labels: Status: For review, Type: Feature / Enhancement

#3454 Feature/status page config
  addons/packages/packetfence.spec
  addons/upgrade/to-9.1-selfservice-conf.pl
  conf/device_registration.conf.defaults
  conf/device_registration.conf.example
  conf/profiles.conf.defaults
  conf/self_service.conf.defaults
  conf/self_service.conf.example
  debian/packetfence.conffiles
  docs/PacketFence_Installation_Guide.asciidoc
  go/api-frontend/aaa/authorization.go
  html/captive-portal/lib/captiveportal/PacketFence/Controller/DeviceRegistration.pm
  html/captive-portal/lib/captiveportal/PacketFence/Controller/Node/Manager.pm
  html/captive-portal/lib/captiveportal/PacketFence/Controller/Status.pm
  html/captive-portal/templates/status.html
  html/pfappserver/lib/pfappserver/Controller/Config/SelfService.pm
  html/pfappserver/lib/pfappserver/Form/Config/ProfileCommon.pm
  html/pfappserver/lib/pfappserver/Form/Config/SelfService.pm
  html/pfappserver/lib/pfappserver/Model/Config/SelfService.pm
  html/pfappserver/lib/pfappserver/PacketFence/Controller/Config/SelfService.pm
  html/pfappserver/root/admin/configuration.tt
  html/pfappserver/root/config/deviceregistration/clone.tt
  html/pfappserver/root/config/deviceregistration/create.tt
  html/pfappserver/root/config/profile/tab-content.tt
  html/pfappserver/root/config/selfservice/clone.tt
  html/pfappserver/root/config/selfservice/create.tt
  html/pfappserver/root/config/selfservice/index.tt
  html/pfappserver/root/config/selfservice/list.tt
  html/pfappserver/root/config/selfservice/view.tt
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationAdminRoles.js
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationConnectionProfiles.js
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationSelfServices.js
  html/pfappserver/root/static.alt/src/globals/pfValidators.js
  html/pfappserver/root/static.alt/src/store/modules/config.js
  html/pfappserver/root/static.alt/src/views/Configuration/_api/index.js
  html/pfappserver/root/static.alt/src/views/Configuration/_components/SelfServiceView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/SelfServicesList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_router/index.js
  html/pfappserver/root/static.alt/src/views/Configuration/_store/selfServices.js
  html/pfappserver/root/static.alt/src/views/Configuration/index.vue
  html/pfappserver/root/static/admin/common.css
  lib/pf/ConfigStore/SelfService.pm
  lib/pf/Connection/Profile.pm
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config/SelfServices.pm
  lib/pf/admin_roles.pm
  lib/pf/config.pm
  lib/pf/constants/admin_roles.pm
  lib/pf/file_paths.pm
  lib/pf/pfcmd/checkup.pm
  lib/pfconfig/namespaces/config/Profiles.pm
  lib/pfconfig/namespaces/config/SelfService.pm
  t/unittest/UnifiedApi/Controller/Config/SelfServices.t
  t/unittest/UnifiedApi/GenerateSpec.t
Labels: Status: For review, Type: Feature / Enhancement

#4676 centralize the firewall SSO on the management node
  lib/pf/api/unifiedapiclient.pm
  lib/pf/firewallsso.pm
Labels: Status: For review

#3968 Feature/dhcp pool algorithm
  go/dhcp/config.go
  go/dhcp/pool/pool.go
  go/dhcp/pool/pool_test.go
  go/pfconfigdriver/structs.go
  html/pfappserver/lib/pfappserver/Form/Config/Network.pm
  html/pfappserver/root/config/networks/view.tt
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationLayer2Networks.js
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationRoutedNetworks.js
  lib/pf/constants/dhcp.pm
Labels: Status: For review, Type: Feature / Enhancement

#4681 added Juniper EX2200 module for Junos 15 and above
  lib/pf/Switch/Juniper/EX2200_v15.pm
Labels: Status: For review

#4678 Feature/configurable api logout
  conf/documentation.conf
  conf/pf.conf.defaults
  go/caddy/api-aaa/api-aaa.go
  go/pfconfigdriver/structs.go
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationAdvanced.js
Labels: Status: For review

#4630 Moved vlan_pool_technique configuration parameter to the connection profile
  addons/upgrade/to-9.1-move-vlan-pool-technique-parameter.pl
  conf/documentation.conf
  conf/pf.conf.defaults
  conf/profiles.conf.defaults
  docs/api/spec/components/schemas/configbase.yaml
  docs/api/spec/components/schemas/configconnectionprofile.yaml
  docs/api/spec/openapi.json
  docs/api/spec/openapi.yaml
  go/pfconfigdriver/structs.go
  html/pfappserver/lib/pfappserver/Form/Config/ProfileCommon.pm
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationAdvanced.js
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationConnectionProfiles.js
  lib/pf/constants/role.pm
  lib/pf/role/pool.pm
Labels: Status: For review, Type: Feature / Enhancement

#4605 Fix pfdhcp duplicates with big registration/inline network + pfstats call
  go/dhcp/api.go
  go/dhcp/config.go
  go/dhcp/main.go
  go/dhcp/pool/pool.go
  go/dhcp/pool/pool_test.go
Labels: Priority: High, Status: For review, Type: Bug
