Repository inverse-inc/packetfence, pull requests merged in 2019-03, with the labels that each got.

#3998 Add RADIUS disconnect support to smartzone module
  lib/pf/Switch/Ruckus/SmartZone.pm
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#3793 Add switch module to manage PICOS boxes
  docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
  lib/pf/Switch/Pica8.pm
  lib/pf/util/dictionary
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#4003 Pfappserver Config Options
  html/pfappserver/root/static.alt/src/components/pfFormChosen.vue
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfiguration.js
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationAuthenticationSources.js
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationConnectionProfiles.js
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationDomains.js
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationRealms.js
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationRoles.js
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationSwitchGroups.js
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationSwitches.js
  html/pfappserver/root/static.alt/src/views/Configuration/_api/index.js
  html/pfappserver/root/static.alt/src/views/Configuration/_components/AuthenticationSourceView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/AuthenticationSourcesList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/ConnectionProfileView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/DomainView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/RealmView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/RoleView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/SwitchGroupView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/SwitchView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_store/connectionProfiles.js
  html/pfappserver/root/static.alt/src/views/Configuration/_store/domains.js
  html/pfappserver/root/static.alt/src/views/Configuration/_store/realms.js
  html/pfappserver/root/static.alt/src/views/Configuration/_store/roles.js
  html/pfappserver/root/static.alt/src/views/Configuration/_store/sources.js
  html/pfappserver/root/static.alt/src/views/Configuration/_store/switchGroups.js
  html/pfappserver/root/static.alt/src/views/Configuration/_store/switches.js
Labels: Status: In progress, Status: Not ready

#4016 Disable AD join os check option
  conf/documentation.conf
  conf/pf.conf.defaults
  html/pfappserver/lib/pfappserver/I18N/en.po
  html/pfappserver/lib/pfappserver/PacketFence/Controller/Config/Domain.pm
Labels: Status: For review, Type: Feature / Enhancement

#3936 mysql new configuration parameters
  conf/documentation.conf
  conf/mariadb/mariadb.conf.tt.example
  conf/pf.conf.defaults
  html/pfappserver/lib/pfappserver/I18N/en.po
  html/pfappserver/lib/pfappserver/I18N/fr.po
  lib/pf/cmd/pf/generatemariadbconfig.pm
Labels: Status: For review, Type: Feature / Enhancement

#3866 Feature/local account module
  conf/portal_modules.conf.defaults
  html/captive-portal/lib/captiveportal/DynamicRouting/Module/ShowLocalAccount.pm
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Root.pm
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/ShowLocalAccount.pm
  html/captive-portal/templates/account.html
  html/pfappserver/lib/pfappserver/Form/Config/PortalModule/ShowLocalAccount.pm
Labels: Priority: Medium, Type: Feature / Enhancement

#4017 Add support for Let's Encrypt through API
  addons/packages/packetfence.spec
  conf/caddy-services/httpdispatcher.conf.example
  conf/documentation.conf
  conf/passthrough.lua.tt.example
  conf/pf.conf.defaults
  debian/rules
  docs/api/spec/components/schemas/configcertificate.yaml
  docs/api/spec/paths/config/certificate.yaml
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config/Certificates.pm
  lib/pf/cmd/pf/renew_lets_encrypt.pm
  lib/pf/file_paths.pm
  lib/pf/ssl.pm
  lib/pf/ssl/lets_encrypt.pm
  packetfence.cron.d
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#4047 Support for Debian 9
  debian/control
  debian/packetfence-config.postinst
  debian/packetfence-config.postrm
  debian/packetfence-config.prerm
  debian/packetfence-redis-cache.postinst
  debian/packetfence-redis-cache.postrm
  debian/packetfence-redis-cache.prerm
  debian/packetfence-remote-arp-sensor.postinst
  debian/packetfence-remote-arp-sensor.postrm
  debian/packetfence-remote-arp-sensor.prerm
  debian/packetfence.postinst
  debian/packetfence.postrm
  debian/packetfence.preinst
  debian/packetfence.prerm
  debian/rules
  lib/pf/UnifiedApi/Controller/Queues.pm
  lib/pf/pfmon/task/switch_cache_lldpLocalPort_description.pm
  raddb/certs/Makefile
  raddb/certs/README
  raddb/certs/bootstrap
Labels: Status: For review, Type: Feature / Enhancement, os specific: Debian

#4012 Added exception when the dns request is for a portal detection url
  go/coredns/plugin/pfdns/pfdns.go
  go/coredns/plugin/pfdns/setup.go
Labels: Status: For review, Type: Bug

#3784 dhcp filters
  conf/dhcp_filters.conf.example
  go/dhcp/api.go
  go/dhcp/dictionary.go
  go/dhcp/main.go
  go/dhcp/utils.go
  lib/pf/access_filter/dhcp.pm
Labels: Status: For review, Type: Feature / Enhancement

#4029 Fix realm attribute on machine authentication
  conf/radiusd/packetfence-tunnel.example
  conf/radiusd/packetfence.example
  raddb/policy.d/packetfence
Labels: Priority: Low, Type: Bug

#4020 Move accounting cleanup to pfmon
  addons/backup-and-maintenance.sh
  conf/pfmon.conf.defaults
  lib/pf/accounting.pm
  lib/pf/dal.pm
  lib/pf/pfmon/task/acct_cleanup.pm
Labels: Status: For review, Type: Feature / Enhancement

#4071 Fix redirection url for a portal module
  html/captive-portal/lib/captiveportal/Base/Actions.pm
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Application.pm
Labels: Priority: Medium, Status: For review

#4078 Ruckus role support
  docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
  docs/images/Ruckus_CreateNewRole.png
  docs/images/Ruckus_Roles.png
  lib/pf/Switch/Ruckus.pm
Labels: Status: For review, Type: Feature / Enhancement

#4098 keep connections to Unified API persistent
  lib/pf/api/unifiedapiclient.pm
Labels: Priority: High

#4097 Use the ip address of the AD server to fetch the nt_hash.
  lib/pf/domain/ntlm_cache.pm
Labels: Status: For review, Type: Bug

#4002 VPN Support
  docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
  lib/pf/Connection.pm
  lib/pf/Switch.pm
  lib/pf/Switch/Cisco/ASA.pm
  lib/pf/Switch/Fortinet/FortiGate.pm
  lib/pf/config.pm
  lib/pf/constants/config.pm
  lib/pf/enforcement.pm
  lib/pf/radius.pm
  lib/pf/radius/rest.pm
  lib/pf/util/radius.pm
Labels: Status: For review, Type: Feature / Enhancement

#3993 use a fresh struct everytime we fetch pfconfig
  go/pfconfigdriver/fetch.go
Labels: Priority: High, Status: For review, Type: Bug

#4099 allow to skip management node in portal load-balancing
  conf/documentation.conf
  conf/pf.conf.defaults
  html/pfappserver/lib/pfappserver/I18N/en.po
  lib/pf/services/manager/haproxy_portal.pm
Labels: Priority: Low, Type: Feature / Enhancement

#4114 If no searchattributes don't generate the ldap configuration
  lib/pf/services/manager/radiusd_child.pm
Labels: Status: For review, Type: Feature / Enhancement

#4115 Removed references to MAC detection VLAN
  addons/integration-testing/violations.conf
  addons/upgrade/to-8.3-authentication-searchattributes.pl
  addons/upgrade/to-9.0-remove_mac_detection.sh
  conf/switches.conf.defaults
  conf/ui-global.conf.example
  conf/ui.conf
  conf/ui.conf.es_ES
  docs/PacketFence_Installation_Guide.asciidoc
  docs/api/spec/components/schemas/configswitchgroup.yaml
  docs/api/spec/openapi.json
  docs/api/spec/openapi.yaml
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationSwitchGroups.js
  lib/pf/Switch.pm
  lib/pf/Switch/Cisco.pm
  lib/pf/Switch/Dlink/DES_3526.pm
  lib/pf/Switch/MockedSwitch.pm
  lib/pf/cmd/pf/switchconfig.pm
  lib/pf/constants/role.pm
  lib/pf/constants/security_event.pm
  lib/pf/floatingdevice.pm
  lib/pf/task/pfsnmp.pm
  t/SNMP.t
  t/data/all-switch-types.conf
  t/data/bug766/switches.conf
  t/data/switches.conf
  t/floatingdevice.t
  t/hardware-snmp-objects.t
Labels: Status: For review, Type: Nice to have

#3679 adjust locationlog to have its own voip column
  db/pf-schema-X.Y.Z.sql
  db/upgrade-X.X.X-X.Y.Z.sql
  lib/pf/locationlog.pm
Labels: Priority: Medium, Status: For review

#4015 Statsd port configuration
  addons/packages/packetfence.spec
  conf/documentation.conf
  conf/pf.conf.defaults
  conf/radiusd/mschap.conf.example
  debian/packetfence.conffiles
  go/pfconfigdriver/structs.go
  go/stats/main.go
  html/pfappserver/lib/pfappserver/I18N/en.po
  lib/pf/StatsD.pm
  lib/pf/services/manager/netdata.pm
  lib/pf/services/manager/radiusd_child.pm
  raddb/mods-enabled/mschap
Labels: Status: For review, Type: Feature / Enhancement

#4124 Feature/key value store
  db/pf-schema-X.Y.Z.sql
  db/upgrade-X.X.X-X.Y.Z.sql
  docs/api/spec/components/schemas/preference.yaml
  docs/api/spec/components/schemas/preferenceslist.yaml
  docs/api/spec/paths/preference.yaml
  docs/api/spec/paths/preferences.yaml
  go/api-frontend/aaa/authorization.go
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Preferences.pm
  lib/pf/dal/_user_preference.pm
  lib/pf/dal/user_preference.pm
  t/unittest/UnifiedApi/Controller/Preferences.t
Labels: Status: For review, Type: Feature / Enhancement

#4106 Feature/api networks
  html/pfappserver/lib/pfappserver/Form/Config/Network/Routed.pm
  lib/pf/ConfigStore/Filtered.pm
  lib/pf/ConfigStore/L2Network.pm
  lib/pf/ConfigStore/RoutedNetwork.pm
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config/L2Networks.pm
  lib/pf/UnifiedApi/Controller/Config/RoutedNetworks.pm
Labels: Status: For review, Type: Feature / Enhancement

#4104 Feature/api interfaces
  docs/api/spec/components/schemas/configinterface.yaml
  docs/api/spec/paths/config/interface.yaml
  go/api-frontend/aaa/authorization.go
  html/pfappserver/lib/pfappserver/Model/Interface.pm
  lib/pf/I18N/pfappserver.pm
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config/Interfaces.pm
Labels: Status: For review, Type: Feature / Enhancement

#4162 Feature/api frontend token expiration++
  go/api-frontend/aaa/authentication.go
  go/api-frontend/aaa/authentication_test.go
  go/api-frontend/aaa/authorization.go
  go/api-frontend/aaa/authorization_test.go
  go/api-frontend/aaa/mem_token_backend.go
  go/api-frontend/aaa/mem_token_backend_test.go
  go/api-frontend/aaa/token_backend.go
  go/caddy/api-aaa/api-aaa.go
Labels: Status: For review
