Repository inverse-inc/packetfence, pull requests merged in 2019-04, with the labels that each got.

#3906 Additional Daemon dns and dhcp
  conf/documentation.conf
  conf/iptables.conf.example
  go/coredns/plugin/pfdns/pfdns.go
  go/dhcp/config.go
  go/dhcp/main.go
  go/dhcp/utils.go
  go/pfconfigdriver/structs.go
  go/sharedutils/util.go
  html/pfappserver/lib/pfappserver/Form/Interface.pm
  html/pfappserver/lib/pfappserver/Model/Interface.pm
  html/pfappserver/lib/pfappserver/PacketFence/Controller/Interface.pm
  lib/pf/config.pm
  lib/pf/iptables.pm
  lib/pf/pfcmd/checkup.pm
  lib/pfconfig/namespaces/interfaces.pm
  lib/pfconfig/namespaces/interfaces/dhcp_ints.pm
  lib/pfconfig/namespaces/interfaces/dns_ints.pm
Labels: Status: For review, Type: Feature / Enhancement

#4188 Fix for juniperSRX firewall
  docs/firewall/junipersrx.asciidoc
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/JuniperSRX.pm
Labels: Priority: Low, Status: For review, Type: Bug

#4155 Feature/domain queue join
  conf/caddy-services/api.conf.example
  go/caddy/caddy/caddy/caddymain/run.go
  go/caddy/caddy/caddyhttp/httpserver/plugin.go
  go/caddy/job-status/job-status.go
  go/caddy/job-status/job-status_test.go
  go/vendor/vendor.json
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config/Domains.pm
  lib/pf/constants/pfqueue.pm
  lib/pf/pfqueue/consumer/redis.pm
  lib/pf/pfqueue/producer/redis.pm
  lib/pf/pfqueue/status_updater.pm
  lib/pf/pfqueue/status_updater/dummy.pm
  lib/pf/pfqueue/status_updater/redis.pm
  lib/pf/task.pm
  lib/pf/task/domain.pm
Labels: Status: For review

#4134 Feature/api custom reports
  docs/api/spec/components/schemas/dynamicreports.yaml
  docs/api/spec/components/schemas/dynamicreportsearch.yaml
  docs/api/spec/paths/dynamicreports.yaml
  go/api-frontend/aaa/authorization.go
  html/pfappserver/lib/pfappserver/PacketFence/Controller/Admin.pm
  html/pfappserver/lib/pfappserver/PacketFence/Controller/DynamicReport.pm
  html/pfappserver/lib/pfappserver/PacketFence/Controller/Graph.pm
  html/pfappserver/root/admin/status.tt
  html/pfappserver/root/admin/wrapper.tt
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationAdminRoles.js
  lib/pf/Report.pm
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/DynamicReports.pm
  lib/pf/admin_roles.pm
  lib/pf/constants/admin_roles.pm
  t/unittest/UnifiedApi/Controller/DynamicReports.t
Labels: Status: For review, Type: Feature / Enhancement

#3937 Aerohive AP/Switch support
  lib/pf/Switch/AeroHIVE/AP.pm
  lib/pf/locationlog.pm
Labels: Status: Not ready, Type: Feature / Enhancement

#3986 Security events GUI
  html/pfappserver/root/static.alt/src/components/pfFormSecurityEventTrigger.vue
  html/pfappserver/root/static.alt/src/components/pfFormSecurityEventTriggerHeader.vue
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationSecurityEvents.js
  html/pfappserver/root/static.alt/src/styles/_card.scss
  html/pfappserver/root/static.alt/src/styles/_popover.scss
  html/pfappserver/root/static.alt/src/styles/global.scss
  html/pfappserver/root/static.alt/src/views/Configuration/_components/SecurityEventView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/SecurityEventsList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_router/index.js
Labels: Status: For review

#4275 Improve documentation conventions
  docs/PacketFence_Developers_Guide.asciidoc
Labels: Status: For review

#4211 Added Aruba Instant Access switch module (for CoA)
  lib/pf/Switch/Aruba/Instant_Access.pm
Labels: Status: For review, Type: Feature / Enhancement

#4119 Feature/accounting triggers history
  html/pfappserver/root/security_event/view.tt
  lib/pf/accounting.pm
  lib/pf/accounting_events_history.pm
  lib/pf/factory/condition/security_event.pm
  lib/pf/security_event.pm
  t/unittest/accounting_events_history.t
Labels: Status: For review, Type: Feature / Enhancement

#3827 Change defaults conf files: portal_modules, profiles and switches
  conf/switches.conf.example
Labels: Priority: Medium, Type: Feature / Enhancement
