Repository inverse-inc/packetfence, pull requests merged in 2019-10, with the labels that each got.

#4766 allow to force the access duration when using device registration
  html/captive-portal/lib/captiveportal/PacketFence/Controller/DeviceRegistration.pm
  html/pfappserver/lib/pfappserver/Form/Config/SelfService.pm
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationSelfServices.js
  lib/pfconfig/namespaces/config/SelfService.pm
Labels: Status: For review

#4824 feature/speedup-dal-generation
  addons/dev-helpers/bin/generator-data-access-layer.pl
  addons/dev-helpers/templates/class-wrapper.tt
  lib/pf/dal/_action.pm
  lib/pf/dal/_activation.pm
  lib/pf/dal/_auth_log.pm
  lib/pf/dal/_billing.pm
  lib/pf/dal/_chi_cache.pm
  lib/pf/dal/_class.pm
  lib/pf/dal/_dhcp_option82.pm
  lib/pf/dal/_dhcp_option82_history.pm
  lib/pf/dal/_dns_audit_log.pm
  lib/pf/dal/_inline_accounting.pm
  lib/pf/dal/_ip4log.pm
  lib/pf/dal/_ip4log_archive.pm
  lib/pf/dal/_ip4log_history.pm
  lib/pf/dal/_ip6log.pm
  lib/pf/dal/_ip6log_archive.pm
  lib/pf/dal/_ip6log_history.pm
  lib/pf/dal/_key_value_storage.pm
  lib/pf/dal/_keyed.pm
  lib/pf/dal/_locationlog.pm
  lib/pf/dal/_locationlog_archive.pm
  lib/pf/dal/_node_category.pm
  lib/pf/dal/_password.pm
  lib/pf/dal/_person.pm
  lib/pf/dal/_pf_version.pm
  lib/pf/dal/_radacct.pm
  lib/pf/dal/_radacct_log.pm
  lib/pf/dal/_radius_audit_log.pm
  lib/pf/dal/_radius_nas.pm
  lib/pf/dal/_savedsearch.pm
  lib/pf/dal/_scan.pm
  lib/pf/dal/_security_event.pm
  lib/pf/dal/_sms_carrier.pm
  lib/pf/dal/_tenant.pm
  lib/pf/dal/_user_preference.pm
  lib/pf/dal/_userlog.pm
  lib/pf/dal/_wrix.pm
Labels: Priority: High

#4841 Ready-to-use Docker images for PacketFence builds
  .gitlab-ci.yml
  addons/dev-helpers/setup-go-env.sh
  addons/packages/build-go.sh
  ci/packer/Makefile
  ci/packer/README.asciidoc
  ci/packer/buildpkg.json
  ci/packer/provisionners/install-go-dependencies.sh
  ci/packer/provisionners/inventory/group_vars/centos/gitlab_buildpkg_tools.yml
  ci/packer/provisionners/inventory/group_vars/centos/rpm_keys.yml
  ci/packer/provisionners/inventory/group_vars/debian/gitlab_buildpkg_tools.yml
  ci/packer/provisionners/inventory/group_vars/rubygems/rubygems.yml
  ci/packer/provisionners/inventory/host_vars/default.yml
  ci/packer/provisionners/playbooks/rubygems.yml
  ci/packer/provisionners/requirements.yml
  ci/packer/provisionners/site.yml
  ci/packer/provisionners/upstream/rpm_keys/nodesource.rpm.key
  config.mk
  docs/PacketFence_Developers_Guide.asciidoc
  docs/go/README.asciidoc
  docs/packer/README.asciidoc
  go/.gitignore
  go/Makefile
  go/README.asciidoc
  go/README.md
  go/go.mod
  go/go.sum
  go/vendor/vendor.json
Labels: Status: For review

#4832 Migrate to go mod for Golang binaries
  go/Makefile
Labels: Status: Not ready

#4843 Improve Vagrant and Ansible provisioning for pipeline
  addons/vagrant/Vagrantfile
  addons/vagrant/inventory/group_vars/all/packetfence_install__api_calls.yml
  addons/vagrant/inventory/group_vars/all/packetfence_install__nodes.yml
  addons/vagrant/inventory/group_vars/all/packetfence_install__sources.yml
  addons/vagrant/inventory/group_vars/all/packetfence_install__users.yml
  addons/vagrant/inventory/group_vars/nightly/gitlab_buildpkg_tools.yml
  addons/vagrant/inventory/group_vars/nightly/packetfence_install.yml
  addons/vagrant/inventory/group_vars/pfservers/packetfence_install.yml
  addons/vagrant/inventory/hosts
  addons/vagrant/requirements.yml
  addons/vagrant/site.yml
  docs/PacketFence_Developers_Guide.asciidoc
Labels: Status: For review

#4852 Adjustements for Packer builds in CI
  .gitlab-ci.yml
  ci/packer/Makefile
  ci/packer/pfbuild.json
  ci/packer/provisionners/inventory/host_vars/default.yml
  config.mk
Labels: Status: Not ready

#4846 Build of Debian and RPM packages in a GitLab pipeline
  .gitlab-ci.yml
  Makefile
  README.md
  ci/debian/.devscripts
  ci/debian/convert-to-native-package.sh
  debian/changelog
  debian/control
  debian/rules
  rpm/.rpmmacros
  rpm/packetfence-release/packetfence-release.spec
  rpm/packetfence.spec
  rpm/source
Labels: Status: For review

#4864 CLI-Access connection profile filter.
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfiguration.js
  html/pfappserver/root/static.alt/src/globals/pfField.js
  lib/pf/Authentication/Source.pm
  lib/pf/Connection.pm
  lib/pf/radius.pm
Labels: Status: For review, Type: Feature / Enhancement

#4863 Switch filter reevaluate scope
  conf/switch_filters.conf.example
  lib/pf/access_filter/switch.pm
  lib/pf/api.pm
  lib/pf/enforcement.pm
  lib/pf/radius.pm
Labels: Status: For review, Type: Feature / Enhancement

#4869 feature/bulk_import
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller.pm
  lib/pf/UnifiedApi/Controller/Nodes.pm
  lib/pf/UnifiedApi/Controller/Users.pm
  lib/pf/import.pm
Labels: Status: For tracking, Type: Feature / Enhancement

#4848 feature/switch_template
  .gitignore
  addons/dev-helpers/bin/generator-template-switches-defaults.pl
  conf/template_switches.conf.defaults
  conf/template_switches.conf.example
  docs/PacketFence_Developers_Guide.asciidoc
  docs/developer/template_switches.asciidoc
  html/pfappserver/lib/pfappserver/Form/Config/Switch.pm
  lib/pf/Switch/Aruba.pm
  lib/pf/Switch/Aruba/Instant_Access.pm
  lib/pf/Switch/ArubaSwitch.pm
  lib/pf/Switch/Avaya.pm
  lib/pf/Switch/Cisco/Aironet_1600.pm
  lib/pf/Switch/PacketFence/Standard.def
  lib/pf/Switch/Template.pm
  lib/pf/SwitchFactory.pm
  lib/pf/config/builder/template_switches.pm
  lib/pf/file_paths.pm
  lib/pf/mini_template.pm
  lib/pf/pfcmd/checkup.pm
  lib/pf/radius.pm
  lib/pf/util/template_switch.pm
  lib/pfconfig/namespaces/config/TemplateSwitches.pm
  t/SwitchFactory.t
  t/data/switches.conf
  t/unittest/Switch/Template.t
  t/unittest/config/builder/template_switches.t
  t/unittest/mini_template.t
  t/unittest/pfconfig/cached_hash.t
Labels: Status: For review, Type: Feature / Enhancement

#4860 Set a default timeout for ipset inline set
  lib/pf/ipset.pm
Labels: Status: For review, Type: Feature / Enhancement

#4827 CSV Import Improvements
  html/pfappserver/root/static.alt/src/components/pfCSVImport.vue
  html/pfappserver/root/static.alt/src/components/pfCSVParse.vue
  html/pfappserver/root/static.alt/src/components/pfFormFields.vue
  html/pfappserver/root/static.alt/src/components/pfFormRow.vue
  html/pfappserver/root/static.alt/src/components/pfFormSelect.vue
  html/pfappserver/root/static.alt/src/components/pfFormUpload.vue
  html/pfappserver/root/static.alt/src/components/pfMixinValidation.js
  html/pfappserver/root/static.alt/src/main.js
  html/pfappserver/root/static.alt/src/store/base/file.js
  html/pfappserver/root/static.alt/src/utils/encoding.js
  html/pfappserver/root/static.alt/src/views/Configuration/_components/CertificatesView.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_api/index.js
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesImport.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_store/index.js
  html/pfappserver/root/static.alt/src/views/Users/_api/index.js
  html/pfappserver/root/static.alt/src/views/Users/_components/UserView.vue
  html/pfappserver/root/static.alt/src/views/Users/_components/UsersImport.vue
  html/pfappserver/root/static.alt/src/views/Users/_components/UsersPreviewModal.vue
  html/pfappserver/root/static.alt/src/views/Users/_store/index.js
Labels: Status: In progress, Status: Not ready
