Repository inverse-inc/packetfence, pull requests merged in 2019-11, with the labels that each got.

#4884 Packer: prepare Docker images for release
  .gitlab-ci.yml
  ci/packer/Makefile
  ci/packer/pfbuild.json
  ci/packer/provisionners/inventory/group_vars/devel_centos/gitlab_buildpkg_tools.yml
  ci/packer/provisionners/inventory/group_vars/devel_centos/rpm_keys.yml
  ci/packer/provisionners/inventory/group_vars/devel_debian/gitlab_buildpkg_tools.yml
  ci/packer/provisionners/inventory/group_vars/devel_rubygems/rubygems.yml
  ci/packer/provisionners/inventory/group_vars/stable_centos/gitlab_buildpkg_tools.yml
  ci/packer/provisionners/inventory/group_vars/stable_centos/rpm_keys.yml
  ci/packer/provisionners/inventory/group_vars/stable_debian/gitlab_buildpkg_tools.yml
  ci/packer/provisionners/inventory/group_vars/stable_rubygems/rubygems.yml
  ci/packer/provisionners/playbooks/rubygems.yml
  ci/packer/provisionners/site.yml
  config.mk
Labels: Status: For review

#4872 Installation guide refactor
  docs/PacketFence_Installation_Guide.asciidoc
  docs/images/ACME1.png
  docs/images/Connection_filter.png
  docs/images/MSE_Tab.png
  docs/images/acme.com.png
  docs/images/billing/authorize-packetfence-config.png
  docs/images/billing/billing-tier.png
  docs/images/billing/paypal-packetfence-configuration.png
  docs/images/billing/stripe-packetfence-configuration.png
  docs/images/domain-add-realm.png
  docs/images/domain-add.png
  docs/images/domain-default-realm.png
  docs/images/domain-ntlm-cache.png
  docs/images/domain-realms-index.png
  docs/images/packetfence-pki-eaptls-sign-example.png
  docs/images/portal-modules/chained_oauth_sms.png
  docs/images/portal-modules/hello_world-my_first_root_module.png
  docs/images/portal-modules/hello_world.png
  docs/images/portal-modules/login_or_boarding.png
  docs/images/portal-modules/prompt_fields.png
  docs/images/portal-modules/sms.png
  docs/images/portal-modules/token_system.png
  docs/images/rapid7/rapid7-connection-profile.png
  docs/images/rapid7/rapid7-syslog-parser.png
  docs/images/rapid7/rapid7-violation-trigger.png
  docs/images/saml-packetfence-config.png
  docs/images/scep-ms-pki-eaptls-example.png
  docs/images/survey-portal-module.png
  docs/images/survey-root-portal-module.png
Labels: Documentation

#4880 Upload DEB and RPM packages built in pipeline
  .gitlab-ci.yml
  ci/upload/deploy-packages.sh
Labels: Status: For review

#4780 Mysql Master Slave Support
  addons/makeslave.pl
  conf/documentation.conf
  conf/haproxy-db.conf.example
  conf/mariadb/mariadb.conf.tt.example
  conf/pf.conf.defaults
  docs/PacketFence_Clustering_Guide.asciidoc
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationDatabaseAdvanced.js
  lib/pf/cluster.pm
  lib/pf/cmd/pf/generatemariadbconfig.pm
  lib/pf/config/cluster.pm
  lib/pf/pfcmd/checkup.pm
  lib/pf/services/manager/haproxy_db.pm
Labels: Status: For review, Type: Feature / Enhancement

#4877 Multiple Input element w/ variable separator
  html/pfappserver/root/static.alt/src/components/pfConfigView.vue
  html/pfappserver/root/static.alt/src/components/pfFormChosen.vue
  html/pfappserver/root/static.alt/src/components/pfFormInputMultiple.vue
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationAuthenticationSources.js
  html/pfappserver/root/static.alt/src/styles/_form-chosen.scss
  html/pfappserver/root/static.alt/src/styles/global.scss
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#4887 Juniper EX2300 CoA Port Bounce
  lib/pf/Switch/Juniper/EX2300.pm
  lib/pf/util/dictionary
Labels: Type: Feature / Enhancement

#4894 Package correctly go and html directories in RPM
  Makefile
  config.mk
  debian/rules
  go/Makefile
  rpm/packetfence.spec
Labels: Status: For review, builds

#4896 Make MySQL upgrade script echo comments and safely re-runnable
  db/upgrade-X.X.X-X.Y.Z.sql
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#4753 Added internal event on production network versus managed network
  lib/pf/constants/trigger.pm
  lib/pf/dhcp/processor_v4.pm
Labels: Status: For review, Type: Feature / Enhancement

#4906 [packer] support docker multi-tags
  ci/packer/Makefile
  ci/packer/pfbuild.json
  config.mk
Labels: Status: For review

#4907 [packer] push each tag to registry if several
  ci/packer/Makefile
  ci/packer/pfbuild.json
Labels: Status: For review

#4911 [ci] build, sign and upload maintenance artifacts for next release
  .gitlab-ci.yml
  ci/lib/maintenance/build_and_sign_maintenance_artifacts.sh
  ci/lib/upload/deploy-artifacts.sh
Labels: Status: Not ready

#4915 [ci] deploy packetfence-release rpm with a fixed name
  .gitlab-ci.yml
  addons/ZEN-vagrant-builder/installer/install-pf.sh
  ci/lib/upload/deploy-artifacts.sh
  docs/PacketFence_Installation_Guide.asciidoc
  docs/pki/packetfence.asciidoc
Labels: Status: For review

#4929 Realm match default
  lib/pf/config/util.pm
Labels: Priority: Medium, Status: For review, Type: Bug

#4943 Start packetfence-config service early to handle 9.2 upgrade
  rpm/packetfence.spec
Labels: Status: For review

#4947 Reorganize UPGRADE.asciidoc
  .gitignore
  UPGRADE.asciidoc
  docs/PacketFence_Clustering_Guide.asciidoc
  docs/PacketFence_Installation_Guide.asciidoc
  docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
  docs/PacketFence_Upgrade_Guide-docinfo.xml
  docs/PacketFence_Upgrade_Guide.asciidoc
  docs/upgrade-notes/archived_upgrade_notes.asciidoc
Labels: Status: For review

#4558 fix/allowed_options
  go/api-frontend/aaa/authorization.go
  go/api-frontend/aaa/authorization_test.go
  html/pfappserver/lib/pfappserver/Base/Form/Authentication/Action.pm
  html/pfappserver/lib/pfappserver/Base/Form/Role/AllowedOptions.pm
  html/pfappserver/lib/pfappserver/Form/Config/AdminRoles.pm
  html/pfappserver/root/static.alt/src/components/pfCSVImport.vue
  html/pfappserver/root/static.alt/src/components/pfFieldTypeValue.vue
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfiguration.js
  html/pfappserver/root/static.alt/src/globals/configuration/pfConfigurationAccessDuration.js
  html/pfappserver/root/static.alt/src/globals/pfField.js
  html/pfappserver/root/static.alt/src/globals/pfValidators.js
  html/pfappserver/root/static.alt/src/store/modules/config.js
  html/pfappserver/root/static.alt/src/store/modules/session.js
  html/pfappserver/root/static.alt/src/utils/duration.js
  html/pfappserver/root/static.alt/src/views/Configuration/_components/AccessDurationView.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodeView.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesCreate.vue
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesImport.vue
  html/pfappserver/root/static.alt/src/views/Users/_components/UserView.vue
  html/pfappserver/root/static.alt/src/views/Users/_components/UsersCreate.vue
  html/pfappserver/root/static.alt/src/views/Users/_components/UsersImport.vue
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Crud.pm
  lib/pf/UnifiedApi/Controller/CurrentUser.pm
  lib/pf/UnifiedApi/Controller/Nodes.pm
  lib/pf/UnifiedApi/Controller/Users/Password.pm
  lib/pf/admin_roles.pm
  lib/pf/nodecategory.pm
  t/unittest/admin_roles.t
Labels: Status: Not ready

#4949 Fix/saml metadata
  html/pfappserver/root/static.alt/src/views/Configuration/_api/index.js
  html/pfappserver/root/static.alt/src/views/Configuration/_components/AuthenticationSourceView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_store/sources.js
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config/Sources.pm
Labels: API, Priority: Medium, Status: For review, Type: Feature / Enhancement
