Repository inverse-inc/packetfence, pull requests merged in 2019-09, with the labels that each got.

#4772 Fix for radius logic
  lib/pf/Switch.pm
  lib/pf/radius.pm
Labels: Status: For review, Type: Bug

#4783 Install images with all subdirectories
  Makefile
  addons/packages/packetfence.spec
  debian/rules
Labels: Status: For review

#4561 fix/4554
  html/pfappserver/lib/pfappserver/Form/Config/Domain.pm
Labels: Type: Bug

#4627 Pfappserver Network Visualization
  html/pfappserver/root/static.alt/README.md
  html/pfappserver/root/static.alt/package-lock.json
  html/pfappserver/root/static.alt/src/components/pfNetworkGraph.vue
  html/pfappserver/root/static.alt/src/components/pfNetworkGraphTooltipNode.vue
  html/pfappserver/root/static.alt/src/components/pfNetworkGraphTooltipPacketfence.vue
  html/pfappserver/root/static.alt/src/components/pfNetworkGraphTooltipSwitch.vue
  html/pfappserver/root/static.alt/src/store/index.js
  html/pfappserver/root/static.alt/src/views/Status/_components/Network.vue
  html/pfappserver/root/static.alt/src/views/Status/_router/index.js
  html/pfappserver/root/static.alt/src/views/Status/index.vue
  lib/pf/SwitchFactory.pm
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Nodes.pm
  lib/pf/UnifiedApi/Search/Builder.pm
  lib/pf/UnifiedApi/Search/Builder/NodesNetworkGraph.pm
Labels: Priority: Low, Status: In progress, Status: Not ready
