Repository inverse-inc/packetfence, pull requests merged in 2019-01, with the labels that each got.

#3908 fix: cell should span 4 columns
  html/pfappserver/root/config/profile/index.tt
Labels: Status: For review

#3903 fix/i18n_translation_utf8
  addons/upgrade/to-8.3-conf-latin1-to-utf8.sh
  html/captive-portal/lib/captiveportal.pm
  html/pfappserver/lib/pfappserver.pm
  lib/pf/config/util.pm
  lib/pf/web.pm
Labels: Type: Bug

#3912 Update I18N default file with extract_i18n_strings.pl
  html/pfappserver/lib/pfappserver/I18N/en.po
Labels: Status: For review

#3931 Fix logic in sdnotify code to allow more retry before restart.
  go/dhcp/main.go
Labels: Status: For review, Type: Bug

#3933 adjust the unifi web-auth authorize to use the unreg date as timeout
  lib/pf/Switch/Ubiquiti/Unifi.pm
Labels: Status: For review

#3946 Feature/improve apache filters
  conf/apache_filters.conf.defaults
  conf/apache_filters.conf.example
  lib/pf/file_paths.pm
  lib/pfconfig/namespaces/config/ApacheFilters.pm
Labels: Status: For review
