Repository inverse-inc/packetfence, pull requests merged in 2020-04, with the labels that each got.

#5192 Converting switch modules to default switch template
  conf/template_switches.conf.defaults
  lib/pf/Switch/AeroHIVE/Access_Point.def
  lib/pf/Switch/Aruba/WirelessController.def
  lib/pf/Switch/Cisco/Switch.def
  lib/pf/Switch/HP/Switch.def
  lib/pf/Switch/Hostapd_template.def
  lib/pf/Switch/Juniper/Mist.def
  lib/pf/Switch/Ruckus/SmartZone_v2.def
  lib/pf/Switch/Ruckus/ZoneDirector.def
Labels: Status: In progress, Type: Feature / Enhancement

#5045 Unreg on accounting stop only if autoregister enabled
  lib/pf/Connection/Profile.pm
  lib/pf/api.pm
Labels: Status: For review, Type: Feature / Enhancement

#4948 Added a new trigger on node maintenance task
  lib/pf/constants/trigger.pm
  lib/pf/node.pm
Labels: Status: For review, Type: Feature / Enhancement

#5276 Feature/tacking config manager
  conf/documentation.conf
  conf/pf.conf.defaults
  lib/pf/cmd/pf/service.pm
  lib/pf/services/manager.pm
  lib/pf/services/manager/pf.pm
  lib/pf/services/manager/tracking.pm
Labels: Priority: High, Status: For review, Type: Feature / Enhancement

#5271 fix/5267-pfacct-statsd
  go/acct/net_flow.go
  go/acct/pfacct.go
  go/acct/radius.go
  go/tryableonce/once.go
  go/tryableonce/once_test.go
  html/pfappserver/root/static.alt/src/views/Status/_components/Dashboard.vue
Labels: Type: Bug

#5278 use shorter VM name for PacketFence ZEN
  addons/ZEN-vagrant-builder/installer/install-pf.sh
Labels: Status: For review

#5316 Test Fix permissions + Checkup
  t/venom/pfservers/04_run_pfcmd_commands/10_run_fix_permissions.yml
  t/venom/pfservers/04_run_pfcmd_commands/20_run_perform_checkup.yml
Labels: Type: Feature / Enhancement

#5336 allow to use existing ip4log entries in web-auth
  conf/documentation.conf
  conf/pf.conf.defaults
  html/pfappserver/root/static.alt/src/views/Configuration/_config/advanced.js
  lib/pf/web/externalportal.pm
Labels: Priority: Medium

#5221 Doc/wmi example
  conf/security_events.conf.defaults
  conf/wmi.conf.example
Labels: Type: Feature / Enhancement

#5371 Fixes #5351
  conf/passthrough_admin.lua.tt.example
  go/httpdportalpreview/httpdportalpreview.go
  go/unifiedapiclient/client.go
Labels: Priority: High, Status: For review, Type: Bug

#5382 Venom: improvements and changes
  addons/vagrant/inventory/hosts
  addons/vagrant/mailhog.yml
  addons/vagrant/requirements.yml
  addons/vagrant/site.yml
  t/venom/Makefile
  t/venom/examples/scenario/TESTSUITE.md
  t/venom/nodes/10_dot1x_eap_peap/01_wpasupplicant.yml
  t/venom/nodes/dot1x_eap_peap/run_wpasupplicant.yml
  t/venom/pfservers/07_create_sources/00_create_and_test_ad_sources.yml
  t/venom/pfservers/common/fix_permissions.yml
  t/venom/pfservers/common/perform_checkup.yml
  t/venom/pfservers/common/restart_radius_services.yml
  t/venom/pfservers/dot1x_eap_peap/00_join_domain.yml
  t/venom/pfservers/dot1x_eap_peap/05_create_realms.yml
  t/venom/pfservers/dot1x_eap_peap/10_restart_radius_services.yml
  t/venom/pfservers/dot1x_eap_peap/15_create_and_test_ad_machine_source.yml
  t/venom/pfservers/dot1x_eap_peap/20_create_and_test_ad_user_source.yml
  t/venom/pfservers/dot1x_eap_peap/25_create_connection_profile.yml
  t/venom/pfservers/dot1x_eap_peap/30_perform_checkup.yml
  t/venom/pfservers/dot1x_eap_peap/35_run_wpasupplicant.yml
  t/venom/pfservers/dot1x_eap_peap/TESTSUITE.md
  t/venom/pfservers/dot1x_eap_peap/teardown/00_teardown.yml
  t/venom/pfservers/dot1x_eap_peap/teardown/05_restart_radius_services.yml
  t/venom/pfservers/global_config/00_create_roles.yml
  t/venom/pfservers/global_config/05_modify_access_durations.yml
  t/venom/pfservers/global_config/10_create_access_levels.yml
  t/venom/pfservers/global_config/15_create_network_devices.yml
  t/venom/pfservers/global_teardown/00_teardown.yml
  t/venom/setup/00_setup.yml
  t/venom/vars/all.yml
  t/venom/venom-wrapper.sh
Labels: Status: For review

#5369 CI: deploy RPM an Deb packages to dedicated repository (branches)
  .gitlab-ci.yml
  addons/vagrant/extra_vars_branches.yml
  addons/vagrant/inventory/group_vars/dev/packetfence_install.yml
  addons/vagrant/inventory/group_vars/nightly/packetfence_install.yml
  addons/vagrant/requirements.yml
  rpm/packetfence-release/packetfence-release.spec
Labels: Status: For review
