Repository inverse-inc/packetfence, pull requests merged in 2020-03, with the labels that each got.

#5121 feature/remove_currently_at
  Makefile
  addons/dev-helpers/setup-dev-env.sh
  conf/documentation.conf
  conf/pf.conf.defaults
  docs/PacketFence_Clustering_Guide.asciidoc
  docs/PacketFence_Installation_Guide.asciidoc
  html/pfappserver/lib/pfappserver/Model/Configurator.pm
  html/pfappserver/lib/pfappserver/PacketFence/Controller/Configurator.pm
  html/pfappserver/lib/pfappserver/PacketFence/Controller/Root.pm
  html/pfappserver/root/static.alt/src/views/Configuration/_config/advanced.js
Labels: Status: For review, Type: Feature / Enhancement

#5088 fix/5075
  html/pfappserver/lib/pfappserver/Model/Node.pm
  lib/pf/UnifiedApi/Controller/Crud.pm
  lib/pf/UnifiedApi/Controller/Nodes.pm
  lib/pf/cmd/pf/node.pm
  lib/pf/node.pm
  t/unittest/node.t
Labels: Status: For review, Type: Bug

#5163 [docs] several improvements
  conf/wmi.conf.example
  docs/PacketFence_Clustering_Guide.asciidoc
  docs/PacketFence_Developers_Guide.asciidoc
  docs/PacketFence_Installation_Guide.asciidoc
  docs/developer/template_switches.asciidoc
Labels: Status: For review

#5177 Allow vlan greater than 1023
  lib/pf/Switch/Cisco/Catalyst_2950.pm
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#5185 add improved check for the httpd.portal process
  addons/monit/check-httpd.portal.sh
  addons/monit/monit_checks_configurations/00_packetfence.tt
Labels: Status: For review

#5016 Add radius disconnect for wired port on Aruba AP
  lib/pf/Switch/Aruba.pm
Labels: Type: Feature / Enhancement

#5170 PacketFence PKI documentation
  docs/images/packetfence-pki-ca_created.png
  docs/images/packetfence-pki-ca_creation.png
  docs/images/packetfence-pki-ca_menu.png
  docs/images/packetfence-pki-certificate_creation.png
  docs/images/packetfence-pki-certificate_download.png
  docs/images/packetfence-pki-certificate_menu.png
  docs/images/packetfence-pki-client-profile.png
  docs/images/packetfence-pki-eaptls-example.png
  docs/images/packetfence-pki-eaptls-sign-example.png
  docs/images/packetfence-pki-ios-provisioner.png
  docs/images/packetfence-pki-myca.png
  docs/images/packetfence-pki-myca2.png
  docs/images/packetfence-pki-pki-provider_creation.png
  docs/images/packetfence-pki-pki-provider_menu.png
  docs/images/packetfence-pki-provider.png
  docs/images/packetfence-pki-provider2.png
  docs/images/packetfence-pki-rest-api.png
  docs/images/packetfence-pki-revoked_certificate.png
  docs/images/packetfence-pki-server-profile.png
  docs/images/packetfence-pki-template_creation.png
  docs/images/packetfence-pki-template_menu.png
  docs/images/packetfence-pki-template_password_email.png
  docs/pki/packetfence.asciidoc
Labels: Documentation, Status: For review

#5155 Feature/fingerbank nba
  .gitignore
  conf/network_behavior_policies.conf.example
  conf/security_events.conf.defaults
  debian/control
  html/pfappserver/lib/pfappserver/Form/Config/NetworkBehaviorPolicy.pm
  html/pfappserver/lib/pfappserver/Form/Field/Duration.pm
  html/pfappserver/lib/pfappserver/Form/Field/NetworkBehaviorPolicyAttributeWeight.pm
  html/pfappserver/root/static.alt/package-lock.json
  html/pfappserver/root/static.alt/src/globals/pfValidators.js
  html/pfappserver/root/static.alt/src/store/modules/config.js
  html/pfappserver/root/static.alt/src/views/Configuration/_api/index.js
  html/pfappserver/root/static.alt/src/views/Configuration/_components/NetworkBehaviorPoliciesList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/NetworkBehaviorPolicyView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_config/adminRole.js
  html/pfappserver/root/static.alt/src/views/Configuration/_config/fingerbank/index.js
  html/pfappserver/root/static.alt/src/views/Configuration/_config/index.js
  html/pfappserver/root/static.alt/src/views/Configuration/_config/networkBehaviorPolicy.js
  html/pfappserver/root/static.alt/src/views/Configuration/_config/securityEvent.js
  html/pfappserver/root/static.alt/src/views/Configuration/_router/index.js
  html/pfappserver/root/static.alt/src/views/Configuration/_store/fingerbank.js
  html/pfappserver/root/static.alt/src/views/Configuration/_store/networkBehaviorPolicies.js
  html/pfappserver/root/static.alt/src/views/Configuration/index.vue
  lib/pf/ConfigStore/NetworkBehaviorPolicy.pm
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config/NetworkBehaviorPolicies.pm
  lib/pf/UnifiedApi/Controller/Fingerbank.pm
  lib/pf/api.pm
  lib/pf/constants/trigger.pm
  lib/pf/file_paths.pm
  rpm/packetfence.spec
Labels: Status: For review

#5169 mysql dhcp pool backend
  db/pf-schema-X.Y.Z.sql
  db/upgrade-X.X.X-X.Y.Z.sql
  go/dhcp/config.go
  go/dhcp/main.go
  go/dhcp/pool/memory.go
  go/dhcp/pool/mysql.go
  go/dhcp/pool/pool.go
  go/dhcp/pool/pool_test.go
  go/dhcp/server.go
  go/dhcp/utils.go
  go/dhcp/workers_pool.go
  go/pfconfigdriver/structs.go
  go/sharedutils/ping.go
  go/sharedutils/pingraw.go
  html/pfappserver/lib/pfappserver/Form/Config/Network.pm
  html/pfappserver/root/static.alt/src/views/Configuration/_config/layer2Network.js
  html/pfappserver/root/static.alt/src/views/Configuration/_config/routedNetwork.js
  lib/pf/constants/dhcp.pm
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#5191 Feature/cisco ise pic
  docs/PacketFence_Installation_Guide.asciidoc
  docs/firewall/ciscoisepic.asciidoc
  docs/images/doc-ise-pic-pf-configuration.png
  docs/images/doc-ise-pic-syslog-header.png
  docs/images/doc-ise-pic-syslog-provider.png
  docs/images/doc-ise-pic-syslog-template.png
  go/firewallsso/ciscoisepic.go
  go/firewallsso/factory.go
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/CiscoIsePic.pm
  html/pfappserver/root/static.alt/src/views/Configuration/_components/FirewallsList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_config/firewall.js
  lib/pf/UnifiedApi/Controller/Config/Firewalls.pm
  lib/pf/constants/firewallsso.pm
Labels: Status: For review

#5198 [pkg] don't start packetfence-httpd.admin at end of install in CI env
  debian/packetfence.postinst
  rpm/packetfence.spec
Labels: Status: For review

#5206 Fix/honor timezone on the os
  lib/pfconfig/namespaces/config/Pf.pm
  packetfence.sudoers
Labels: Status: For review

#5236 Disable secure redirect on self signed certificate
  lib/pfconfig/namespaces/config/Pf.pm
Labels: Priority: High, Status: For review, Status: Tested and works, Type: Bug

#5245 Force stop if the service is disabled, test if pfacct is disable in radius-acct manager
  lib/pf/cmd/pf/service.pm
  lib/pf/services/manager/radiusd.pm
Labels: Priority: High, Type: Bug

#5004 fix/pfsnmp_queue_distribute
  conf/pfqueue.conf.defaults
  lib/pf/constants/pfqueue.pm
  lib/pf/pfqueue/producer/redis.pm
  lib/pf/services/manager/snmptrapd.pm
  lib/pf/snmptrapd.pm
  lib/pf/task/pfsnmp.pm
  lib/pf/task/pfsnmp_parsing.pm
  lib/pfconfig/namespaces/config/Pfqueue.pm
  sbin/pfqueue
Labels: Priority: High, Type: Bug
