Repository inverse-inc/packetfence, pull requests merged in 2020-02, with the labels that each got.

#5128 Added generateConfig function to iptables service
  lib/pf/services/manager/iptables.pm
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#5086 Feature/change captive portal detection
  Makefile
  addons/update-samsung-dns-filter.sh
  conf/dns_filters.conf.defaults
  conf/keepalived.conf.example
  conf/passthrough.lua.tt.example
  conf/pf.conf.defaults
  conf/systemd/packetfence-haproxy-portal.service
  conf/systemd/packetfence-keepalived.service
  debian/patches/debianize.patch
  go/coredns/plugin/pfdns/pfdns.go
  go/httpdispatcher/proxy.go
  lib/pf/cluster.pm
  lib/pf/iptables.pm
  lib/pf/services/manager/haproxy_portal.pm
  lib/pf/services/manager/keepalived.pm
  rpm/packetfence.spec
Labels: Priority: High, Status: For review, Type: Feature / Enhancement

#5092 keepalived manage routes
  conf/documentation.conf
  conf/pf.conf.defaults
  conf/systemd/packetfence-routes.service
  debian/packetfence.postinst
  debian/rules
  lib/pf/cmd/pf/service.pm
  lib/pf/services/manager/keepalived.pm
  lib/pf/services/manager/routes.pm
  rpm/packetfence.spec
Labels: Status: For tracking, Type: Feature / Enhancement

#5159 Add CLI login to juniper switches
  docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
  lib/pf/Switch/Juniper.pm
Labels: Type: Feature / Enhancement

#5009 security_events: split example and defaults in correct files
  conf/security_events.conf.defaults
  conf/security_events.conf.example
Labels: Status: For review

#5172 Ensure sponsor field is updated when using forced_sponsor
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Sponsor.pm
Labels: Status: For review

#5154 Fix for 5106
  conf/chi.conf.defaults
  lib/pf/CHI.pm
  lib/pf/dhcp/processor_v4.pm
  lib/pf/fingerbank.pm
Labels: Priority: High, Status: For review, Type: Bug

#4967 Added a way to define a custom pfconfig table in the db
  conf/pfconfig.conf.example
  lib/pfconfig/backend/mysql.pm
Labels: Priority: Low, Status: For review, Type: Feature / Enhancement

#5104 New switch template for Aruba switches
  conf/template_switches.conf.defaults
  lib/pf/Switch/Aruba/ArubaSwitchNG.def
Labels: Status: For review

#5148 Vagrant: add an Active Directory server in environment
  addons/vagrant/Vagrantfile
  addons/vagrant/inventory/group_vars/all/common.yml
  addons/vagrant/inventory/group_vars/stable_and_nightly/packetfence_install__api_calls.yml
  addons/vagrant/inventory/group_vars/winservers/ansible.yml
  addons/vagrant/inventory/group_vars/winservers/domain_account.yml
  addons/vagrant/inventory/group_vars/winservers/domain_setup.yml
  addons/vagrant/inventory/hosts
  addons/vagrant/requirements.yml
  addons/vagrant/site.yml
  addons/vagrant/winservers.yml
  docs/PacketFence_Developers_Guide.asciidoc
Labels: Status: For review

#5158 Feature/galera autofix
  addons/packages/build-go.sh
  conf/documentation.conf
  conf/iptables.conf.example
  conf/pf.conf.defaults
  conf/systemd/packetfence-galera-autofix.service
  conf/systemd/packetfence-mariadb.service
  config.mk
  debian/rules
  docs/PacketFence_Clustering_Guide.asciidoc
  go/Makefile
  go/db/db.go
  go/galeraautofix/chitchat.go
  go/galeraautofix/main.go
  go/galeraautofix/mariadb/mariadb.go
  go/galeraautofix/nodes.go
  go/go.mod
  go/go.sum
  go/go.sy
  go/pfconfigdriver/structs.go
  html/pfappserver/root/static.alt/src/views/Configuration/_config/service.js
  lib/pf/cmd/pf/service.pm
  lib/pf/services/manager/galera_autofix.pm
  rpm/packetfence.spec
  sbin/pf-mariadb
Labels: Status: For review
