Repository inverse-inc/packetfence, pull requests merged in 2020-09, with the labels that each got.

#5642 Feature/sponsor register on activation
  db/pf-schema-X.Y.Z.sql
  db/upgrade-X.X.X-X.Y.Z.sql
  html/captive-portal/lib/captiveportal/PacketFence/Controller/Activate/Email.pm
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Sponsor.pm
  html/captive-portal/templates/waiting.html
  html/pfappserver/lib/pfappserver/Form/Config/Source/SponsorEmail.pm
  html/pfappserver/root/static.alt/src/views/Configuration/_config/authenticationSource.js
  lib/pf/Authentication/Source/SponsorEmailSource.pm
  lib/pf/activation.pm
  lib/pf/dal/_activation.pm
Labels: Status: For review

#5753 [docs] Minor improvements to documentation
  docs/PacketFence_Clustering_Guide.asciidoc
  docs/PacketFence_Installation_Guide.asciidoc
Labels: Status: For review

#5746 [systemd] 143 is a legit exit code for haproxy
  conf/systemd/packetfence-haproxy-admin.service
  conf/systemd/packetfence-haproxy-db.service
  conf/systemd/packetfence-haproxy-portal.service
Labels: Status: For review

#5784 Support EAP-PEAP and EAP-TLS for CLI and VPN authentication
  lib/pf/radius.pm
Labels: Status: For review

#5701 feature/generalize-makefile
  config.mk
  go/Makefile
  go/cmd/db-tester/main.go
  go/cmd/galera-autofix/chitchat.go
  go/cmd/galera-autofix/main.go
  go/cmd/galera-autofix/nodes.go
  go/cmd/pfacct/bandwidth_account_test.go
  go/cmd/pfacct/bandwidth_accounting.go
  go/cmd/pfacct/dispatcher.go
  go/cmd/pfacct/main.go
  go/cmd/pfacct/net_flow.go
  go/cmd/pfacct/net_flow_test.go
  go/cmd/pfacct/nodes.go
  go/cmd/pfacct/nodes_test.go
  go/cmd/pfacct/pfacct.go
  go/cmd/pfacct/radius.go
  go/cmd/pfacct/radius_test.go
  go/cmd/pfcertmanager/main.go
  go/cmd/pfcertmanager/mem.go
  go/cmd/pfdetect/main.go
  go/cmd/pfdhcp/api.go
  go/cmd/pfdhcp/config.go
  go/cmd/pfdhcp/dictionary.go
  go/cmd/pfdhcp/keysoption.go
  go/cmd/pfdhcp/main.go
  go/cmd/pfdhcp/rawClient.go
  go/cmd/pfdhcp/server.go
  go/cmd/pfdhcp/serverif.go
  go/cmd/pfdhcp/utils.go
  go/cmd/pfdhcp/workers_pool.go
  go/cmd/pfdns/coredns.go
  go/cmd/pfdns/directives_generate.go
  go/cmd/pfhttpd/main.go
  go/cmd/pfstats/main.go
  go/cmd/pfstats/metrics.go
  go/cmd/radius-tester/main.go
Labels: Status: For review, Type: Feature / Enhancement

#5740 feature/mandatory-field-email-templates
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Email.pm
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Sponsor.pm
Labels: Status: For review, Type: Feature / Enhancement

#5735 feature/switch-template-bounce
  docs/developer/template_switches.asciidoc
  html/pfappserver/root/static.alt/src/views/Configuration/_config/switchTemplate.js
  lib/pf/Switch.pm
  lib/pf/Switch/MockedSwitch.pm
  lib/pf/Switch/Template.pm
  lib/pf/constants/template_switch.pm
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#5742 feature/default-switch-packetfence-standard
  addons/upgrade/to-10.2-default-switch-packetfence-standard.pl
  conf/switches.conf.defaults
  conf/template_switches.conf.defaults
  lib/pf/Switch/PacketFence/SNMP.def
Labels: Status: For review, Type: Feature / Enhancement

#5708 feature/switch-template-cli-access
  html/pfappserver/root/static.alt/src/views/Configuration/_config/switchTemplate.js
  lib/pf/Switch.pm
  lib/pf/Switch/Template.pm
  lib/pf/constants/template_switch.pm
  lib/pf/radius.pm
Labels: Status: For review, Status: Tested and works, Type: Feature / Enhancement

#5759 Dell N1500: use common regex to get MAC from LLDP
  lib/pf/Switch/Dell/N1500.pm
Labels: Priority: Medium, Status: For review

#5801 Use Status Check to test radius sources
  go/cmd/pfstats/main.go
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#5717 Fix/netflow adjustements
  NEWS.asciidoc
  conf/documentation.conf
  conf/pf.conf.defaults
  docs/PacketFence_Installation_Guide.asciidoc
Labels: Status: For review

#5779 feature/switch-template-nasport2index
  html/pfappserver/lib/pfappserver/Form/Config/TemplateSwitch.pm
  html/pfappserver/root/static.alt/src/views/Configuration/_config/switchTemplate.js
  lib/pf/Switch/Template.pm
  lib/pf/config/builder/template_switches.pm
  t/data/switches.conf
  t/data/template_switches.conf
  t/test_paths.pm
  t/unittest/Switch/Template.t
Labels: Status: For review, Type: Feature / Enhancement

#5726 feature/syslog-parser-tenant-aware
  .gitignore
  addons/upgrade/to-10.2-pfdetect-conf.pl
  go/detectparser/dhcp.go
  go/detectparser/dhcp_test.go
  go/detectparser/fortianalyser.go
  go/detectparser/fortianalyser_test.go
  go/detectparser/generic.go
  go/detectparser/generic_test.go
  go/detectparser/nexpose.go
  go/detectparser/nexpose_test.go
  go/detectparser/parser.go
  go/detectparser/security_onion.go
  go/detectparser/security_onion_test.go
  go/detectparser/snort.go
  go/detectparser/snort_test.go
  go/detectparser/suricata_md5.go
  go/detectparser/suricata_md5_test.go
  go/pfqueueclient/pfqueueclient.go
  html/pfappserver/lib/pfappserver/Form/Config/Pfdetect.pm
  html/pfappserver/root/static.alt/src/views/Configuration/_config/syslogParser.js
  lib/pf/detect/parser/regex.pm
Labels: Status: For review, Type: Feature / Enhancement

#5725 fix/2845
  html/pfappserver/lib/pfappserver/Model/Config/System.pm
Labels: Status: For review, Type: Bug

#5802 Create a new entry in radacct and in radacct_log if the interim update has been received after a stop.
  db/pf-schema-X.Y.Z.sql
  db/upgrade-X.X.X-X.Y.Z.sql
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#5781 Feature/rfc 7710
  conf/passthrough.lua.tt.example
  go/cmd/pfdhcp/api.go
  go/cmd/pfdhcp/config.go
  go/cmd/pfdhcp/dictionary.go
  go/cmd/pfdhcp/main.go
  go/cmd/pfdhcp/server.go
  go/cmd/pfdhcp/utils.go
  go/cmd/pfdhcp/workers_pool.go
  go/go.mod
  go/go.sum
  go/go.sy
  go/httpdispatcher/proxy.go
Labels: Status: For review, Type: Feature / Enhancement

#5800 Add default MAC Address randomization security event check
  conf/security_events.conf.defaults
  html/captive-portal/content/images/android-mac-address-randomization.png
  html/captive-portal/content/images/ios-mac-address-randomization.jpg
  html/captive-portal/content/images/windows-mac-address-randomization.jpg
  html/captive-portal/templates/security_events/random_mac.html
Labels: Status: For review, Status: Tested and works, Type: Feature / Enhancement

#5724 feature/node-delete
  html/pfappserver/root/static.alt/src/utils/api.js
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesSearch.vue
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Nodes.pm
  lib/pf/dal/node.pm
  lib/pf/enforcement.pm
  lib/pf/node.pm
  t/unittest/UnifiedApi/Controller/Nodes.t
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#5806 Exclude the ip address of a disabled server
  go/cmd/pfdhcp/utils.go
  go/pfconfigdriver/structs.go
Labels: Priority: High, Status: For review, Type: Bug

#5734 feature/roles-delete
  db/pf-schema-X.Y.Z.sql
  db/upgrade-X.X.X-X.Y.Z.sql
  html/pfappserver/root/static.alt/src/views/Configuration/_api/index.js
  html/pfappserver/root/static.alt/src/views/Configuration/_components/RoleView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/RolesList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_config/role.js
  html/pfappserver/root/static.alt/src/views/Configuration/_store/roles.js
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config.pm
  lib/pf/UnifiedApi/Controller/Config/Roles.pm
  lib/pf/dal.pm
  lib/pf/nodecategory.pm
  lib/pf/scan.pm
  lib/pfconfig/namespaces/config.pm
  lib/pfconfig/namespaces/config/AdminRoles.pm
  lib/pfconfig/namespaces/config/Authentication.pm
  lib/pfconfig/namespaces/config/BillingTiers.pm
  lib/pfconfig/namespaces/config/Firewall_SSO.pm
  lib/pfconfig/namespaces/config/PortalModules.pm
  lib/pfconfig/namespaces/config/Profiles.pm
  lib/pfconfig/namespaces/config/Provisioning.pm
  lib/pfconfig/namespaces/config/Scan.pm
  lib/pfconfig/namespaces/config/SecurityEvents.pm
  lib/pfconfig/namespaces/config/SelfService.pm
  lib/pfconfig/namespaces/config/Switch.pm
  lib/pfconfig/namespaces/config/VlanFilters.pm
  lib/pfconfig/namespaces/resource/RolesReverseLookup.pm
  t/unittest/UnifiedApi/Controller/Config/Provisionings.t
  t/unittest/UnifiedApi/Controller/Config/Roles.t
Labels: Status: For review, Type: Feature / Enhancement

#5616 Master/Slave radius proxy and degraded workflow
  conf/radiusd/auth.conf.example
  conf/radiusd/eap.conf.example
  conf/radiusd/packetfence-cli.example
  conf/radiusd/packetfence-tunnel.example
  conf/radiusd/packetfence.example
  conf/radiusd/sql.conf.example
  db/pf-schema-X.Y.Z.sql
  db/upgrade-X.X.X-X.Y.Z.sql
  lib/pf/api.pm
  lib/pf/api/queue_cluster.pm
  lib/pf/domain/ntlm_cache.pm
  lib/pf/radius.pm
  lib/pf/services/manager/galera_autofix.pm
  lib/pf/services/manager/radiusd_child.pm
  raddb/dictionary.inverse
  raddb/mods-available/perl
  raddb/mods-config/perl/reply_in_db.pm
  raddb/mods-config/sql/main/mysql/reject.conf
  raddb/policy.d/packetfence
Labels: Status: In progress, Type: Feature / Enhancement

#5739 fix/5729
  html/pfappserver/root/static.alt/src/views/Configuration/_components/CertificatesView.vue
  lib/pf/UnifiedApi/Controller/Config/Certificates.pm
  lib/pf/util.pm
Labels: Status: For review, Type: Bug

#5796 Add tenancy to realm configuration
  html/pfappserver/root/static.alt/src/components/pfMixinSearchable.js
  html/pfappserver/root/static.alt/src/globals/pfValidators.js
  html/pfappserver/root/static.alt/src/store/base/searchable.js
  html/pfappserver/root/static.alt/src/store/modules/config.js
  html/pfappserver/root/static.alt/src/utils/api.js
  html/pfappserver/root/static.alt/src/views/Configuration/_api/index.js
  html/pfappserver/root/static.alt/src/views/Configuration/_components/RealmView.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/RealmsList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_config/realm.js
  html/pfappserver/root/static.alt/src/views/Configuration/_router/index.js
  html/pfappserver/root/static.alt/src/views/Configuration/_store/realms.js
  lib/pf/UnifiedApi/Controller/Config.pm
Labels: Priority: High

#5822 Fix/5821 bis
  go/cmd/pfacct/radius.go
  go/pfconfigdriver/structs.go
Labels: Priority: High, Status: For review, Type: Bug
