Repository inverse-inc/packetfence, pull requests merged in 2020-10, with the labels that each got.

#5892 local account creation expiration should follow the access validity
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication.pm
Labels: Priority: High, Status: For review

#5898 allow to specify local account expiration in auth source
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication.pm
  html/pfappserver/lib/pfappserver/Base/Form/Role/SourceLocalAccount.pm
  html/pfappserver/root/static.alt/src/views/Configuration/_config/authenticationSource.js
  lib/pf/Authentication/CreateLocalAccountRole.pm
Labels: Status: For review

#5911 Feature/pfacct behind radiusd acct
  conf/radiusd/packetfence.example
  conf/radiusd/proxy.conf.inc.example
  go/cmd/pfacct/radius.go
  go/pfconfigdriver/structs.go
  lib/pf/services/manager/radiusd.pm
  lib/pf/services/manager/radiusd_child.pm
Labels: Status: For review

#5916 Feature/extreme aerohive module improvements
  lib/pf/Switch/AeroHIVE.pm
  lib/pf/Switch/Extreme.pm
Labels: Status: For review

#5903 feature/alt-ssid-attribute
  lib/pf/Switch.pm
  t/unittest/Switch.t
Labels: Status: For review, Type: Feature / Enhancement

#5931 [Venom] Venom install script upgrade
  t/venom/install-venom.sh
Labels: Status: For review
