Repository inverse-inc/packetfence, pull requests merged in 2020-01, with the labels that each got.

#5052 [docs] minor improvements
  Makefile
  UPGRADE.asciidoc
  docs/PacketFence_Clustering_Guide.asciidoc
  docs/PacketFence_Developers_Guide.asciidoc
  docs/PacketFence_Installation_Guide.asciidoc
  docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
  docs/PacketFence_Template_Guide.asciidoc
Labels: Status: For review

#5062 [docs] Remove duplicated instructions for PacketFence cluster upgrade
  UPGRADE.asciidoc
  docs/PacketFence_Clustering_Guide.asciidoc
Labels: Status: For review

#5069 Fixed Avaya portsec when a device move to another port.
  lib/pf/Switch/Avaya.pm
Labels: Priority: Medium, Status: For review, Type: Bug, Type: Feature / Enhancement

#5007 Update path to route binary
  lib/pf/services/manager/routes.pm
Labels: Priority: Medium, Status: For review

#5077 Feature/meru mc v2
  conf/template_switches.conf.defaults
  lib/pf/Switch/Meru/MC_v2.def
Labels: Status: For review

#5083 Unifi: improve deauthentication using HTTP
  lib/pf/Switch/Ubiquiti/Unifi.pm
Labels: Status: For review

#5015 [CI] Docker images to build EL8 and Debian 10 packages
  .gitlab-ci.yml
  ci/packer/Makefile
  ci/packer/pfbuild.json
  ci/packer/provisionners/inventory/group_vars/devel_centos/gitlab_buildpkg_tools.yml
  ci/packer/provisionners/inventory/group_vars/devel_centos/rpm_keys.yml
  ci/packer/provisionners/inventory/group_vars/devel_centos7/gitlab_buildpkg_tools.yml
  ci/packer/provisionners/inventory/group_vars/devel_centos8/gitlab_buildpkg_tools.yml
  ci/packer/provisionners/inventory/group_vars/devel_debian/gitlab_buildpkg_tools.yml
  ci/packer/provisionners/inventory/group_vars/devel_rubygems/rubygems.yml
  ci/packer/provisionners/inventory/group_vars/stable_centos/gitlab_buildpkg_tools.yml
  ci/packer/provisionners/inventory/group_vars/stable_centos/rpm_keys.yml
  ci/packer/provisionners/inventory/group_vars/stable_centos7/gitlab_buildpkg_tools.yml
  ci/packer/provisionners/inventory/group_vars/stable_centos8/gitlab_buildpkg_tools.yml
  ci/packer/provisionners/inventory/group_vars/stable_debian/gitlab_buildpkg_tools.yml
  ci/packer/provisionners/inventory/group_vars/stable_rubygems/rubygems.yml
  ci/packer/provisionners/playbooks/python3.yml
  ci/packer/provisionners/playbooks/rubygems.yml
  ci/packer/provisionners/shell/install-nodejs-el8.sh
  ci/packer/provisionners/site.yml
  ci/packer/provisionners/upstream/rpm_keys/nodesource.rpm.key
  config.mk
  debian/control
  rpm/packetfence.spec
Labels: Status: For review

#4951 Lower ttl to 5 seconds if the fqdn match with a captive portal detection host
  go/coredns/plugin/pfdns/pfdns.go
Labels: Priority: Low, Status: For review, Type: Feature / Enhancement

#5095 Enable tracking services
  debian/packetfence.postinst
  rpm/packetfence.spec
Labels: Status: For review, Type: Feature / Enhancement, Type: Nice to have
