Repository inverse-inc/packetfence, pull requests merged in 2020-06, with the labels that each got.

#5034 Admin - Switch Import
  html/pfappserver/root/static.alt/src/components/pfButtonExportToCsv.vue
  html/pfappserver/root/static.alt/src/components/pfConfigList.vue
  html/pfappserver/root/static.alt/src/globals/pfValidators.js
  html/pfappserver/root/static.alt/src/styles/_nav.scss
  html/pfappserver/root/static.alt/src/views/Configuration/_api/index.js
  html/pfappserver/root/static.alt/src/views/Configuration/_components/SwitchesImport.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_components/SwitchesList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_config/switch.js
  html/pfappserver/root/static.alt/src/views/Configuration/_router/index.js
  html/pfappserver/root/static.alt/src/views/Configuration/_store/switches.js
  html/pfappserver/root/static.alt/src/views/Nodes/_components/NodesImport.vue
  html/pfappserver/root/static.alt/src/views/Users/_components/UsersImport.vue
Labels: API, Priority: Medium, Status: For review, Type: Feature / Enhancement

#5507 Documentation/eap radius ldap
  conf/radius_filters.conf.defaults
  conf/vlan_filters.conf.defaults
  docs/PacketFence_Installation_Guide.asciidoc
  lib/pf/ConfigStore/RadiusFilters.pm
  lib/pf/file_paths.pm
  lib/pfconfig/namespaces/config/RadiusFilters.pm
  rpm/packetfence.spec
Labels: Documentation, Priority: High, Status: For review

#5474 feature/openid_improvements
  conf/documentation.conf
  conf/pf.conf.defaults
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/OAuth/OpenID.pm
  html/pfappserver/lib/pfappserver/Form/Config/Source/OpenID.pm
  html/pfappserver/lib/pfappserver/Form/Field/PersonMapping.pm
  html/pfappserver/root/static.alt/src/components/pfFieldPersonOpenid.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_config/advanced.js
  html/pfappserver/root/static.alt/src/views/Configuration/_config/authenticationSource.js
  lib/pf/Authentication/Source/OpenIDSource.pm
  lib/pf/Authentication/utils.pm
  lib/pf/ConfigStore/Source.pm
  lib/pfconfig/namespaces/config/Authentication.pm
  t/data/authentication.conf
  t/unittest/authentication.t
Labels: Status: Not ready, Type: Feature / Enhancement

#5581 handle the case when authorizing a guest with a ZERO date
  lib/pf/Switch/Ubiquiti/Unifi.pm
Labels: Status: For review

#5599 Restart rsyslog after new systemd config has been applied
  rpm/packetfence.spec
Labels: Status: In progress

#5606 [ZEN] Install all locales and remove IDE Controller
  ci/packer/zen/files/centos7.ks.cfg
  ci/packer/zen/sources.pkr.hcl
Labels: Status: For review

#5584 [docs] Adjustements to Upgrade and Cluster guide
  UPGRADE.asciidoc
  docs/PacketFence_Clustering_Guide.asciidoc
Labels: Status: For review

#5623 Feature/cisco coa improvement
  lib/pf/Switch.pm
  lib/pf/Switch/Meraki/MR_v2.pm
Labels: Status: For review

#5479 Fix/5476
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/SAML.pm
  html/captive-portal/templates/saml.html
  html/pfappserver/lib/pfappserver/Form/Config/PortalModule/Authentication/SAML.pm
  html/pfappserver/root/static.alt/src/views/Configuration/_config/portalModule.js
Labels: Status: For review
