Repository inverse-inc/packetfence, pull requests merged in 2020-05, with the labels that each got.

#5404 feature/LDAP-not_found_set_role_action
  html/pfappserver/lib/pfappserver/Form/Field/SourceRule.pm
  html/pfappserver/root/static.alt/src/globals/pfActions.js
  html/pfappserver/root/static.alt/src/views/Configuration/_config/authenticationSource.js
  lib/pf/Authentication/Source.pm
  lib/pf/Authentication/Source/AdminProxySource.pm
  lib/pf/Authentication/Source/AuthorizationSource.pm
  lib/pf/Authentication/Source/BillingSource.pm
  lib/pf/Authentication/Source/BlackholeSource.pm
  lib/pf/Authentication/Source/ClickatellSource.pm
  lib/pf/Authentication/Source/EAPTLSSource.pm
  lib/pf/Authentication/Source/EduroamSource.pm
  lib/pf/Authentication/Source/EmailSource.pm
  lib/pf/Authentication/Source/HtpasswdSource.pm
  lib/pf/Authentication/Source/KerberosSource.pm
  lib/pf/Authentication/Source/LDAPSource.pm
  lib/pf/Authentication/Source/NullSource.pm
  lib/pf/Authentication/Source/OAuthSource.pm
  lib/pf/Authentication/Source/PotdSource.pm
  lib/pf/Authentication/Source/RADIUSSource.pm
  lib/pf/Authentication/Source/SMSSource.pm
  lib/pf/Authentication/Source/SponsorEmailSource.pm
  lib/pf/Authentication/Source/TwilioSource.pm
  lib/pf/Authentication/constants.pm
  lib/pf/authentication.pm
  t/data/authentication.conf
  t/ldap-auth-role_not_found.t
Labels: Type: Feature / Enhancement

#5423 Screen packetfence-pki-eaptls-example
  docs/images/packetfence-pki-eaptls-example.png
  docs/images/packetfence-pki-eaptls-sign-example.png
Labels: Documentation

#5422 [CI] build ZEN using packer
  .gitlab-ci.yml
  ci/packer/zen/.gitignore
  ci/packer/zen/Makefile
  ci/packer/zen/README.md
  ci/packer/zen/build-and-upload.sh
  ci/packer/zen/build.pkr.hcl
  ci/packer/zen/files/centos7.ks.cfg
  ci/packer/zen/files/rc.local
  ci/packer/zen/scripts/install-pf.sh
  ci/packer/zen/sources.pkr.hcl
  ci/packer/zen/variables.pkr.hcl
Labels: Status: For review

#5407 feature/advanced_ldap_condition
  html/pfappserver/lib/pfappserver/Form/Field/SourceRuleCondition.pm
  html/pfappserver/root/static.alt/src/globals/pfField.js
  lib/pf/Authentication/Source/LDAPSource.pm
  lib/pf/Authentication/constants.pm
  t/data/authentication.conf
  t/unittest/Authentication/Source/LDAPSource.t
Labels: Status: For tracking, Status: Not ready, Type: Feature / Enhancement

#5438 CI: automatically test package installation at release
  .gitlab-ci.yml
  ci/lib/test/vagrant-wrapper.sh
Labels: Status: For review

#5419 Feature/fingerbank client hints
  html/captive-portal/lib/captiveportal/PacketFence/Controller/Root.pm
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Application.pm
Labels: Status: For review

#5265 Feature/vpn mschap
  conf/radiusd/packetfence.example
  lib/pf/radius.pm
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#5433 add the ability to enable/disable an NBA policy
  conf/network_behavior_policies.conf.example
  html/pfappserver/lib/pfappserver/Form/Config/NetworkBehaviorPolicy.pm
  html/pfappserver/root/static.alt/src/views/Configuration/_config/networkBehaviorPolicy.js
Labels: Status: For review

#5441 Allow multiple access levels in source admin rules
  html/pfappserver/lib/pfappserver/Form/Field/SourceRuleAction.pm
  html/pfappserver/root/static.alt/src/globals/pfField.js
Labels: Priority: Medium, Status: In progress, Status: Not ready, Type: Feature / Enhancement

#5130 Return the portal ip if the fqdn match with one of the portal fqdn
  conf/pfdns.conf.example
  go/coredns/plugin/pfdns/pfdns.go
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#5439 feature/disable-enable-source-rules
  addons/upgrade/to-10.1-rule-status.pl
  conf/authentication.conf.example
  html/pfappserver/lib/pfappserver/Form/Field/SourceRule.pm
  html/pfappserver/root/static.alt/src/components/pfFieldRule.vue
  lib/pfconfig/namespaces/config/Authentication.pm
Labels: Status: For review, Type: Feature / Enhancement

#4968 Feature/dell n1500
  docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
  lib/pf/Switch/Dell/N1500.pm
  lib/pf/web/constants.pm
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#5231 Feature/coa unifi
  conf/pfmon.conf.defaults
  docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
  docs/images/ubiquiti-unifi-guest-policy.png
  docs/images/ubiquiti-unifi-guest-policy_access.png
  docs/images/ubiquiti-unifi-guest-ssid.png
  docs/images/unifi-open.png
  docs/images/unifi-open2.png
  docs/images/unifi-radius.png
  docs/images/unifi-radius2.png
  docs/images/unifi-secure.png
  docs/images/unifi-secure2.png
  lib/pf/Switch/AeroHIVE.pm
  lib/pf/Switch/Aruba.pm
  lib/pf/Switch/Avaya/WC.pm
  lib/pf/Switch/Belair.pm
  lib/pf/Switch/Cambium.pm
  lib/pf/Switch/Cisco/ASA.pm
  lib/pf/Switch/Cisco/Aironet.pm
  lib/pf/Switch/Cisco/Aironet_1600.pm
  lib/pf/Switch/Cisco/Aironet_WDS.pm
  lib/pf/Switch/Cisco/WLC.pm
  lib/pf/Switch/Dlink/DWS_3026.pm
  lib/pf/Switch/Enterasys/V2110.pm
  lib/pf/Switch/Extricom.pm
  lib/pf/Switch/HP/Controller_MSM710.pm
  lib/pf/Switch/HP/MSM.pm
  lib/pf/Switch/Hostapd.pm
  lib/pf/Switch/Huawei.pm
  lib/pf/Switch/Meru.pm
  lib/pf/Switch/Mikrotik.pm
  lib/pf/Switch/MockedSwitch.pm
  lib/pf/Switch/Motorola.pm
  lib/pf/Switch/Ruckus.pm
  lib/pf/Switch/Ruckus/SmartZone.pm
  lib/pf/Switch/Template.pm
  lib/pf/Switch/Trapeze.pm
  lib/pf/Switch/Ubiquiti/Unifi.pm
  lib/pf/Switch/Xirrus.pm
  lib/pf/SwitchFactory.pm
  lib/pf/api.pm
  lib/pf/pfmon/task/ubiquiti_ap_mac_to_ip.pm
  lib/pf/web/externalportal.pm
  t/SwitchFactory.t
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#5393 feature/sflow
  go/go.mod
  go/go.sum
  go/sflow/cmds/tcp_view/tcp_view.go
  go/sflow/counters.go
  go/sflow/countersamples.go
  go/sflow/ethernetifcounter.go
  go/sflow/flowsamples.go
  go/sflow/ifcounter.go
  go/sflow/processor/example_test.go
  go/sflow/processor/processor.go
  go/sflow/sampledflows.go
  go/sflow/sampledheader.go
  go/sflow/sampledipv4_test.go
  go/sflow/sflow.go
  go/sflow/sflow_test.go
  go/sflow/util.go
Labels: Status: For review, Type: Feature / Enhancement

#5465 feature/replace-func
  docs/developer/template_switches.asciidoc
  lib/pf/mini_template.pm
  t/unittest/mini_template.t
Labels: Status: For review, Type: Feature / Enhancement

#5417 Support for regex Realm
  html/pfappserver/lib/pfappserver/Form/Config/Realm.pm
  html/pfappserver/root/static.alt/src/views/Configuration/_api/index.js
  html/pfappserver/root/static.alt/src/views/Configuration/_components/RealmsList.vue
  html/pfappserver/root/static.alt/src/views/Configuration/_config/realm.js
  html/pfappserver/root/static.alt/src/views/Configuration/_store/realms.js
  lib/pf/config.pm
  lib/pf/config/util.pm
  lib/pf/services/manager/radiusd_child.pm
  lib/pfconfig/namespaces/config/OrderedRealm.pm
  raddb/mods-config/perl/packetfence-multi-domain.pm
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#5468 fix pf-maint.pl while running behind a proxy
  addons/pf-maint.pl
Labels: Status: For review

#5459 feature/role_dynamic_role
  lib/pf/Authentication/Source.pm
  lib/pf/Authentication/Source/LDAPSource.pm
  lib/pf/Authentication/Source/RADIUSSource.pm
  lib/pf/Authentication/constants.pm
  lib/pf/authentication.pm
  lib/pf/constants/filters.pm
  lib/pf/radius.pm
  lib/pf/registration.pm
  lib/pf/role.pm
  lib/pf/task/pfsnmp.pm
  lib/pf/web/wispr.pm
  lib/pfconfig/namespaces/config/Authentication.pm
  t/unittest/Authentication/Source-RoleLookup.t
Labels: Priority: High, Status: For review, Type: Feature / Enhancement

#5392 Feature/live log viewer
  conf/caddy-services/api.conf.example
  conf/log.conf.example
  go/caddy/caddy/caddy/caddymain/run.go
  go/caddy/caddy/caddyhttp/httpserver/plugin.go
  go/caddy/log-tailer/handlers.go
  go/caddy/log-tailer/log-tailer.go
  go/caddy/log-tailer/log-tailer_test.go
  go/caddy/log-tailer/logmeta.go
  go/caddy/log-tailer/logmeta_test.go
  go/caddy/log-tailer/tailing_session.go
  go/caddy/log-tailer/tailing_session_test.go
  go/go.mod
  go/go.sum
  go/pfconfigdriver/structs.go
  html/pfappserver/root/static.alt/src/components/pfFormChosen.vue
  html/pfappserver/root/static.alt/src/main.js
  html/pfappserver/root/static.alt/src/store/modules/performance.js
  html/pfappserver/root/static.alt/src/styles/_form-chosen.scss
  html/pfappserver/root/static.alt/src/styles/_utilities.scss
  html/pfappserver/root/static.alt/src/views/Auditing/_api/index.js
  html/pfappserver/root/static.alt/src/views/Auditing/_components/LiveLogCreate.vue
  html/pfappserver/root/static.alt/src/views/Auditing/_components/LiveLogTabs.vue
  html/pfappserver/root/static.alt/src/views/Auditing/_components/LiveLogView.vue
  html/pfappserver/root/static.alt/src/views/Auditing/_router/index.js
  html/pfappserver/root/static.alt/src/views/Auditing/_store/liveLog.js
  html/pfappserver/root/static.alt/src/views/Auditing/_store/liveLogs.js
  html/pfappserver/root/static.alt/src/views/Auditing/index.vue
  lib/pf/config.pm
  lib/pf/constants/syslog.pm
  lib/pf/util.pm
  lib/pfconfig/namespaces/resource/syslog_files.pm
Labels: Status: Not ready, Type: Feature / Enhancement

#5411 feature/venom-backup-db-and-restore
  t/venom/Makefile
  t/venom/pfservers/backup_db_and_restore/00_backup_db_and_restore.yml
  t/venom/pfservers/backup_db_and_restore/TESTSUITE.md
  t/venom/pfservers/backup_db_and_restore/teardown/00_teardown.yml
  t/venom/vars/all.yml
Labels: Type: Feature / Enhancement

#5410 feature/templated_radius_attributes
  addons/upgrade/to-10.1-radius-filter-template.pl
  html/pfappserver/lib/pfappserver/Form/Config/FilterEngines/RADIUSFilter.pm
  html/pfappserver/lib/pfappserver/Form/Field/FilterCondition.pm
  html/pfappserver/lib/pfappserver/Form/Field/RadiusAnswer.pm
  html/pfappserver/root/static.alt/src/components/pfFieldPrefixTypeValue.vue
  html/pfappserver/root/static.alt/src/components/pfFormBoolean.vue
  html/pfappserver/root/static.alt/src/components/pfFormChosen.vue
  html/pfappserver/root/static.alt/src/globals/pfOperators.js
  html/pfappserver/root/static.alt/src/views/Configuration/_config/filterEngine.js
  html/pfappserver/root/static.alt/src/views/Configuration/_config/index.js
  lib/pf/Switch/Template.pm
  lib/pf/UnifiedApi/Controller/Config.pm
  lib/pf/UnifiedApi/Controller/Config/Subtype.pm
  lib/pf/access_filter/radius.pm
  lib/pf/condition_parser.pm
  lib/pf/config/builder/filter_engine.pm
  lib/pf/config/builder/filter_engine/radius.pm
  lib/pf/constants/filters.pm
  lib/pf/mini_template.pm
  lib/pf/radius.pm
  lib/pf/util.pm
  lib/pfconfig/namespaces/FilterEngine/AccessScopes.pm
  lib/pfconfig/namespaces/FilterEngine/RadiusScopes.pm
  t/unittest/UnifiedApi/Controller/Config/OPTIONS.t
  t/unittest/access_filter/radius.t
  t/unittest/condition_parser.t
  t/unittest/config/builder/filter_engine.t
  t/unittest/mini_template.t
  t/util.t
Labels: Priority: High, Status: For review, Type: Feature / Enhancement

#5480 feature/search-radius-attributes
  go/caddy/api/api.go
  go/caddy/api/error.go
  go/caddy/api/placeholders.go
  go/caddy/api/query.go
  go/caddy/api/radius_attributes.go
  go/caddy/api/radius_attributes_test.go
  go/pfconfigdriver/structs.go
Labels: Status: For review, Type: Feature / Enhancement

#4950 Feature/inline detection mecanism bypass passthrough
  go/httpdispatcher/proxy.go
Labels: Priority: Low, Status: For review, Type: Feature / Enhancement

#4212 feature/bulk_config_actions
  lib/pf/ConfigStore.pm
  lib/pf/ConfigStore/Pfdetect.pm
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config.pm
  t/unittest/UnifiedApi/Controller/Config/BulkImport.t
Labels: Status: For review, Type: Feature / Enhancement
