Repository inverse-inc/packetfence, pull requests merged in 2021-09, with the labels that each got.

#6566 Fix issues with integration tests
  .gitlab-ci.yml
  ci/lib/test/Makefile
  ci/lib/test/vagrant-wrapper.sh
  debian/rules
  rpm/packetfence-test.spec
  t/venom/pfservers/common/increase_log_level.yml
  t/venom/pfservers/common/utils/change_log_level.sh
  t/venom/pfservers/configurator/10_run_configurator_step1.yml
  t/venom/pfservers/configurator/45_increase_log_level.yml
  t/venom/pfservers/configurator/50_run_configurator_step4.yml
Labels: Status: In progress

#6567 Fix upgrade to v11
  docs/PacketFence_Upgrade_Guide.asciidoc
  docs/installation/export_import_mechanism.asciidoc
Labels: Status: In progress

#6572 multiple fixes to LDAP EAP-TTLS PAP
  conf/radiusd/packetfence-tunnel.example
  lib/pf/services/manager/radiusd_child.pm
  lib/pfconfig/namespaces/resource/authentication_sources_ldap.pm
Labels: Status: For review, Priority: High

#6586 Allow to use the sAMAccountName from the searchattributes in MSCHAP machine authentication
  conf/radiusd/mschap.conf.example
Labels: Status: For review

#6574 Tests: other VM are created only once
  .gitlab-ci.yml
  addons/vagrant/Vagrantfile
  addons/vagrant/cumulus/Vagrantfile
  addons/vagrant/inventory/group_vars/all/common.yml
  addons/vagrant/playbooks/config_dev_repos.yml
  addons/vagrant/playbooks/nodes/pre_prov/packages.yml
  addons/vagrant/playbooks/wireless.yml
  addons/vagrant/playbooks/wireless/wireless.yml
  addons/vagrant/requirements.yml
  ci/lib/test/Makefile
  ci/lib/test/vagrant-wrapper.sh
Labels: Status: In progress

#6591 Fixes for #6588
  go/cmd/galera-autofix/main.go
  go/galeraautofix/mariadb/mariadb.go
Labels: Status: For review

#6592 Feature/sql mode defaults
  addons/dev-helpers/bin/generator-data-access-layer.pl
  addons/dev-helpers/templates/pf-dal.pm.tt
  lib/pf/activation.pm
  lib/pf/dal/_bandwidth_accounting.pm
  lib/pf/dal/_dhcp_option82.pm
  lib/pf/dal/_dhcp_option82_history.pm
  lib/pf/dal/_dns_audit_log.pm
  lib/pf/dal/_locationlog.pm
  lib/pf/dal/_locationlog_history.pm
  lib/pf/dal/_pf_version.pm
  lib/pf/dal/_pki_certs.pm
  lib/pf/dal/_pki_revoked_certs.pm
  lib/pf/dal/_radius_audit_log.pm
  lib/pf/dal/_sms_carrier.pm
  t/unittest/UnifiedApi/Controller/Locationlogs.t
Labels: Status: For review, Priority: Low

#6420 feature/pfcmd-mariadb
  lib/pf/cmd/pf/mariadb.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: Low

#6587 Add script for removing wmi scan
  addons/upgrade/to-11.1-remove-wmi-scan.pl
  t/data/update-11.1/profiles-wmi.conf
  t/data/update-11.1/scan.conf
  t/unittest/upgrade/11.1-remove-wmi-scan.t
Labels: Type: Bug, Status: For review
