Repository inverse-inc/packetfence, pull requests merged in 2021-07, with the labels that each got.

#6324 Added owner fields in radius filter
  html/pfappserver/lib/pfappserver/Form/Config/FilterEngines/RADIUSFilter.pm
  lib/pf/radius.pm
Labels: Priority: Low, Status: For review, Type: Feature / Enhancement

#6392 Macro documentation in filter engine
  docs/installation/advanced_access_configuration.asciidoc
Labels: Priority: Low, Status: For review, Type: Feature / Enhancement

#6347 feature/audit-admin-login
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller.pm
  t/data/authentication.conf
  t/data/htpasswd.conf
  t/unittest/UnifiedApi/Controller/Authentication.t
Labels: Priority: Medium, Type: Feature / Enhancement

#6360 PFPKI intune support
  .gitignore
  conf/cloud.conf.example
  db/pf-schema-X.Y.sql
  db/upgrade-X.X-X.Y.sql
  debian/packetfence.conffiles
  docs/images/Intune-1-App-Registration.png
  docs/images/Intune-10-PacketFence-SCEP.png
  docs/images/Intune-2-Register-Application.png
  docs/images/Intune-3-App-Detail.png
  docs/images/Intune-4-App-Certificates-Secrets.png
  docs/images/Intune-5-Add-Client-Secret.png
  docs/images/Intune-6-Copy-Client-Secret.png
  docs/images/Intune-7-API-Permissions.png
  docs/images/Intune-8-Grant-Admin.png
  docs/images/packetfence-pki-scep.png
  docs/installation/pki/packetfence.asciidoc
  go/caddy/pfpki/certutils/certutils.go
  go/caddy/pfpki/cloud/cloud.go
  go/caddy/pfpki/cloud/intune.go
  go/caddy/pfpki/models/models.go
  go/caddy/pfpki/pfpki.go
  go/caddy/pfpki/scep/scep.go
  go/go.mod
  go/go.sum
  go/pfconfigdriver/structs.go
  html/pfappserver/lib/pfappserver/Form/Config/Cloud.pm
  html/pfappserver/lib/pfappserver/Form/Config/Cloud/Intune.pm
  html/pfappserver/root/src/store/modules/config.js
  html/pfappserver/root/src/views/Configuration/_components/CloudsList.vue
  html/pfappserver/root/src/views/Configuration/_config/cloud.js
  html/pfappserver/root/src/views/Configuration/_router/index.js
  html/pfappserver/root/src/views/Configuration/clouds/_api.js
  html/pfappserver/root/src/views/Configuration/clouds/_components/BaseFormGroupChosenOneCloud.js
  html/pfappserver/root/src/views/Configuration/clouds/_components/FormTypeIntune.vue
  html/pfappserver/root/src/views/Configuration/clouds/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/clouds/_components/TheView.js
  html/pfappserver/root/src/views/Configuration/clouds/_components/index.js
  html/pfappserver/root/src/views/Configuration/clouds/_composables/useCollection.js
  html/pfappserver/root/src/views/Configuration/clouds/_composables/useForm.js
  html/pfappserver/root/src/views/Configuration/clouds/_router.js
  html/pfappserver/root/src/views/Configuration/clouds/_store.js
  html/pfappserver/root/src/views/Configuration/clouds/config.js
  html/pfappserver/root/src/views/Configuration/clouds/schema.js
  html/pfappserver/root/src/views/Configuration/index.vue
  html/pfappserver/root/src/views/Configuration/pki/profiles/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/pki/profiles/_components/index.js
  lib/pf/ConfigStore/Cloud.pm
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config/Clouds.pm
  lib/pf/admin_roles.pm
  lib/pf/config.pm
  lib/pf/constants/admin_roles.pm
  lib/pf/constants/cloud.pm
  lib/pf/file_paths.pm
  lib/pfconfig/namespaces/config/Cloud.pm
  rpm/packetfence.spec
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#6380 Azure Active Directory support
  docs/installation/authentication_mechanisms.asciidoc
  docs/installation/azuread.asciidoc
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Login.pm
  html/pfappserver/lib/pfappserver/Form/Config/Realm.pm
  html/pfappserver/lib/pfappserver/Form/Config/Source/AzureAD.pm
  html/pfappserver/root/package-lock.json
  html/pfappserver/root/src/views/Configuration/realms/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/realms/_components/index.js
  html/pfappserver/root/src/views/Configuration/sources/_components/FormTypeAzureAD.vue
  html/pfappserver/root/src/views/Configuration/sources/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/sources/_components/index.js
  html/pfappserver/root/src/views/Configuration/sources/config.js
  lib/pf/Authentication/Condition.pm
  lib/pf/Authentication/Source/AzureADSource.pm
  lib/pf/CHI.pm
  lib/pf/UnifiedApi/Controller/Config/Sources.pm
  lib/pf/config.pm
  lib/pf/services/manager/radiusd_child.pm
  lib/pfconfig/namespaces/config/Authentication.pm
  lib/pfconfig/namespaces/resource/authentication_sources_azuread.pm
  raddb/dictionary
  raddb/dictionary.oauth2
  raddb/mods-config/perl/oauth2.pm
  raddb/mods-enabled/oauth2
  raddb/policy.d/oauth2
Labels: Status: In progress

#6421 fix/dup-logs-username-portal
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module.pm
Labels: Status: For review, Type: Bug

#6425 Fix MariaDB-backup on standalone installations
  addons/backup-and-maintenance.sh
  docs/installation/performance_optimizations.asciidoc
Labels: Status: In progress

#6409 feature/google-workspace-chromebook-provisioner
  conf/chi.conf.defaults
  docs/images/google-workspace-chromebook-config.png
  docs/installation/integrating_provisioning_agents.asciidoc
  docs/installation/provisioner/google_chrome_provisioner.asciidoc
  html/pfappserver/lib/pfappserver/Form/Config/Provisioning/google_workspace_chromebook.pm
  html/pfappserver/lib/pfappserver/Form/Field/JSON.pm
  html/pfappserver/root/src/views/Configuration/provisioners/_components/FormTypeGoogleWorkspaceChromebook.vue
  html/pfappserver/root/src/views/Configuration/provisioners/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/provisioners/_components/index.js
  html/pfappserver/root/src/views/Configuration/provisioners/config.js
  lib/pf/CHI.pm
  lib/pf/ConfigStore/Provisioning.pm
  lib/pf/UnifiedApi/Controller/Config/Provisionings.pm
  lib/pf/cmd/pf/import.pm
  lib/pf/cmd/pf/import/google_chromebook_provisioner.pm
  lib/pf/defer.pm
  lib/pf/factory/provisioner.pm
  lib/pf/provisioner/google_workspace_chromebook.pm
  lib/pfconfig/namespaces/config/Provisioning.pm
  t/data/provisioning.conf
  t/data/security_events.conf
  t/mock_servers/google-provisioner-chromebook.pl
  t/unittest/ConfigStore/Provisioning.t
  t/unittest/UnifiedApi/Controller/Config/Provisionings.t
  t/unittest/pfappserver/Form/Field/JSON.t
  t/unittest/provisioner/google_workspace_chromebook.t
Labels: Status: For review, Type: Feature / Enhancement

#6383 feature/resend-sms
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Application.pm
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/SMS.pm
  html/captive-portal/templates/sms/validate.html
  lib/pf/activation.pm
Labels: Status: For review, Type: Feature / Enhancement

#6363 feature/google-workspace-ldap
  docs/installation/authentication_mechanisms.asciidoc
  docs/installation/google_workspace_ldap.asciidoc
  html/pfappserver/lib/pfappserver/Form/Config/Source/GoogleWorkspaceLDAP.pm
  html/pfappserver/lib/pfappserver/Form/Config/Source/LDAP.pm
  html/pfappserver/lib/pfappserver/Form/Field/Path.pm
  html/pfappserver/root/src/views/Configuration/sources/_components/FormTypeLdap.vue
  html/pfappserver/root/src/views/Configuration/sources/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/sources/_components/index.js
  html/pfappserver/root/src/views/Configuration/sources/config.js
  lib/pf/Authentication/Source/GoogleWorkspaceLDAPSource.pm
  lib/pf/Authentication/Source/LDAPSource.pm
  lib/pf/LDAP.pm
  lib/pf/UnifiedApi/Controller/Config/Sources.pm
  lib/pf/authentication.pm
  t/data/authentication.conf
  t/unittest/Authentication/Source/LDAPSource.t
  t/unittest/UnifiedApi/Controller/Config/Sources.t
  t/unittest/pfappserver/Form/Field/Path.t
Labels: Status: For review, Type: Feature / Enhancement

#6335 fix/config-switch-roles
  html/pfappserver/lib/pfappserver/Form/Config/Switch.pm
  lib/pf/ConfigStore/Switch.pm
  lib/pf/UnifiedApi/Controller/Config.pm
  lib/pf/UnifiedApi/Controller/Config/SwitchGroups.pm
  lib/pf/UnifiedApi/Controller/Config/SwitchRole.pm
  lib/pf/UnifiedApi/Controller/Config/Switches.pm
  lib/pfconfig/namespaces/config/Switch.pm
  t/data/roles.conf
  t/unittest/ConfigStore/Switch.t
  t/unittest/UnifiedApi/Controller/Config/SwitchGroups.t
  t/unittest/UnifiedApi/Controller/Config/Switches.t
Labels: Status: For review

#6415 fix/6386
  html/pfappserver/lib/pfappserver/Form/Config/Switch.pm
  html/pfappserver/lib/pfappserver/Form/Field/SwitchID.pm
  lib/pf/UnifiedApi/Controller/Config.pm
  t/unittest/UnifiedApi/Controller/Config/ConnectionProfiles.t
  t/unittest/UnifiedApi/Controller/Config/Switches.t
Labels: Status: For review, Type: Bug
