Repository inverse-inc/packetfence, pull requests merged in 2021-12, with the labels that each got.

#6742 Close only wired connections
  lib/pf/locationlog.pm
Labels: Type: Bug, Status: For review, Priority: Critical

#6737 Search both the Packet-Src-IP-Address and raw:NAS-IP-Address for the switch information
  raddb/sites-available/dynamic-clients
Labels: Type: Bug, Status: For review, Priority: Medium

#6744 Venom: NAT fix and captive portal test suite
  .gitlab-ci.yml
  addons/vagrant/inventory/group_vars/wireless/hostapd.yml
  addons/vagrant/inventory/hosts
  debian/control
  t/venom/Makefile
  t/venom/lib/delete_node.yml
  t/venom/lib/run_cumulus_command.yml
  t/venom/lib/run_cumulus_command_without_output.yml
  t/venom/lib/run_pfcmd_command.yml
  t/venom/lib/sleep.yml
  t/venom/pfservers/captive_portal/15_enable_mac_auth_dot1x_int.yml
  t/venom/pfservers/captive_portal/17_enable_dynamic_vlan.yml
  t/venom/pfservers/captive_portal/20_commit_config.yml
  t/venom/pfservers/captive_portal/30_check_mac_auth_unreg.yml
  t/venom/pfservers/captive_portal/35_check_locales_on_portal.yml
  t/venom/pfservers/captive_portal/teardown/05_disable_mac_auth_dot1x_int.yml
  t/venom/pfservers/captive_portal/teardown/07_disable_dynamic_vlan.yml
  t/venom/pfservers/captive_portal/teardown/10_commit_config.yml
  t/venom/pfservers/captive_portal/teardown/15_delete_node01.yml
  t/venom/pfservers/captive_portal/teardown/20_check_node01_deleted.yml
  t/venom/pfservers/captive_portal/teardown/25_clean_httpd_portal_cache.yml
  t/venom/scenarios/captive_portal/playbooks/rsync.yml
  t/venom/scenarios/captive_portal/playbooks/run_tests.yml
  t/venom/scenarios/captive_portal/site.yml
  t/venom/test_suites/captive_portal/10_create_connection_profile.yml
  t/venom/test_suites/captive_portal/15_enable_mac_auth_dot1x_int.yml
  t/venom/test_suites/captive_portal/17_enable_dynamic_vlan.yml
  t/venom/test_suites/captive_portal/20_commit_config.yml
  t/venom/test_suites/captive_portal/22_sleep_some_time.yml
  t/venom/test_suites/captive_portal/25_check_radius_audit_log.yml
  t/venom/test_suites/captive_portal/30_check_mac_auth_unreg.yml
  t/venom/test_suites/captive_portal/32_sleep_some_time.yml
  t/venom/test_suites/captive_portal/TESTSUITE.md
  t/venom/test_suites/captive_portal/locales/00_check_locales_on_portal.yml
  t/venom/test_suites/captive_portal/teardown/05_disable_mac_auth_dot1x_int.yml
  t/venom/test_suites/captive_portal/teardown/07_disable_dynamic_vlan.yml
  t/venom/test_suites/captive_portal/teardown/10_commit_config.yml
  t/venom/test_suites/captive_portal/teardown/15_delete_node01.yml
  t/venom/test_suites/captive_portal/teardown/25_clean_httpd_portal_cache.yml
  t/venom/test_suites/captive_portal/teardown/30_delete_connection_profile.yml
  t/venom/test_suites/global_config/15_create_network_devices.yml
  t/venom/test_suites/global_teardown/00_teardown.yml
  t/venom/test_suites/nodes/captive_portal/check_locales_on_portal.yml
  t/venom/test_suites/nodes/common/check_internet_access.yml
  t/venom/test_suites/nodes/common/check_wlan1_int_status_down.yml
  t/venom/test_suites/nodes/common/check_wlan1_int_status_up.yml
  t/venom/test_suites/nodes/common/kill_wpasupplicant.yml
  t/venom/test_suites/nodes/dot1x_eap_peap/run_wpasupplicant.yml
  t/venom/test_suites/nodes/wired_dot1x_eap_tls/run_sscep_on_node01.yml
  t/venom/test_suites/nodes/wired_dot1x_eap_tls/run_wpasupplicant.yml
  t/venom/test_suites/nodes/wireless_dot1x_eap_peap/run_wpasupplicant.yml
  t/venom/test_suites/nodes/wireless_mac_auth/run_wpasupplicant.yml
  t/venom/vars/all.yml
Labels: Status: In progress

#6758 Revert "Remove interval"
  lib/pf/pfcron/task.pm
Labels: Type: Bug, Status: For review, Priority: Critical

#6765 fix(docs): stop monit and services before maintenance patches
  docs/PacketFence_Upgrade_Guide.asciidoc
Labels: Status: For review

#6784 Feature/venom upload logs
  .gitlab-ci.yml
  README.md
  addons/vagrant/Vagrantfile
  addons/vagrant/inventory/group_vars/nodes/venom.yml
  addons/vagrant/playbooks/get_logs.yml
  addons/vagrant/playbooks/tasks/register_rhel_subscription_tasks.yml
  addons/vagrant/playbooks/tasks/unregister_rhel_subscription_tasks.yml
  addons/vagrant/teardown.yml
  ci/lib/check/run-pipeline-if-necessary.sh
  debian/rules
  rpm/packetfence-test.spec
  t/venom/Makefile
  t/venom/test-wrapper.sh
  t/venom/utils/sanitize-venom-logs.sh
Labels: Status: For review

#6773 Fix/6766
  conf/radiusd/eap.conf.example
  conf/radiusd/tls.conf.defaults
  docs/PacketFence_Upgrade_Guide.asciidoc
  html/pfappserver/lib/pfappserver/Form/Config/Radiusd/TLSProfile.pm
  html/pfappserver/root/src/views/Configuration/radius/tls/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/radius/tls/_components/index.js
  lib/pf/radius/constants.pm
Labels: Type: Bug, Status: For review, Priority: High

#6783 Test suite Feature/venom cli login tests
  .gitlab-ci.yml
  t/venom/Makefile
  t/venom/lib/delete_file.yml
  t/venom/lib/delete_realm.yml
  t/venom/lib/delete_source.yml
  t/venom/lib/delete_switch.yml
  t/venom/lib/restart_radius_services.yml
  t/venom/lib/systemctl_service.yml
  t/venom/scenarios/cli_login/ansible_inventory.yml
  t/venom/scenarios/cli_login/playbooks/configure.yml
  t/venom/scenarios/cli_login/playbooks/rsync.yml
  t/venom/scenarios/cli_login/playbooks/run_tests.yml
  t/venom/scenarios/cli_login/site.yml
  t/venom/test_suites/cli-login-radius/00_create_admin_roles.yml
  t/venom/test_suites/cli-login-radius/05_create_radius_machine_source.yml
  t/venom/test_suites/cli-login-radius/10_create_switch.yml
  t/venom/test_suites/cli-login-radius/15_create_realms.yml
  t/venom/test_suites/cli-login-radius/20_start_services.yml
  t/venom/test_suites/cli-login-radius/25_start_radius_request.yml
  t/venom/test_suites/cli-login-radius/TESTSUITE.md
  t/venom/test_suites/cli-login-radius/teardown/00_clean_pf_config.yml
  t/venom/test_suites/cli-login-radius/teardown/05_stop_service.yml
  t/venom/test_suites/cli-login-radius/teardown/10_delete_files.yml
  t/venom/test_suites/cli-login-radius/teardown/95_restart_radius_services.yml
  t/venom/vars/all.yml
Labels: Type: Feature / Enhancement, Priority: Medium, Status: Tested and works
