Repository inverse-inc/packetfence, pull requests merged in 2021-11, with the labels that each got.

#6670 fix/6645
  html/captive-portal/lib/captiveportal/PacketFence/Controller/SecurityEvent.pm
Labels: Status: For review

#6674 fix/6666
  addons/backup-and-maintenance.sh
  conf/pfcron.conf.defaults
  go/cron/config.go
Labels: Type: Bug, Status: For review

#6687 pfpki: workaround for Windows devices configured through Intune
  go/caddy/pfpki/pfpki.go
  go/go.mod
  go/go.sum
Labels: Status: In progress

#6662 remove unused etcd plugin from coredns due to indirect dependency vulnerability
  go/coredns/core/plugin/zplugin.go
  go/coredns/plugin/etcd/README.md
  go/coredns/plugin/etcd/cname_test.go
  go/coredns/plugin/etcd/etcd.go
  go/coredns/plugin/etcd/group_test.go
  go/coredns/plugin/etcd/handler.go
  go/coredns/plugin/etcd/log_test.go
  go/coredns/plugin/etcd/lookup_test.go
  go/coredns/plugin/etcd/multi_test.go
  go/coredns/plugin/etcd/other_test.go
  go/coredns/plugin/etcd/setup.go
  go/coredns/plugin/etcd/setup_test.go
  go/coredns/plugin/etcd/xfr.go
  go/coredns/test/etcd_cache_test.go
  go/coredns/test/etcd_credentials_test.go
  go/coredns/test/etcd_test.go
  go/go.mod
  go/go.sum
Labels: Status: For review

#6711 Feature/venom local dev
  addons/vagrant/Vagrantfile
  addons/vagrant/cumulus/Vagrantfile
  addons/vagrant/helper_scripts/config_node01.sh
  addons/vagrant/helper_scripts/config_node02.sh
  addons/vagrant/helper_scripts/config_switch.sh
  addons/vagrant/inventory/group_vars/all/common.yml
  addons/vagrant/inventory/group_vars/dev/packetfence_install.yml
  addons/vagrant/inventory/group_vars/linux_servers/freeradius.yml
  addons/vagrant/inventory/group_vars/linux_servers/tinyproxy.yml
  addons/vagrant/inventory/group_vars/localdev/packetfence_install.yml
  addons/vagrant/inventory/group_vars/pfservers/packetfence_install.yml
  addons/vagrant/inventory/group_vars/pfservers/rhel_subscription.yml
  addons/vagrant/inventory/group_vars/pfservers/venom_local_vars.yml
  addons/vagrant/inventory/group_vars/service_rsyslog/rsyslog.yml
  addons/vagrant/inventory/group_vars/wireless/gitlab_buildpkg_tools.yml
  addons/vagrant/inventory/hosts
  addons/vagrant/linux_servers/Vagrantfile
  addons/vagrant/pfservers/Vagrantfile
  addons/vagrant/playbooks/nodes/pre_prov/packages.yml
  addons/vagrant/requirements.yml
  addons/vagrant/winservers/Vagrantfile
  addons/vagrant/wireless/Vagrantfile
  t/venom/Makefile
  t/venom/requirements.yml
  t/venom/scenarios/configurator/playbooks/rsync.yml
  t/venom/scenarios/configurator/site.yml
  t/venom/scenarios/dot1x_eap_peap/playbooks/rsync.yml
  t/venom/scenarios/dot1x_eap_peap/site.yml
  t/venom/scenarios/dot1x_eap_tls/playbooks/rsync.yml
  t/venom/scenarios/dot1x_eap_tls/site.yml
  t/venom/scenarios/example/playbooks/rsync.yml
  t/venom/scenarios/example/site.yml
  t/venom/scenarios/export_import/playbooks/rsync.yml
  t/venom/scenarios/export_import/site.yml
  t/venom/scenarios/mac_auth/playbooks/rsync.yml
  t/venom/scenarios/mac_auth/site.yml
  t/venom/scenarios/template/playbooks/rsync.yml
  t/venom/scenarios/template/site.yml
  t/venom/scenarios/unit_tests/playbooks/rsync.yml
  t/venom/scenarios/unit_tests/site.yml
  t/venom/test-wrapper.sh
  t/venom/vars/all.yml
Labels: Status: For review
