Repository inverse-inc/packetfence, pull requests merged in 2021-04, with the labels that each got.

#6306 docs: improve troubleshooting and maintenance of a cluster
  docs/cluster/appendix.asciidoc
  docs/cluster/maintenance_and_operations.asciidoc
  docs/cluster/troubleshooting_a_cluster.asciidoc
Labels: Status: For review

#6320 docs: disable properly galera-autofix during an upgrade
  docs/PacketFence_Upgrade_Guide.asciidoc
  docs/cluster/appendix.asciidoc
Labels: Status: For review, Status: In progress

#6293 Feature/move pre process filter
  lib/pf/radius.pm
Labels: Priority: Medium, Status: For review, Type: Feature / Enhancement

#6311 UI User Preferences
  html/pfappserver/root/src/App.vue
  html/pfappserver/root/src/components/new/BaseInputGroupTextarea.vue
  html/pfappserver/root/src/composables/usePreferences.js
  html/pfappserver/root/src/main.js
  html/pfappserver/root/src/router/index.js
  html/pfappserver/root/src/views/Configuration/pki/profiles/_components/TheForm.vue
  html/pfappserver/root/src/views/Preferences/_components/TabPermissions.vue
  html/pfappserver/root/src/views/Preferences/_components/TabSettings.vue
  html/pfappserver/root/src/views/Preferences/_components/TheView.vue
  html/pfappserver/root/src/views/Preferences/_router/index.js
  html/pfappserver/root/src/views/Preferences/index.vue
Labels: Priority: Low, Status: For review

#6266 Feature/venom inline l3
  addons/vagrant/cumulus/Vagrantfile
  addons/vagrant/helper_scripts/config_node01.sh
  addons/vagrant/helper_scripts/config_node02.sh
  addons/vagrant/helper_scripts/config_switch.sh
  addons/vagrant/inventory/hosts
  docs/developer/integration_tests/subnets_and_ips.asciidoc
  docs/developer/integration_tests/virtual_machines.asciidoc
  docs/developer/integration_tests/wired_network_topology.asciidoc
  docs/images/integration_tests/wired_topology.drawio
  docs/images/integration_tests/wired_topology.png
  t/venom/pfservers/inline_l3/TESTSUITE.md
Labels: Status: For review
