Repository inverse-inc/packetfence, pull requests merged in 2021-10, with the labels that each got.

#6606 (letsencrypt renew) Test if service is enabled
  lib/pf/cmd/pf/renew_lets_encrypt.pm
Labels: Type: Bug, Status: For review, Priority: Medium

#6599 Removes the deprecated NTLM background job fields and components
  addons/upgrade/to-11.1-cleanup-ntlm-cache-batch-fields.pl
  docs/images/domain-ntlm-cache.png
  docs/installation/performance_optimizations.asciidoc
  html/pfappserver/lib/pfappserver/Form/Config/Domain.pm
  lib/pf/domain/ntlm_cache.pm
  lib/pfconfig/namespaces/config/Domain.pm
  lib/pfconfig/namespaces/resource/NtlmRedisCachedDomains.pm
Labels: Status: For review

#6216 Feature/mikrotik dhcp
  lib/pf/Switch/Mikrotik.pm
  raddb/policy.d/canonicalization
Labels: Type: Feature / Enhancement, Status: For review

#6600 Be more precise in auth match when finding access for CLI login
  lib/pf/authentication.pm
  lib/pf/radius.pm
Labels: Status: For review
