Repository inverse-inc/packetfence, pull requests merged in 2022-07, with the labels that each got.

#7055 Split read/writes in a cluster
  .gitlab-ci.yml
  conf/haproxy-admin.conf.example
  conf/pf.conf.defaults
  conf/proxysql.conf.example
  conf/systemd/packetfence-haproxy-admin.service
  conf/systemd/packetfence-proxysql.service
  containers/docker-minimal-rules.sh
  containers/haproxy-admin/Dockerfile
  debian/patches/debianize.patch
  docs/cluster/assumptions.asciidoc
  docs/cluster/layer_3_clusters.asciidoc
  lib/pf/cluster.pm
  lib/pf/config/cluster.pm
  lib/pf/services/manager/haproxy_admin.pm
  lib/pf/services/manager/iptables.pm
  lib/pf/services/manager/proxysql.pm
  rpm/packetfence.spec
  sbin/haproxy-admin-docker-wrapper
Labels: Status: For review

#7027 feature/multi-sql-reports
  conf/report.conf.defaults
  docs/installation/advanced_topics.asciidoc
  t/data/report.conf
Labels: Status: For review

#7059 Fix AD integration with recent containerization
  conf/systemd/packetfence-pfqueue.service
  containers/radiusd-auth/Dockerfile
  containers/systemd-service
  html/pfappserver/root/src/views/Configuration/domains/_store.js
  lib/pf/UnifiedApi/Controller/Config/Domains.pm
  lib/pf/cmd/pf/generatedomainconfig.pm
  lib/pf/domain.pm
  lib/pf/task/domain.pm
  sbin/pfperl-api-docker-wrapper
  sbin/radiusd-auth-docker-wrapper
Labels: Status: For review

#7060 feature/mysql-compatibility
  go/cron/bandwidth_maintenance.go
  go/cron/bandwidth_maintenance_test.go
  go/cron/batch.go
  lib/pf/dal.pm
Labels: Priority: High

#6937 feature/utf8-db
  conf/mariadb/mariadb.conf.tt.example
  db/pf-schema-X.Y.sql
  db/upgrade-X.X-X.Y.sql
  go/db/db.go
  html/pfappserver/lib/pfappserver/Model/DB.pm
  lib/pf/db.pm
  t/db/setup_test_db.pl
  t/log.conf
  t/test_apply_schema.sh
  t/unittest/UnifiedApi/Controller/Nodes.t
  t/unittest/db/is_utf8.t
Labels: Type: Feature / Enhancement, Status: For review, Priority: Critical

#7013 Configuration management of PF for K8S environments
  Makefile
  addons/dev-helpers/create-pf-git-storage.sh
  addons/dev-helpers/update-pf-git-storage.sh
  conf/pf.conf.defaults
  conf/pfconfig.conf.defaults
  lib/pf/ConfigStore.pm
  lib/pf/ConfigStore/FingerbankSettings.pm
  lib/pf/ConfigStore/Roles.pm
  lib/pf/ConfigStore/SecurityEvents.pm
  lib/pf/ConfigStore/Survey.pm
  lib/pf/ConfigStore/Switch.pm
  lib/pf/UnifiedApi/Controller/Config/ConnectionProfiles.pm
  lib/pf/config.pm
  lib/pf/k8s.pm
  lib/pf/k8s/pods.pm
  lib/pf/security_event_config.pm
  lib/pf/services/manager/radiusd_child.pm
  lib/pf/ssl.pm
  lib/pf/util.pm
  lib/pfconfig/git_storage.pm
  lib/pfconfig/manager.pm
  lib/pfconfig/util.pm
  rpm/packetfence.spec
  sbin/haproxy-admin-docker-wrapper
  sbin/pfconfig
  sbin/pfperl-api-docker-wrapper
Labels: Status: For review

#6934 feature/processing-bandwidth-accounting
  conf/documentation.conf
  conf/pf.conf.defaults
  go/cmd/pfacct/pfacct.go
  go/cmd/pfacct/radius.go
  go/pfconfigdriver/structs.go
  html/pfappserver/root/src/views/Configuration/fingerbank/generalSettings/_components/TheView.js
  html/pfappserver/root/src/views/Configuration/radius/general/_components/AlertServices.vue
  html/pfappserver/root/src/views/Configuration/radius/general/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/radius/general/_components/TheView.js
  html/pfappserver/root/src/views/Configuration/radius/general/_components/index.js
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#6950 fix: use CRLF for mails sent to SMTP servers
  lib/pf/Authentication/Source/SMSSource.pm
  lib/pf/UnifiedApi/Controller/Config/Bases.pm
  lib/pf/config/util.pm
Labels: Status: For review, Priority: Low

#7067 Sophos VPN Support
  lib/pf/Switch/Sophos.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#7017 add radius filter to use ttls-pap username from inner tunnel in reply
  conf/radius_filters.conf.defaults
  conf/radiusd/packetfence-tunnel.example
Labels: Status: Question, Status: For review

#6969 Remote unused potentially dangerous caddy middlewares
  go/caddy/caddy/caddyhttp/browse/browse.go
  go/caddy/caddy/caddyhttp/browse/setup.go
  go/caddy/caddy/caddyhttp/browse/testdata/header.html
  go/caddy/caddy/caddyhttp/browse/testdata/photos.tpl
  go/caddy/caddy/caddyhttp/browse/testdata/photos/hidden.html
  go/caddy/caddy/caddyhttp/browse/testdata/photos/test.html
  go/caddy/caddy/caddyhttp/browse/testdata/photos/test1/test.html
  go/caddy/caddy/caddyhttp/browse/testdata/photos/test2.html
  go/caddy/caddy/caddyhttp/browse/testdata/photos/test3.html
  go/caddy/caddy/caddyhttp/caddyhttp.go
  go/caddy/caddy/caddyhttp/fastcgi/fastcgi.go
  go/caddy/caddy/caddyhttp/fastcgi/fcgi_test.php
  go/caddy/caddy/caddyhttp/fastcgi/fcgiclient.go
  go/caddy/caddy/caddyhttp/fastcgi/setup.go
  go/caddy/caddy/caddyhttp/httpserver/plugin.go
  go/caddy/caddy/caddyhttp/push/handler.go
  go/caddy/caddy/caddyhttp/push/link_parser.go
  go/caddy/caddy/caddyhttp/push/push.go
  go/caddy/caddy/caddyhttp/push/setup.go
Labels: Status: For review

#6864 Configurable Sender email address for monit
  addons/monit/monit_build_configuration.pl
  addons/monit/monit_configurations/monit_general.tt
  conf/documentation.conf
  conf/pf.conf.defaults
  html/pfappserver/root/src/views/Configuration/monit/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/monit/_components/index.js
  lib/pf/cmd/pf/generatemonitconfig.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium

#7066 Cookie session id as param in the redirect url (Akamai MFA)
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/MFA.pm
  html/captive-portal/lib/captiveportal/PacketFence/Model/Portal/Session.pm
  lib/pf/Portal/Session.pm
  lib/pf/mfa/Akamai.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#7069 fix/3804-part2
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Email.pm
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Sponsor.pm
  html/captive-portal/templates/emails/emails-guest_email_activation.html
  html/captive-portal/templates/emails/emails-guest_email_activation.mjml
  html/captive-portal/templates/emails/emails-guest_sponsor_activation.html
  html/captive-portal/templates/emails/emails-guest_sponsor_activation.mjml
  lib/pf/person.pm
Labels: Type: Feature / Enhancement

#7070 Fix Connection type detection on Dell switches (n1500)
  lib/pf/Switch/Dell/N1500.pm
  lib/pf/radius.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: High, Status: Tested and works
