Repository inverse-inc/packetfence, pull requests merged in 2022-06, with the labels that each got.

#7015 Fingerbank Upstream DB image builder
  .gitlab-ci.yml
  containers/fingerbank-db/Dockerfile
  containers/kanikobuild
Labels: Status: For review

#7020 [Containers] pfpki: add as a container
  .gitlab-ci.yml
  conf/caddy-services/pfpki.conf.example
  conf/systemd/packetfence-pfpki.service
  containers/pfpki/Dockerfile
  rpm/packetfence.spec
  sbin/pfpki-docker-wrapper
Labels: Status: For review

#7021 Fix/intune scep
  go/caddy/pfpki/cloud/intune.go
Labels: Type: Bug, Status: For review, Priority: Critical, Status: Tested and works

#6921 Improve Network View
  html/pfappserver/root/package.json
  html/pfappserver/root/src/views/Status/network/_components/TheGraph.scss
  html/pfappserver/root/src/views/Status/network/_components/TheGraph.vue
  html/pfappserver/root/src/views/Status/network/_components/TheSearch.vue
  html/pfappserver/root/src/views/Status/network/_components/TooltipNode.vue
  html/pfappserver/root/src/views/Status/network/_components/TooltipPacketfence.vue
  html/pfappserver/root/src/views/Status/network/_components/TooltipSwitch.vue
  html/pfappserver/root/src/views/Status/network/_components/TooltipSwitchGroup.vue
  html/pfappserver/root/src/views/Status/network/_composables/useSimulation.js
  html/pfappserver/root/src/views/Status/network/_composables/useSvg.js
  html/pfappserver/root/src/views/Status/network/_composables/useTooltips.js
Labels: Status: For review

#7000 Add support for Role Based Enforcement for Meraki wired devices
  lib/pf/Switch/Meraki/MS220_8.pm
Labels: Status: For review

#7024 Improve pfconnector support in switch modules
  conf/switches.conf.defaults
  html/pfappserver/lib/pfappserver/Form/Config/Switch.pm
  html/pfappserver/root/src/views/Configuration/switchGroups/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/switchGroups/_components/index.js
  html/pfappserver/root/src/views/Configuration/switches/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/switches/_components/index.js
  lib/pf/Switch.pm
  lib/pf/Switch/AeroHIVE.pm
  lib/pf/Switch/Alcatel.pm
  lib/pf/Switch/Aruba.pm
  lib/pf/Switch/Aruba/2930M.pm
  lib/pf/Switch/Aruba/CX.pm
  lib/pf/Switch/Aruba/Instant_Access.pm
  lib/pf/Switch/ArubaSwitch.pm
  lib/pf/Switch/Avaya.pm
  lib/pf/Switch/Cisco.pm
  lib/pf/Switch/Cisco/ASA.pm
  lib/pf/Switch/Cisco/Aironet_1600.pm
  lib/pf/Switch/Cisco/Catalyst_2960.pm
  lib/pf/Switch/Cisco/WLC.pm
  lib/pf/Switch/Dell/N1500.pm
  lib/pf/Switch/Enterasys/V2110.pm
  lib/pf/Switch/Hostapd.pm
  lib/pf/Switch/Huawei.pm
  lib/pf/Switch/Juniper/EX2200.pm
  lib/pf/Switch/Juniper/EX2200_v15.pm
  lib/pf/Switch/Juniper/EX2300.pm
  lib/pf/Switch/Meraki/MR_v2.pm
  lib/pf/Switch/Mikrotik.pm
  lib/pf/Switch/Mojo.pm
  lib/pf/Switch/Pica8.pm
  lib/pf/Switch/Ruckus/SmartZone.pm
  lib/pf/Switch/Template.pm
  lib/pf/Switch/Ubiquiti/Unifi.pm
  lib/pf/Switch/Xirrus.pm
  lib/pf/constants/filters.pm
  lib/pf/util/radius.pm
Labels: Status: For review

#7028 Docker iptables systemd service
  conf/systemd/packetfence-api-frontend.service
  conf/systemd/packetfence-config.service
  conf/systemd/packetfence-docker-iptables.service
  conf/systemd/packetfence-haproxy-admin.service
  conf/systemd/packetfence-haproxy-portal.service
  conf/systemd/packetfence-httpd.aaa.service
  conf/systemd/packetfence-httpd.admin_dispatcher.service
  conf/systemd/packetfence-httpd.dispatcher.service
  conf/systemd/packetfence-httpd.portal.service
  conf/systemd/packetfence-httpd.webservices.service
  conf/systemd/packetfence-iptables.service
  conf/systemd/packetfence-pfconnector-client.service
  conf/systemd/packetfence-pfconnector-server.service
  conf/systemd/packetfence-pfperl-api.service
  conf/systemd/packetfence-pfpki.service
  conf/systemd/packetfence-pfqueue.service
  conf/systemd/packetfence-pfsso.service
  conf/systemd/packetfence-radiusd-acct.service
  conf/systemd/packetfence-radiusd-auth.service
  conf/systemd/packetfence-radiusd-cli.service
  conf/systemd/packetfence-radiusd-eduroam.service
  conf/systemd/packetfence-radiusd-load_balancer.service
  containers/docker_iptables.sh
  debian/packetfence-docker-iptables.service
  debian/patches/debianize.patch
  debian/rules
  lib/pf/cmd/pf.pm
  lib/pf/cmd/pf/generatedockeriptables.pm
  rpm/packetfence.spec
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#7039 Align Apache timeout with captive_portal.request_timeout
  conf/httpd.conf.d/httpd.portal.tt.example
Labels: Status: For review

#7035 Only apply NatDNS if it´s an inline network
  go/cmd/pfdhcp/utils.go
Labels: Type: Bug, Status: For review, Priority: High, Status: Tested and works
