Repository inverse-inc/packetfence, pull requests merged in 2022-01, with the labels that each got.

#6767 Various fixes for PKI
  docs/installation/pki/packetfence.asciidoc
  go/caddy/pfpki/models/models.go
  go/go.mod
  go/go.sum
  t/venom/test_suites/nodes/wired_dot1x_eap_tls/run_sscep_on_node01.yml
  t/venom/test_suites/wired_dot1x_eap_tls_manual/45_create_eaptls_source.yml
  t/venom/test_suites/wired_dot1x_eap_tls_scep/45_create_eaptls_source.yml
  t/venom/vars/all.yml
Labels: Type: Bug, Priority: High

#6792 fix/6789
  lib/pf/pfcmd/checkup.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#6692 Fix/docs huawei
  docs/network/networkdevice/huawei_switchs.asciidoc
Labels: Status: For review

#6774 Feature/ruckus floating devices
  lib/pf/Switch/Brocade.pm
  lib/pf/radius.pm
Labels: Status: Not ready

#6726 Get username from _session in case of SAML authentication
  html/captive-portal/lib/captiveportal/PacketFence/Controller/DeviceRegistration.pm
  html/captive-portal/lib/captiveportal/PacketFence/Controller/Node/Manager.pm
  html/captive-portal/lib/captiveportal/PacketFence/Controller/Status.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium, Status: Tested and works

#6804 Feature/vagrant cluster setup
  .gitlab-ci.yml
  addons/vagrant/inventory/group_vars/all/common.yml
  addons/vagrant/inventory/group_vars/clusters/packetfence_install.yml
  addons/vagrant/inventory/group_vars/clusters/venom_local_vars.yml
  addons/vagrant/inventory/group_vars/standalones/venom_local_vars.yml
  addons/vagrant/inventory/hosts
  addons/vagrant/playbooks/enable_ipv6_el_os.yml
  addons/vagrant/requirements.yml
  ci/packer/vagrant_img/Makefile
  ci/packer/vagrant_img/provisioners/inventory/group_vars/pfservers/locales.yml
  ci/packer/vagrant_img/provisioners/playbooks/debian.yml
  ci/packer/vagrant_img/sources.pkr.hcl
  t/venom/Makefile
  t/venom/requirements.yml
  t/venom/scenarios/cluster/playbooks/configure.yml
  t/venom/scenarios/cluster/playbooks/rsync.yml
  t/venom/scenarios/cluster/playbooks/run_tests.yml
  t/venom/scenarios/cluster/site.yml
  t/venom/test-wrapper.sh
Labels: Status: For review

#6828 improve timeout handling in monitoring-scripts run
  addons/monit/monitoring-scripts/run-all.sh
Labels: Status: For review

#6770 Feature/pki resign ca
  go/caddy/pfpki/handlers/handlers.go
  go/caddy/pfpki/models/models.go
  go/caddy/pfpki/pfpki.go
  html/pfappserver/root/src/components/new/BaseFormButtonBar.vue
  html/pfappserver/root/src/composables/useFormButtonBar.js
  html/pfappserver/root/src/views/Configuration/_components/new/BaseViewCollectionItem.vue
  html/pfappserver/root/src/views/Configuration/_composables/useViewCollectionItem.js
  html/pfappserver/root/src/views/Configuration/domains/_components/TheView.js
  html/pfappserver/root/src/views/Configuration/pki/cas/_api.js
  html/pfappserver/root/src/views/Configuration/pki/cas/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/pki/cas/_components/TheView.js
  html/pfappserver/root/src/views/Configuration/pki/cas/_composables/useCollection.js
  html/pfappserver/root/src/views/Configuration/pki/cas/_store.js
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium, Status: Tested and works

#6829 Fix/6826
  go/caddy/pfpki/handlers/handlers.go
  go/caddy/pfpki/models/models.go
  go/caddy/pfpki/pfpki.go
  lib/pf/pki_provider/packetfence_pki.pm
Labels: Type: Bug, Status: For review, Priority: High

#6778 Hide download and email if the certificate has been signed by scep request
  db/pf-schema-X.Y.sql
  db/upgrade-X.X-X.Y.sql
  go/caddy/pfpki/models/models.go
  html/pfappserver/root/src/views/Configuration/pki/certs/_components/ButtonCertificateCopy.vue
  html/pfappserver/root/src/views/Configuration/pki/certs/_components/ButtonCertificateDownload.vue
  html/pfappserver/root/src/views/Configuration/pki/certs/_components/ButtonCertificateEmail.vue
  html/pfappserver/root/src/views/Configuration/pki/certs/_components/TheSearch.vue
  html/pfappserver/root/src/views/Configuration/pki/certs/_components/TheView.js
  html/pfappserver/root/src/views/Configuration/pki/certs/_components/index.js
  html/pfappserver/root/src/views/Configuration/pki/certs/_composables/useCollection.js
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium

#6823 Various fixes for pfpki
  db/pf-schema-X.Y.sql
  db/upgrade-X.X-X.Y.sql
  docs/installation/pki/packetfence.asciidoc
  go/caddy/pfpki/models/models.go
  go/caddy/pfpki/scep/scep.go
  go/go.mod
  go/go.sum
  t/venom/test_suites/nodes/wired_dot1x_eap_tls/run_sscep_on_node01.yml
  t/venom/test_suites/wired_dot1x_eap_tls_manual/TESTSUITE.md
  t/venom/test_suites/wired_dot1x_eap_tls_scep/05_create_pki.yml
  t/venom/test_suites/wired_dot1x_eap_tls_scep/95_check_autoregister_node.yml
  t/venom/test_suites/wired_dot1x_eap_tls_scep/TESTSUITE.md
  t/venom/vars/all.yml
Labels: Type: Bug, Type: Feature / Enhancement, Status: For review, Priority: High

#6771 OpenVPN and Generic VPN switch module
  docs/network/vpn_configuration.asciidoc
  lib/pf/Switch/GenericVPN.pm
  lib/pf/Switch/OpenVPN.pm
Labels: Type: Feature / Enhancement, Status: For review

#6815 Feature/mariadb haproxy timeout
  conf/documentation.conf
  conf/haproxy-db.conf.example
  conf/mariadb/mariadb.conf.tt.example
  conf/pf.conf.defaults
  html/pfappserver/root/src/views/Configuration/database/advanced/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/database/advanced/_components/index.js
  lib/pf/cmd/pf/generatemariadbconfig.pm
  lib/pf/services/manager/haproxy_db.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#6752 Feature/kandji
  docs/installation/integrating_provisioning_agents.asciidoc
  docs/installation/provisioner/kandji.asciidoc
  html/captive-portal/templates/provisioner/kandji.html
  html/pfappserver/lib/pfappserver/Form/Config/Provisioning/kandji.pm
  html/pfappserver/root/src/views/Configuration/provisioners/_components/FormTypeKandji.vue
  html/pfappserver/root/src/views/Configuration/provisioners/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/provisioners/_components/index.js
  html/pfappserver/root/src/views/Configuration/provisioners/config.js
  lib/pf/UnifiedApi/Controller/Config/Provisionings.pm
  lib/pf/iptables.pm
  lib/pf/provisioner/kandji.pm
Labels: Status: For review

#6727 Ubiquiti EdgeSwitch: set NAS-Port-Type to virtual when undef
  lib/pf/Switch/Ubiquiti/EdgeSwitch.pm
Labels: Status: For review

#6762 feature/pfcron-test-switch_cache_lldpLocalPort_description
  lib/pf/pfcron/task/switch_cache_lldpLocalPort_description.pm
  t/data/switches.conf
  t/unittest/pfconfig/cached_hash.t
  t/unittest/pfcron/task/switch_cache_lldpLocalPort_description.t
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#6763 feature/pfcron-test-ubiquiti_ap_mac_to_ip
  t/data/switches.conf
  t/mock_servers/ubiquiti_ap_mac_to_ip.pl
  t/unittest/pfconfig/cached_hash.t
  t/unittest/pfcron/task/ubiquiti_ap_mac_to_ip.t
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#6820 feature/switch_template_locationlog
  docs/developer/template_switches.asciidoc
  lib/pf/Switch/Template.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#6810 feature/update-mysql-driver
  go/go.mod
  go/go.sum
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#6755 feature/security-event-maintenance-tests
  go/cron/bandwidth_maintenance_test.go
  go/cron/cleanup_chi_database_cache_test.go
  go/cron/ip4log_cleanup_test.go
  go/cron/ip6log_cleanup_test.go
  go/cron/security_event_maintenance_test.go
  go/cron/window_batch_task_test.go
  lib/pf/security_event.pm
  t/data/roles.conf
  t/data/security_events.conf
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#6747 Improve speed of the node online query.
  db/pf-schema-X.Y.sql
  db/upgrade-X.X-X.Y.sql
  lib/pf/SQL/Abstract.pm
  lib/pf/UnifiedApi/Search.pm
  lib/pf/UnifiedApi/Search/Builder.pm
  lib/pf/UnifiedApi/Search/Builder/Nodes.pm
  t/unittest/UnifiedApi/Controller/Nodes-Search.t
  t/unittest/UnifiedApi/Search.t
  t/unittest/UnifiedApi/Search/Builder/Nodes.t
Labels: Type: Feature / Enhancement, Status: For review, Priority: Critical

#6718 Portal Message module without layout
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Message.pm
  html/captive-portal/templates/message.html
  html/pfappserver/lib/pfappserver/Form/Config/PortalModule/Message.pm
  html/pfappserver/root/src/views/Configuration/portalModules/_components/FormTypeMessage.vue
  html/pfappserver/root/src/views/Configuration/portalModules/_components/index.js
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium, Status: Tested and works

#6836 Add the ip6tables service
  .gitignore
  conf/documentation.conf
  conf/ip6tables-input-management.conf.inc.example
  conf/ip6tables.conf.example
  conf/pf.conf.defaults
  conf/systemd/packetfence-ip6tables.service
  debian/packetfence-ip6tables.service
  debian/packetfence.conffiles
  debian/rules
  lib/pf/ip6tables.pm
  lib/pf/services/manager/ip6tables.pm
  rpm/packetfence.spec
Labels: Status: Not ready

#6760 feature/pfcron-test-option82_query
  lib/pf/option82.pm
  t/data/pf.conf
  t/data/switches.conf
  t/pf/Switch/TestOption82.pm
  t/unittest/pfconfig/cached_hash.t
  t/unittest/pfcron/task/option82_query.t
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#6684 RADIUS Role attribute for VPN
  conf/switches.conf.defaults
  docs/api/spec/components/schemas/configswitchgroup.yaml
  docs/api/spec/openapi.json
  docs/api/spec/openapi.yaml
  docs/developer/template_switches.asciidoc
  html/pfappserver/lib/pfappserver/Form/Config/Switch.pm
  html/pfappserver/root/src/views/Configuration/switchGroups/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/switchGroups/_components/index.js
  html/pfappserver/root/src/views/Configuration/switches/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/switches/_components/index.js
  html/pfappserver/root/src/views/Configuration/switches/_composables/useForm.js
  lib/pf/ConfigStore/Switch.pm
  lib/pf/Switch.pm
  lib/pf/Switch/Fortinet/FortiGate.pm
  lib/pf/UnifiedApi/Controller/Config/Roles.pm
  lib/pf/UnifiedApi/Controller/Config/SwitchRole.pm
  lib/pf/UnifiedApi/Controller/Config/Switches.pm
  lib/pf/radius.pm
Labels: Type: Bug, Status: For review, Priority: High

#6743 feature/remove-populate_ntlm_redis_cache
  addons/upgrade/to-11.2-pfcron-populate_ntlm_redis_cache.pl
  conf/pfcron.conf.defaults
  docs/api/spec/components/schemas/configdomain.yaml
  go/cron/config.go
  go/cron/populate_ntlm_redis_cache.go
  html/pfappserver/lib/pfappserver/Form/Config/Domain.pm
  lib/pf/UnifiedApi/Controller/Config/MaintenanceTasks.pm
  lib/pf/api.pm
  lib/pf/cmd/pf/pfcron.pm
  lib/pf/cmd/pf/pfmon.pm
  t/unittest/UnifiedApi/GenerateSpec.t
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium

#6816 Venom: Test security event autoreg using DHCP fingerprint
  .gitlab-ci.yml
  t/venom/Makefile
  t/venom/scenarios/security_events/playbooks/rsync.yml
  t/venom/scenarios/security_events/playbooks/run_tests.yml
  t/venom/scenarios/security_events/site.yml
  t/venom/test_suites/security_event_autoreg/TESTSUITE.md
  t/venom/test_suites/security_event_autoreg/prepare/00_create_autoreg_security_event.yml
  t/venom/test_suites/security_event_autoreg/prepare/10_create_connection_profile.yml
  t/venom/test_suites/security_event_autoreg/prepare/15_enable_mac_auth_dot1x_int.yml
  t/venom/test_suites/security_event_autoreg/prepare/17_enable_dynamic_vlan.yml
  t/venom/test_suites/security_event_autoreg/prepare/20_commit_config.yml
  t/venom/test_suites/security_event_autoreg/teardown/05_disable_mac_auth_dot1x_int.yml
  t/venom/test_suites/security_event_autoreg/teardown/07_disable_dynamic_vlan.yml
  t/venom/test_suites/security_event_autoreg/teardown/10_commit_config.yml
  t/venom/test_suites/security_event_autoreg/teardown/15_delete_node01.yml
  t/venom/test_suites/security_event_autoreg/teardown/30_delete_connection_profile.yml
  t/venom/test_suites/security_event_autoreg/teardown/40_delete_security_event.yml
  t/venom/test_suites/security_event_autoreg/verify/run.yml
  t/venom/vars/all.yml
Labels: Status: For review

#6853 Allow to centralize the virtual IPs on the same server
  conf/documentation.conf
  conf/pf.conf.defaults
  html/pfappserver/root/src/views/Configuration/activeActive/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/activeActive/_components/index.js
  lib/pf/services/manager/keepalived.pm
Labels: Status: For review

#6714 Feature/admin cert san
  addons/packetfence-perl/dependencies.csv
  html/pfappserver/root/src/views/Configuration/sslCertificates/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/sslCertificates/_composables/useForm.js
  html/pfappserver/root/src/views/Configuration/sslCertificates/config.js
  html/pfappserver/root/src/views/Configuration/sslCertificates/schema.js
  lib/pf/ssl.pm
  t/unittest/ssl.t
Labels: Status: For review

#6858 fix/6613
  html/pfappserver/root/src/views/Configuration/sslCertificates/_components/TheForm.vue
Labels: Status: For review, Priority: High, javascript

#6834 mysql_probe service in go to control haproxy-db backend
  addons/packages/build-go.sh
  conf/documentation.conf
  conf/haproxy-db.conf.example
  conf/iptables.conf.example
  conf/mariadb/db-check.tt.example
  conf/pf.conf.defaults
  conf/systemd/packetfence-mysql-probe.service
  config.mk
  debian/packetfence-mysql-probe.service
  debian/rules
  docs/api/spec/components/schemas/configbase.yaml
  docs/api/spec/openapi.json
  docs/api/spec/openapi.yaml
  go/.gitignore
  go/cmd/mysql-probe/main.go
  go/galeraautofix/mariadb/mariadb.go
  go/pfconfigdriver/structs.go
  html/pfappserver/root/src/views/Configuration/activeActive/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/activeActive/_components/index.js
  html/pfappserver/root/src/views/Configuration/services/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/services/_components/index.js
  lib/pf/cmd/pf/generatemariadbconfig.pm
  lib/pf/cmd/pf/service.pm
  lib/pf/services/manager/haproxy_db.pm
  lib/pf/services/manager/mysql_probe.pm
  rpm/packetfence.spec
  t/TestUtils.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium

#6845 New OpenWiFi switch module
  lib/pf/Switch/OpenWifi.pm
Labels: Type: Feature / Enhancement, Status: For review, Type: Nice to have, Priority: Medium
