Repository inverse-inc/packetfence, pull requests merged in 2022-04, with the labels that each got.

#6955 fix/6952
  docs/developer/template_switches.asciidoc
  lib/pf/Switch/Template.pm
Labels: Type: Bug, Status: For review, Priority: Medium

#6953 fix(EXOS): disable SNMP query on CLI login
  lib/pf/Switch/Extreme/EXOS.pm
Labels: Status: For review

#6724 Fix the switch_group condition creation for securuty event triggers
  lib/pf/factory/condition/security_event.pm
  t/data/security_events.conf
  t/data/switches.conf
  t/unittest/factory/condition/security_event.t
  t/unittest/pfconfig/cached_hash.t
  t/unittest/security_events.t
Labels: Type: Bug, Status: For review
