Repository inverse-inc/packetfence, pull requests merged in 2022-08, with the labels that each got.

#7081 sd_notify ProxySQL Docker image
  conf/systemd/packetfence-proxysql.service
  containers/proxysql/Dockerfile
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#7089 Retreive the main PID of the process
  conf/systemd/packetfence-api-frontend.service
  conf/systemd/packetfence-config.service
  conf/systemd/packetfence-haproxy-admin.service
  conf/systemd/packetfence-haproxy-portal.service
  conf/systemd/packetfence-httpd.aaa.service
  conf/systemd/packetfence-httpd.admin_dispatcher.service
  conf/systemd/packetfence-httpd.dispatcher.service
  conf/systemd/packetfence-httpd.portal.service
  conf/systemd/packetfence-httpd.webservices.service
  conf/systemd/packetfence-pfconnector-client.service
  conf/systemd/packetfence-pfconnector-server.service
  conf/systemd/packetfence-pfcron.service
  conf/systemd/packetfence-pfperl-api.service
  conf/systemd/packetfence-pfpki.service
  conf/systemd/packetfence-pfsso.service
  conf/systemd/packetfence-proxysql.service
  conf/systemd/packetfence-radiusd-acct.service
  conf/systemd/packetfence-radiusd-cli.service
  conf/systemd/packetfence-radiusd-load_balancer.service
  go/cmd/sdnotify-proxy/main.go
Labels: Status: For review, Priority: Critical

#7092 fix/6979
  go/caddy/pfpki/models/models.go
Labels: Priority: High

#7094 Nodes communications API
  go/caddy/api/api.go
  go/caddy/api/node.go
  go/common/collector_endpoint.go
  go/fbcollectorclient/client.go
  go/fbcollectorclient/client_test.go
  go/pfconfigdriver/structs.go
  lib/pfconfig/namespaces/config/FingerbankSettings.pm
Labels: Status: For review, Priority: High

#7084 use 100.64.0.1:0 instead of 0.0.0.0:0 so the containers can communicate with each other
  lib/pf/services/manager/haproxy_admin.pm
Labels: Priority: High

#7109 adjust proxysql config for when the DB is in read-only mode
  conf/proxysql.conf.example
Labels: Status: For review, Priority: High

#6855 Feature: UI Cluster Services
  html/pfappserver/root/src/components/AppNotificationToasts.vue
  html/pfappserver/root/src/components/new/BaseButtonService.vue
  html/pfappserver/root/src/store/index.js
  html/pfappserver/root/src/store/modules/cluster.js
  html/pfappserver/root/src/store/modules/pfqueue.js
  html/pfappserver/root/src/store/modules/services.js
  html/pfappserver/root/src/styles/_base.scss
  html/pfappserver/root/src/utils/api.js
  html/pfappserver/root/src/views/Configuration/bases/_store.js
  html/pfappserver/root/src/views/Configuration/domains/_store.js
  html/pfappserver/root/src/views/Configuration/pki/cas/_components/TheSearch.vue
  html/pfappserver/root/src/views/Configuration/pki/certs/_components/TheSearch.vue
  html/pfappserver/root/src/views/Configuration/pki/profiles/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/pki/profiles/_components/TheSearch.vue
  html/pfappserver/root/src/views/Configuration/pki/revokedCerts/_components/TheSearch.vue
  html/pfappserver/root/src/views/Configuration/portalModules/_components/PortalModule.vue
  html/pfappserver/root/src/views/Configuration/switches/_store.js
  html/pfappserver/root/src/views/Configurator/packetfence/_components/FormDatabase.vue
  html/pfappserver/root/src/views/Configurator/packetfence/_components/FormGeneral.vue
  html/pfappserver/root/src/views/Configurator/status/_components/TheStep.vue
  html/pfappserver/root/src/views/Status/_api/index.js
  html/pfappserver/root/src/views/Status/_router/index.js
  html/pfappserver/root/src/views/Status/_store/index.js
  html/pfappserver/root/src/views/Status/cluster/_components/TheView.vue
  html/pfappserver/root/src/views/Status/cluster/_router.js
  html/pfappserver/root/src/views/Status/dashboard/_components/TheView.vue
  html/pfappserver/root/src/views/Status/dashboard/_router.js
  html/pfappserver/root/src/views/Status/index.vue
  html/pfappserver/root/src/views/Status/services/_components/BaseButtonBulkActions.vue
  html/pfappserver/root/src/views/Status/services/_components/BaseService.vue
  html/pfappserver/root/src/views/Status/services/_components/TheView.vue
  html/pfappserver/root/src/views/Status/services/_components/ToggleServiceAlive.js
  html/pfappserver/root/src/views/Status/services/_components/ToggleServiceEnabled.js
  html/pfappserver/root/src/views/Status/services/_router.js
  html/pfappserver/root/src/views/Status/services/config.js
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller.pm
  lib/pf/UnifiedApi/Controller/Config.pm
  lib/pf/UnifiedApi/Controller/SystemServices.pm
Labels: Type: Feature / Enhancement, Status: For review

#7098 Use the full date and time for expiration of password
  lib/pf/password.pm
Labels: Priority: Medium

#6793 fix/6791
  lib/pf/ConfigStore/Switch.pm
  t/data/switches.conf
  t/unittest/UnifiedApi/Controller/Config/Switches.t
  t/unittest/pfconfig/cached_hash.t
Labels: Type: Bug, Status: For review, Priority: Critical

#7118 fix/7108
  conf/caddy-services/api.conf.example
  go/api-frontend/aaa/authentication.go
  go/api-frontend/aaa/db_token_backend.go
  go/api-frontend/aaa/mem_token_backend.go
  go/api-frontend/aaa/multi_token_backend.go
  go/api-frontend/aaa/redis_token_backend.go
  go/api-frontend/aaa/token_backend.go
  go/api-frontend/aaa/token_backend_factory.go
  go/api-frontend/aaa/token_backend_test.go
  go/caddy/api-aaa/api-aaa.go
Labels: Type: Bug, Status: For review, Priority: Critical

#7141 adjust the NAS-IP-Address in the RADIUS source
  docs/PacketFence_Upgrade_Guide.asciidoc
  html/pfappserver/lib/pfappserver/Form/Config/Source/RADIUS.pm
  html/pfappserver/root/src/views/Configuration/sources/_components/FormTypeRadius.vue
  html/pfappserver/root/src/views/Configuration/sources/_components/index.js
  lib/pf/Authentication/Source/RADIUSSource.pm
Labels: Status: For review

#7147 update api translations
  conf/I18N/api/en.po
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#7146 Update portal translations
  conf/locale/en/LC_MESSAGES/packetfence.po
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#7145 fix/7136
  conf/radiusd/auth.conf.example
  conf/radiusd/eduroam.conf.example
  lib/pf/constants/syslog.pm
Labels: Type: Bug, Status: For review, Priority: High

#7153 Fix/proxysql read only again
  bin/proxysql-read-only-handler.sh
  conf/proxysql.conf.example
  containers/proxysql/Dockerfile
  go/cmd/pfacct/radius.go
  lib/pf/services/manager/proxysql.pm
  rpm/packetfence.spec
Labels: Status: For review

#7152 Initial Linode IaaS and PacketFence Connector documentation
  docs/images/linode_firewall.png
  docs/images/linode_lb.png
  docs/installation/appendix.asciidoc
  docs/installation/installation.asciidoc
  docs/installation/linode/linode.asciidoc
Labels: Priority: High, Documentation

#7163 UI - Restart Protected Services
  html/pfappserver/root/src/store/modules/pfqueue.js
  html/pfappserver/root/src/views/Status/services/_components/BaseService.vue
  html/pfappserver/root/src/views/Status/services/_components/TheView.vue
  html/pfappserver/root/src/views/Status/services/config.js
Labels: Priority: Medium
