Repository inverse-inc/packetfence, pull requests merged in 2022-11, with the labels that each got.

#7333 Removed monitor on eduroam authentication source
  go/cmd/pfstats/main.go
  html/pfappserver/lib/pfappserver/Form/Config/Source/Eduroam.pm
  html/pfappserver/root/src/views/Configuration/sources/_components/FormTypeEduroam.vue
  lib/pf/Authentication/Source/EduroamSource.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium

#7338 Fix / Add sameorigin in haproxy admin for netdata
  lib/pf/services/manager/haproxy_admin.pm
Labels: Type: Bug, Status: For review, Priority: High

#7348 fix/fixpermission-containers
  containers/systemd-service
  packetfence.sudoers
Labels: Priority: High

#7361 fix/7360
  lib/pf/cmd/pf/service.pm
Labels: Type: Bug, Priority: Critical

#7353 Sysprep on ZEN installation
  ci/packer/zen/build.pkr.hcl
  ci/packer/zen/provisioners/inventory/group_vars/pfservers/rc_local.yml
  ci/packer/zen/provisioners/playbooks/set_rc_local.yml
  ci/packer/zen/provisioners/playbooks/sysprep.yml
  ci/packer/zen/provisioners/requirements.yml
  ci/packer/zen/provisioners/shell/sysprep-packetfence.sh
  ci/packer/zen/provisioners/site.yml
Labels: Status: For review

#7378 Run pfconfig container on shell runner to generate material
  .gitlab-ci.yml
  Makefile
  ci/lib/build/generate-material.sh
  ci/lib/build/start-pfconfig-in-container.sh
Labels: Status: For review

#7385 Create a kaniko-build image to build Docker images on other projects
  .gitlab-ci.yml
  containers/Makefile
  containers/kaniko-build/Dockerfile
  containers/kaniko_vars
  containers/kanikobuild
  containers/manage-images.sh
Labels: Status: For review, Priority: Medium
