Repository inverse-inc/packetfence, pull requests merged in 2022-02, with the labels that each got.

#6860 allow to manage devices (unregister) when reaching max nodes
  conf/profiles.conf.defaults
  html/captive-portal/lib/captiveportal/PacketFence/Controller/Status.pm
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Root.pm
  html/captive-portal/templates/max-nodes-reached.html
  html/captive-portal/templates/status.html
  html/pfappserver/lib/pfappserver/Form/Config/ProfileCommon.pm
  html/pfappserver/root/src/views/Configuration/connectionProfiles/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/connectionProfiles/_components/index.js
  lib/pf/Connection/Profile.pm
Labels: Status: For review

#6854 Allow to configure environment variables for the collector via the admin interface
  debian/control
  html/pfappserver/root/src/views/Configuration/fingerbank/generalSettings/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/fingerbank/generalSettings/_components/index.js
  lib/pf/ConfigStore/FingerbankSettings.pm
  rpm/packetfence.spec
Labels: Status: For review

#6761 Fixes #6147
  lib/pf/api.pm
  lib/pfconfig/namespaces/config/Pf.pm
Labels: Type: Bug, Status: For review, Priority: Medium

#6844 Fix/6827
  conf/pfcron.conf.defaults
  db/pf-schema-X.Y.sql
  db/upgrade-X.X-X.Y.sql
  docs/PacketFence_Upgrade_Guide.asciidoc
  go/caddy/pfpki/handlers/handlers.go
  go/caddy/pfpki/models/models.go
  go/caddy/pfpki/ocspresponder/ocspresponder.go
  go/caddy/pfpki/pfpki.go
  go/caddy/pfpki/scep/scep.go
  go/cron/config.go
  go/cron/pki_certificates_check.go
  go/go.mod
  go/go.sum
  html/captive-portal/templates/emails/emails-renewal_certificate.html
  html/captive-portal/templates/emails/emails-renewal_certificate.mjml
  html/pfappserver/lib/pfappserver/Form/Config/Pfcron/pki_certificates_check.pm
  html/pfappserver/root/src/views/Configuration/pki/profiles/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/pki/profiles/_components/index.js
  html/pfappserver/root/src/views/Configuration/pki/profiles/_composables/useCollection.js
  html/pfappserver/root/src/views/Configuration/pki/profiles/schema.js
  lib/pf/UnifiedApi/Controller/Config/MaintenanceTasks.pm
  lib/pf/cmd/pf/pfcron.pm
  lib/pf/cmd/pf/pfmon.pm
  t/venom/vars/all.yml
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#6861 feature/go-admin-audit-api
  go/admin_api_audit_log/db.go
  go/admin_api_audit_log/db_test.go
  go/admin_api_audit_log/mask_secrets.go
  go/admin_api_audit_log/mask_secrets_test.go
  go/caddy/pfpki/handlers/handlers.go
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#6785 feature/pfcron-test-fingerbank_data_update
  t/data/fingerbank.db
  t/data/pfcron-test.conf.test
  t/ini_cmd.pl
  t/mock_servers/fingerbank.pl
  t/venom/test_suites/pfcron/01_job_was_ran.yml
  t/venom/vars/all.yml
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#6846 add unit tests for addons/functions/
  addons/functions/configuration.functions
  addons/functions/helpers.functions
  addons/vagrant/inventory/group_vars/pfservers/packetfence_install.yml
  addons/vagrant/inventory/group_vars/standalones/venom_local_vars.yml
  addons/vagrant/inventory/hosts
  debian/rules
  rpm/packetfence-test.spec
  t/addons-functions/.gitignore
  t/addons-functions/Makefile
  t/addons-functions/README.md
  t/addons-functions/configuration.tests
  t/addons-functions/helpers.tests
  t/addons-functions/run-all.tests
  t/addons-functions/vars.tests.ci
  t/addons-functions/vars.tests.example
  t/venom/scenarios/unit_tests/playbooks/run_tests.yml
  t/venom/test_suites/unit_tests/addons_functions_tests.yml
Labels: Status: For review

#6874 Disable vulnerable ciphers in HAProxy configuration
  conf/haproxy-admin.conf.example
  conf/haproxy-portal.conf.example
Labels: Status: For review

#6869 packefence-perl enhancements
  addons/packetfence-perl/README.md
  addons/packetfence-perl/dependencies.csv
  addons/packetfence-perl/get_modules_installed.pl
  addons/packetfence-perl/install_cpan.sh
Labels: Status: For review

#6856 Fix/6830 v11.1
  go/cmd/pfacct/pfacct.go
  go/cmd/pfacct/radius.go
  go/cmd/pfacct/radius_bandwidth_cache_test.go
  go/cron/bandwidth_maintenance.go
  go/cron/bandwidth_maintenance_test.go
  go/cron/batch.go
  go/cron/config.go
  go/cron/noop.go
  go/cron/window_batch_task_test.go
  lib/pfconfig/namespaces/config/Cron.pm
Labels: Type: Bug

#6803 Feature/debian installer
  .gitlab-ci.yml
  ci/debian-installer/.gitignore
  ci/debian-installer/Makefile
  ci/debian-installer/build-and-upload.sh
  ci/debian-installer/create-debian-installer-docker.sh
  ci/debian-installer/create-debian-installer.sh
  ci/debian-installer/grub.cfg
  ci/debian-installer/gtk.cfg
  ci/debian-installer/preseed.cfg.tmpl
  docs/installation/installation.asciidoc
Labels: Status: For review

#6865 Fixes #5948 Validate email address on TLS Enrollment
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/TLSEnrollment.pm
Labels: Type: Bug, Status: For review, Priority: Medium

#6886 fix/6882
  html/pfappserver/root/src/utils/yup.js
  html/pfappserver/root/src/views/Configuration/sources/_components/BaseFormGroupDomains.js
  html/pfappserver/root/src/views/Configuration/sources/_components/FormTypeSponsorEmail.vue
  html/pfappserver/root/src/views/Configuration/sources/_components/index.js
  html/pfappserver/root/src/views/Configuration/sources/_store.js
  html/pfappserver/root/src/views/Configuration/sources/config.js
  html/pfappserver/root/src/views/Configuration/sources/schema.js
Labels: Type: Bug, Priority: High

#6871 fix/6862
  html/pfappserver/root/src/components/new/BaseInputGroup.vue
  html/pfappserver/root/src/components/new/BaseInputGroupDate.vue
  html/pfappserver/root/src/composables/useInput.js
  html/pfappserver/root/src/globals/pfActions.js
Labels: Status: For review

#6911 Updated paypal documentation and screenshots
  docs/images/billing/paypal-access-sandbox-profile.png
  docs/images/billing/paypal-change-password.png
  docs/images/billing/paypal-encrypted-payment.png
  docs/images/billing/paypal-website-payment.png
  docs/images/billing/paypal-website-payment2.png
  docs/images/billing/paypal-website-payment3.png
  docs/installation/authentication_mechanisms.asciidoc
Labels: Status: For review, Priority: High, Documentation

#6912 Stripe integration update
  docs/images/billing/stripe-add-endpoint.png
  docs/images/billing/stripe-api-keys.png
  docs/images/billing/stripe-plan.png
  docs/images/billing/stripe-product-detail.png
  docs/images/billing/stripe-webhook.png
  docs/installation/authentication_mechanisms.asciidoc
Labels: Status: For review, Priority: High, Documentation
