Repository inverse-inc/packetfence, pull requests merged in 2022-10, with the labels that each got.

#7242 Import adjustments
  addons/full-import/import.sh
  addons/functions/configuration.functions
  addons/functions/database.functions
  docs/installation/export_import_mechanism.asciidoc
Labels: Status: For review, Priority: Medium

#6970 Sync iptables-input config and ip6table* files across cluster
  addons/full-import/find-extra-files.pl
  docs/installation/export_import_mechanism.asciidoc
  lib/pf/constants/cluster.pm
  lib/pf/file_paths.pm
Labels: Status: For review

#7241 Fix source IP for pfconnector-remote deauth
  lib/pf/Switch.pm
  lib/pf/Switch/AeroHIVE.pm
  lib/pf/Switch/Alcatel.pm
  lib/pf/Switch/Aruba.pm
  lib/pf/Switch/Aruba/2930M.pm
  lib/pf/Switch/Aruba/CX.pm
  lib/pf/Switch/Aruba/Instant_Access.pm
  lib/pf/Switch/ArubaSwitch.pm
  lib/pf/Switch/Avaya.pm
  lib/pf/Switch/Cisco.pm
  lib/pf/Switch/Cisco/ASA.pm
  lib/pf/Switch/Cisco/Aironet_1600.pm
  lib/pf/Switch/Cisco/Catalyst_2960.pm
  lib/pf/Switch/Cisco/WLC.pm
  lib/pf/Switch/Dell/N1500.pm
  lib/pf/Switch/Enterasys/V2110.pm
  lib/pf/Switch/Hostapd.pm
  lib/pf/Switch/Huawei.pm
  lib/pf/Switch/Juniper/EX2200.pm
  lib/pf/Switch/Juniper/EX2200_v15.pm
  lib/pf/Switch/Juniper/EX2300.pm
  lib/pf/Switch/Meraki/MR_v2.pm
  lib/pf/Switch/Mikrotik.pm
  lib/pf/Switch/Mojo.pm
  lib/pf/Switch/Pica8.pm
  lib/pf/Switch/Ruckus/SmartZone.pm
  lib/pf/Switch/Template.pm
  lib/pf/Switch/Ubiquiti/Unifi.pm
  lib/pf/Switch/Xirrus.pm
  lib/pf/util/radius.pm
Labels: Status: For review

#7232 Debian package for PacketFence Connector
  Makefile
  addons/pfconnector/configure.sh
  addons/pfconnector/install.sh
  addons/pfconnector/systemd/packetfence-pfconnector-remote.logrotate-drop-in.service
  addons/pfconnector/systemd/packetfence-pfconnector-remote.service
  addons/pfconnector/upgrade/remove-unpackaged-pfconnector.sh
  config.mk
  debian/control
  debian/packetfence-pfconnector-remote.conffiles
  debian/packetfence-pfconnector-remote.logrotate
  debian/packetfence-pfconnector-remote.postinst
  debian/rules
  docs/installation/linode/linode.asciidoc
Labels: Status: For review, Priority: Medium

#7160 fix/3768
  lib/pf/Authentication/Source.pm
  t/data/authentication.conf
  t/unittest/authentication.t
Labels: Type: Bug, Status: For review, Priority: Low

#7276 Cancel tests if space is limited on runners
  t/venom/test-wrapper.sh
Labels: Status: For review

#7099 feature/remove-savedsearch
  db/pf-schema-X.Y.sql
  db/upgrade-X.X-X.Y.sql
Labels: Priority: Low

#7288 Allow to store logo in profile-templates directory - part 2
  addons/upgrade/move-logos-to-profile-templates.pl
Labels: Status: In progress

#7291 fix/7283
  db/upgrade-11.2-12.0.sql
Labels: Type: Bug, Priority: Critical

#7267 Instructions to override CSS definitions on captive portal
  docs/developer/customizing_packetfence.asciidoc
  docs/installation/advanced_topics.asciidoc
Labels: Status: For review

#7210 Captive Portal - Deprecate jQuery
  html/captive-portal/content/autosubmit.js
  html/captive-portal/content/billing/authorizenet.js
  html/captive-portal/content/billing/stripe.js
  html/captive-portal/content/captiveportal.js
  html/captive-portal/content/guest-management.js
  html/captive-portal/content/provisioner/mobileconfig.js
  html/captive-portal/content/provisioner/sepm.js
  html/captive-portal/content/release.js
  html/captive-portal/content/scan.js
  html/captive-portal/content/sslinspection.js
  html/captive-portal/content/status.js
  html/captive-portal/content/timerbar.js
  html/captive-portal/content/waiting.js
  html/captive-portal/templates/layout.html
  html/common/aup-autosubmit.js
  html/common/autosubmit.js
  html/common/jquery-1.11.3.min.js
  html/common/jquery-shim.js
  html/common/jquery.qrcode.min.js
  html/common/pf.js
  html/common/prototype.js
  html/common/qrcode.js
  html/common/qrcode.min.js
Labels: Priority: High

#7085 Show the PSK is the status page
  html/captive-portal/lib/captiveportal/PacketFence/Controller/Status.pm
  html/captive-portal/templates/status.html
  html/pfappserver/lib/pfappserver/Form/Config/SelfService.pm
  html/pfappserver/root/src/views/Configuration/selfServices/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/selfServices/_components/index.js
Labels: Status: For review, Priority: High

#7183 Create pfconfig.conf on post installation (remove pfconfig.conf.example)
  addons/upgrade/restore-pfconfig-conf.sh
  conf/pfconfig.conf.example
  containers/radiusd/Dockerfile
  debian/packetfence-config.conffiles
  debian/packetfence-config.postinst
  debian/rules
  rpm/packetfence.spec
Labels: Status: For review, Priority: High

#7306 Remove ip*tables.conf from config files
  conf/ip6tables.conf.example
  conf/iptables.conf.example
  debian/packetfence.conffiles
  rpm/packetfence.spec
Labels: Status: For review, Priority: Medium

#7311 Instructions to upload logo for 12.0.0 and 12.1.0
  docs/developer/customizing_packetfence.asciidoc
Labels: Status: For review, Priority: Medium

#7314 Feature/openwifi dpsk
  go/go.sum
  lib/pf/Switch/OpenWiFi.pm
  lib/pf/util/combined_dictionary
  lib/pf/util/wpa.pm
  raddb/dictionary
  raddb/dictionary.freeradius.evs5
  raddb/dictionary.pfacct
Labels: Priority: Medium

#7091 Handle WebAuth on Extreme Controller without web form
  docs/network/networkdevice/extreme_networks_wireless.asciidoc
  docs/network/wireless_controllers_and_access_point_configuration.asciidoc
  lib/pf/Switch/Extreme/AP.pm
  lib/pf/web/constants.pm
Labels: Status: For review, Priority: Medium

#7285 feature/file_upload_api
  .gitignore
  debian/rules
  html/pfappserver/lib/pfappserver/Form/Config/PKI_Provider/packetfence_local.pm
  html/pfappserver/lib/pfappserver/Form/Config/PKI_Provider/packetfence_pki.pm
  html/pfappserver/lib/pfappserver/Form/Config/PKI_Provider/scep.pm
  html/pfappserver/lib/pfappserver/Form/Config/Provisioning/mobileconfig.pm
  html/pfappserver/lib/pfappserver/Form/Config/Source.pm
  html/pfappserver/lib/pfappserver/Form/Config/Source/Htpasswd.pm
  html/pfappserver/lib/pfappserver/Form/Config/Source/LDAP.pm
  html/pfappserver/lib/pfappserver/Form/Config/Source/Paypal.pm
  html/pfappserver/lib/pfappserver/Form/Config/Source/SAML.pm
  html/pfappserver/lib/pfappserver/Form/Field/PathUpload.pm
  html/pfappserver/root/src/components/new/BaseButtonUpload.vue
  html/pfappserver/root/src/components/new/BaseFormGroupChosen.vue
  html/pfappserver/root/src/components/new/BaseFormGroupFileUpload.vue
  html/pfappserver/root/src/components/new/BaseFormGroupInput.vue
  html/pfappserver/root/src/components/new/BaseInputGroup.vue
  html/pfappserver/root/src/components/new/BaseSearchInputBasic.vue
  html/pfappserver/root/src/components/new/index.js
  html/pfappserver/root/src/styles/_buttons.scss
  html/pfappserver/root/src/styles/_input-group.scss
  html/pfappserver/root/src/utils/api.js
  html/pfappserver/root/src/utils/strings.js
  html/pfappserver/root/src/views/Configuration/pkiProviders/_components/FormTypePacketfenceLocal.vue
  html/pfappserver/root/src/views/Configuration/pkiProviders/_components/FormTypePacketfencePki.vue
  html/pfappserver/root/src/views/Configuration/pkiProviders/_components/FormTypeScep.vue
  html/pfappserver/root/src/views/Configuration/pkiProviders/_components/index.js
  html/pfappserver/root/src/views/Configuration/pkiProviders/_store.js
  html/pfappserver/root/src/views/Configuration/pkiProviders/schema.js
  html/pfappserver/root/src/views/Configuration/provisioners/_components/FormTypeAndroid.vue
  html/pfappserver/root/src/views/Configuration/provisioners/_components/FormTypeMobileconfig.vue
  html/pfappserver/root/src/views/Configuration/provisioners/_components/FormTypeWindows.vue
  html/pfappserver/root/src/views/Configuration/provisioners/_components/index.js
  html/pfappserver/root/src/views/Configuration/provisioners/_store.js
  html/pfappserver/root/src/views/Configuration/provisioners/schema.js
  html/pfappserver/root/src/views/Configuration/sources/_components/FormTypeHtpasswd.vue
  html/pfappserver/root/src/views/Configuration/sources/_components/FormTypeLdap.vue
  html/pfappserver/root/src/views/Configuration/sources/_components/FormTypeOpenId.vue
  html/pfappserver/root/src/views/Configuration/sources/_components/FormTypePaypal.vue
  html/pfappserver/root/src/views/Configuration/sources/_components/FormTypeSaml.vue
  html/pfappserver/root/src/views/Configuration/sources/_components/index.js
  html/pfappserver/root/src/views/Configuration/sources/_store.js
  html/pfappserver/root/src/views/Configuration/sources/schema.js
  lib/pf/UnifiedApi/Controller/Config.pm
  lib/pf/UnifiedApi/Controller/Config/ConnectionProfiles.pm
  lib/pf/UnifiedApi/GenerateSpec.pm
  lib/pf/cmd/pf/fixpermissions.pm
  lib/pf/constants/user.pm
  lib/pf/file_paths.pm
  lib/pf/util.pm
  rpm/packetfence.spec
  t/unittest/UnifiedApi/Controller/Config/OPTIONS.t
  t/unittest/UnifiedApi/Controller/Config/Sources/Htpasswd.t
  t/unittest/UnifiedApi/Controller/Config/Sources/SAML.t
Labels: Priority: High

#7313 fix/6385
  db/pf-schema-X.Y.sql
  db/upgrade-X.X-X.Y.sql
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Sponsor.pm
  html/pfappserver/root/src/views/Users/_components/TheFormUpdate.vue
  html/pfappserver/root/src/views/Users/_components/index.js
  html/pfappserver/root/src/views/Users/_config/index.js
  html/pfappserver/root/src/views/Users/_search.js
  lib/pf/dal/_person.pm
Labels: Priority: Medium

#7287 Feature/improve mfa
  html/pfappserver/lib/pfappserver/Form/Config/Mfa/Akamai.pm
  lib/pf/mfa/Akamai.pm
  lib/pf/radius.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium

#7222 Api integration updated for Intune scep
  docs/images/Intune-7-API-Permissions.png
  docs/installation/pki/packetfence.asciidoc
  go/caddy/pfpki/cloud/intune.go
  go/go.mod
  go/go.sum
Labels: Type: Bug, Type: Feature / Enhancement, Status: For review, Priority: High

#7324 Upgrade to golang 1.18.7
  config.mk
Labels: Priority: High, Status: Fix confirmed

#7286 Fixes VPN attribute not returned each time
  addons/upgrade/to-12.1-move-rolebyname-to-vpnbyname-fortigate.pl
  lib/pf/Switch.pm
  lib/pf/Switch/Fortinet/FortiGate.pm
  lib/pf/radius.pm
  lib/pfconfig/namespaces/config/Switch.pm
Labels: Type: Bug, Status: For review, Priority: Medium

#7326 Feature/analytics conscent
  conf/documentation.conf
  conf/pf.conf.defaults
  html/pfappserver/root/.env
  html/pfappserver/root/src/store/modules/analytics.js
  html/pfappserver/root/src/store/modules/system.js
  html/pfappserver/root/src/views/Configuration/bases/_store.js
  html/pfappserver/root/src/views/Configuration/clouds/_router.js
  html/pfappserver/root/src/views/Configuration/clouds/_store.js
  html/pfappserver/root/src/views/Configuration/clouds/config.js
  html/pfappserver/root/src/views/Configuration/eventLoggers/_router.js
  html/pfappserver/root/src/views/Configuration/eventLoggers/_store.js
  html/pfappserver/root/src/views/Configuration/eventLoggers/config.js
  html/pfappserver/root/src/views/Configuration/firewalls/_router.js
  html/pfappserver/root/src/views/Configuration/firewalls/_store.js
  html/pfappserver/root/src/views/Configuration/firewalls/config.js
  html/pfappserver/root/src/views/Configuration/general/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/general/_components/index.js
  html/pfappserver/root/src/views/Configuration/maintenanceTasks/_router.js
  html/pfappserver/root/src/views/Configuration/maintenanceTasks/_store.js
  html/pfappserver/root/src/views/Configuration/maintenanceTasks/config.js
  html/pfappserver/root/src/views/Configuration/mfas/_router.js
  html/pfappserver/root/src/views/Configuration/mfas/_store.js
  html/pfappserver/root/src/views/Configuration/mfas/config.js
  html/pfappserver/root/src/views/Configuration/pkiProviders/_router.js
  html/pfappserver/root/src/views/Configuration/pkiProviders/_store.js
  html/pfappserver/root/src/views/Configuration/pkiProviders/config.js
  html/pfappserver/root/src/views/Configuration/portalModules/_router.js
  html/pfappserver/root/src/views/Configuration/portalModules/_store.js
  html/pfappserver/root/src/views/Configuration/portalModules/config.js
  html/pfappserver/root/src/views/Configuration/provisioners/_router.js
  html/pfappserver/root/src/views/Configuration/provisioners/_store.js
  html/pfappserver/root/src/views/Configuration/provisioners/config.js
  html/pfappserver/root/src/views/Configuration/scanEngines/_router.js
  html/pfappserver/root/src/views/Configuration/scanEngines/_store.js
  html/pfappserver/root/src/views/Configuration/scanEngines/config.js
  html/pfappserver/root/src/views/Configuration/securityEvents/_router.js
  html/pfappserver/root/src/views/Configuration/securityEvents/_store.js
  html/pfappserver/root/src/views/Configuration/securityEvents/config.js
  html/pfappserver/root/src/views/Configuration/sources/_router.js
  html/pfappserver/root/src/views/Configuration/sources/_store.js
  html/pfappserver/root/src/views/Configuration/sources/config.js
  html/pfappserver/root/src/views/Configuration/sslCertificates/_router.js
  html/pfappserver/root/src/views/Configuration/sslCertificates/_store.js
  html/pfappserver/root/src/views/Configuration/sslCertificates/config.js
  html/pfappserver/root/src/views/Configuration/syslogForwarders/_router.js
  html/pfappserver/root/src/views/Configuration/syslogForwarders/_store.js
  html/pfappserver/root/src/views/Configuration/syslogForwarders/config.js
  html/pfappserver/root/src/views/Configuration/syslogParsers/_router.js
  html/pfappserver/root/src/views/Configuration/syslogParsers/_store.js
  html/pfappserver/root/src/views/Configuration/syslogParsers/config.js
  html/pfappserver/root/src/views/Configurator/packetfence/_components/FormGeneral.vue
  html/pfappserver/root/src/views/Reports/_router/index.js
  html/pfappserver/root/src/views/Reports/_store/index.js
  html/pfappserver/root/src/views/Reports/config.js
  lib/pf/UnifiedApi/Controller/SystemSummary.pm
Labels: Priority: High

#6401 Use new radius request attribute to identify vpn access and modified valid_mac to reject ip address (detect 123.456.789.123 as 12:34:56:78:91:23)
  lib/pf/Switch/Fortinet/FortiGate.pm
  lib/pf/util.pm
Labels: Type: Bug, Status: For review, Priority: Medium

#7154 fix/3400
  html/pfappserver/root/src/composables/usePreference.js
  html/pfappserver/root/src/globals/pfFormatters.js
  html/pfappserver/root/src/store/modules/preferences.js
  html/pfappserver/root/src/views/Nodes/_components/TheSearch.vue
  html/pfappserver/root/src/views/Nodes/_router/index.js
  html/pfappserver/root/src/views/Nodes/_search.js
  html/pfappserver/root/src/views/Status/network_threats/_components/TheView.vue
  html/pfappserver/root/src/views/Status/network_threats/_router.js
  lib/pf/UnifiedApi/Search/Builder.pm
  lib/pf/UnifiedApi/Search/Builder/Nodes.pm
  lib/pf/security_event.pm
  t/unittest/UnifiedApi/Search/Builder/Nodes.t
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium
