Repository inverse-inc/packetfence, pull requests merged in 2023-03, with the labels that each got.

#7560 Feature/out dacl
  html/pfappserver/lib/pfappserver/Form/Config/Switch.pm
  html/pfappserver/lib/pfappserver/Util/ACLs.pm
  lib/pf/Switch.pm
  lib/pf/Switch/Cisco.pm
  lib/pf/Switch/Cisco/ASA.pm
  lib/pf/Switch/Cisco/Catalyst_2960.pm
  lib/pf/Switch/Dell/N1500.pm
  lib/pf/UnifiedApi/Controller/Nodes.pm
  lib/pf/UnifiedApi/Controller/Users/Password.pm
  t/hardware-snmp-objects.t
  t/unittest/UnifiedApi/Controller/Config/Roles.t
  t/unittest/UnifiedApi/Controller/Config/Switches.t
  t/unittest/UnifiedApi/Controller/Nodes.t
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#7569 ZEN: Call make in raddb/certs only once
  ci/packer/zen/provisioners/inventory/group_vars/pfservers/rc_local.yml
Labels: Status: For review

#7564 Disable DNS lookup made by sudo
  debian/packetfence.conffiles
  debian/rules
  disable-dns-lookup.sudoers
  rpm/packetfence.spec
Labels: Status: For review

#7574 Don't overwrite host when DOCKER_NETWORK_IS_HOST is set
  lib/pf/connector.pm
  sbin/pfperl-api-docker-wrapper
Labels: Priority: Critical

#7581 Fix the logic for update ifDesc
  lib/pf/Switch/Extreme/EXOS.pm
Labels: Priority: Critical

#7590 tests: delete/recreate iptable rule to prevent issue during sso_radius test suite
  t/venom/test_suites/wired_dot1x_eap_peap_firewall_sso_radius/30_delete_iptable_rule.yml
  t/venom/test_suites/wired_dot1x_eap_peap_firewall_sso_radius/teardown/96_restart_iptables.yml
Labels: Status: For review

#7591 tests: cancel jobs and halt VM differently
  .gitlab-ci.yml
  ci/lib/check/run-pipeline-if-necessary.sh
  ci/lib/test/cancel-pending-jobs.sh
  ci/lib/test/clean-test-environment.sh
Labels: Status: For review
