Repository inverse-inc/packetfence, pull requests merged in 2023-06, with the labels that each got.

#7654 Allow to call a custom script from pfupdate to handle VIP in cloud environments
  NEWS.asciidoc
  bin/cluster/pfupdate
  conf/documentation.conf
  conf/pf.conf.defaults
  html/pfappserver/root/src/views/Configuration/advanced/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/advanced/_components/index.js
  lib/pf/services/manager/keepalived.pm
Labels: Status: For review, Priority: High

#7701 feature/remove-provisioner-config
  addons/upgrade/to-13.0-remove-provisioner.pl
Labels: Status: For review, Priority: High

#7350 UI e2e testing framework
  .gitlab-ci.yml
  addons/vagrant/inventory/group_vars/standalones/venom_local_vars.yml
  addons/vagrant/playbooks/get_logs.yml
  html/pfappserver/root/src/components/new/BaseFormGroupChosen.vue
  html/pfappserver/root/src/components/new/BaseFormGroupInput.vue
  html/pfappserver/root/src/components/new/BaseFormGroupInputDate.vue
  html/pfappserver/root/src/components/new/BaseFormGroupInputDateTime.vue
  html/pfappserver/root/src/components/new/BaseFormGroupInputMultiplier.vue
  html/pfappserver/root/src/components/new/BaseFormGroupInputPassword.vue
  html/pfappserver/root/src/components/new/BaseFormGroupInputPasswordGenerator.vue
  html/pfappserver/root/src/components/new/BaseFormGroupInputPasswordTest.vue
  html/pfappserver/root/src/components/new/BaseFormGroupInputTest.vue
  html/pfappserver/root/src/components/new/BaseFormGroupToggle.vue
  html/pfappserver/root/src/components/new/BaseInput.vue
  html/pfappserver/root/src/components/new/BaseInputChosen.vue
  html/pfappserver/root/src/components/new/BaseInputGroupDate.vue
  html/pfappserver/root/src/components/new/BaseInputGroupDateTime.vue
  html/pfappserver/root/src/components/new/BaseInputGroupPassword.vue
  html/pfappserver/root/src/views/Configurator/packetfence/_components/FormAdministrator.vue
  html/pfappserver/root/src/views/Configurator/packetfence/_components/FormAlerting.vue
  html/pfappserver/root/src/views/Configurator/packetfence/_components/FormDatabase.vue
  html/pfappserver/root/src/views/Configurator/packetfence/_components/FormGeneral.vue
  html/pfappserver/root/src/views/Configurator/status/_components/FormStatus.vue
  t/html/pfappserver/.editorconfig
  t/html/pfappserver/.gitignore
  t/html/pfappserver/.local_env
  t/html/pfappserver/Makefile
  t/html/pfappserver/README.md
  t/html/pfappserver/config/collections/domains.js
  t/html/pfappserver/config/collections/index.js
  t/html/pfappserver/config/collections/roles.js
  t/html/pfappserver/cypress/config/cypress.config-configuration.js
  t/html/pfappserver/cypress/config/cypress.config-configurator.js
  t/html/pfappserver/cypress/config/cypress.config.js
  t/html/pfappserver/cypress/fixtures/configurator.js
  t/html/pfappserver/cypress/specs/e2e/00-commands.cy.js
  t/html/pfappserver/cypress/specs/e2e/00-configurator/01-configurator.cy.js
  t/html/pfappserver/cypress/specs/e2e/90-configuration/01-login.cy.js
  t/html/pfappserver/cypress/specs/e2e/90-configuration/02-locale.cy.js
  t/html/pfappserver/cypress/specs/e2e/90-configuration/03-collections.cy.js
  t/html/pfappserver/cypress/specs/e2e/90-configuration/40-policies-and-access-control/01-roles.cy.js
  t/html/pfappserver/cypress/support/commands.js
  t/html/pfappserver/cypress/support/e2e.js
  t/html/pfappserver/cypress/support/filter.js
  t/html/pfappserver/package-lock.json
  t/html/pfappserver/package.json
  t/html/pfappserver/webpack.config.js
  t/venom/Makefile
  t/venom/lib/html_e2e.yml
  t/venom/lib/html_e2e_project.yml
  t/venom/scenarios/pfappserver/playbooks/configure.yml
  t/venom/scenarios/pfappserver/playbooks/localdev.yml
  t/venom/scenarios/pfappserver/playbooks/rsync.yml
  t/venom/scenarios/pfappserver/playbooks/run_tests.yml
  t/venom/scenarios/pfappserver/site.yml
  t/venom/test_suites/pfappserver_configurator/TESTSUITE.md
  t/venom/test_suites/pfappserver_configurator/run_e2e.yml
  t/venom/vars/all.yml
Labels: Status: For review, Status: In progress

#7686 IBM provisioner removal
  html/captive-portal/templates/provisioner/ibm.html
  html/pfappserver/lib/pfappserver/Form/Config/Provisioning/ibm.pm
  html/pfappserver/root/src/views/Configuration/provisioners/_components/FormTypeIbm.vue
  html/pfappserver/root/src/views/Configuration/provisioners/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/provisioners/config.js
  lib/pf/UnifiedApi/Controller/Config/Provisionings.pm
  lib/pf/provisioner/ibm.pm
Labels: Status: For review

#7699 feature/remove-servicenow
  html/captive-portal/templates/provisioner/servicenow.html
  html/pfappserver/lib/pfappserver/Form/Config/Provisioning/servicenow.pm
  html/pfappserver/root/src/views/Configuration/provisioners/_components/FormTypeServicenow.vue
  html/pfappserver/root/src/views/Configuration/provisioners/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/provisioners/config.js
  lib/pf/UnifiedApi/Controller/Config/Provisionings.pm
  lib/pf/provisioner/servicenow.pm
Labels: Status: For review, Priority: High

#7700 feature/remove-symantec-provisioner
  html/captive-portal/templates/provisioner/symantec.html
  html/pfappserver/lib/pfappserver/Form/Config/Provisioning/symantec.pm
  html/pfappserver/root/src/views/Configuration/provisioners/_components/FormTypeSymantec.vue
  html/pfappserver/root/src/views/Configuration/provisioners/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/provisioners/config.js
  lib/pf/UnifiedApi/Controller/Config/Provisionings.pm
  lib/pf/provisioner/symantec.pm
  t/unittest/provisioner/symantec.t
Labels: Status: For review, Priority: High

#7716 remove Provisioner - OPSWAT
  docs/images/opswat-add-devices.png
  docs/images/opswat-add-guest-devices.png
  docs/images/opswat-compliance-config.png
  docs/images/opswat-critical-config.png
  docs/images/opswat-passthroughs.png
  docs/images/opswat-pf-config.png
  docs/images/opswat-portal.png
  docs/installation/integrating_provisioning_agents.asciidoc
  docs/installation/provisioner/opswat.asciidoc
  html/captive-portal/templates/provisioner/opswat.html
  html/pfappserver/lib/pfappserver/Form/Config/Provisioning/opswat.pm
  html/pfappserver/root/src/views/Configuration/provisioners/_components/FormTypeOpswat.vue
  html/pfappserver/root/src/views/Configuration/provisioners/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/provisioners/config.js
  lib/pf/UnifiedApi/Controller/Config/Provisionings.pm
  lib/pf/provisioner/opswat.pm
Labels: Status: For review

#7714 Docs: improve cluster troubleshooting section
  docs/cluster/troubleshooting_a_cluster.asciidoc
Labels: Status: For review

#7719 don't delete a node from pfdhcp if it is disabled
  lib/pf/node.pm
Labels: Status: For review, Priority: Medium

#7667 feature/remove-httpd-collector
  addons/upgrade/to-12.0-rename-log-files.pl
  conf/documentation.conf
  conf/httpd.conf.d/httpd.collector.tt.example
  conf/iptables.conf.example
  conf/log.conf.d/httpd.collector.conf.example
  conf/pf.conf.defaults
  conf/systemd/packetfence-httpd.collector.service
  debian/packetfence.conffiles
  debian/packetfence.preinst
  debian/patches/debianize.patch
  debian/rules
  docs/images/httpd_collector.png
  go/caddy/log-tailer/logmeta.go
  go/pfconfigdriver/structs.go
  html/pfappserver/root/src/views/Configuration/services/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/services/_components/index.js
  lib/pf/cmd/pf/service.pm
  lib/pf/constants/syslog.pm
  lib/pf/iptables.pm
  lib/pf/services/manager/httpd_collector.pm
  lib/pf/web/httpd.collector_modperl_require.pl
  rpm/packetfence.spec
Labels: Priority: High

#7666 feature/remove-tc-service
  conf/documentation.conf
  conf/pf.conf.defaults
  conf/systemd/packetfence-tc.service
  conf/traffic_shaping.conf.example
  debian/packetfence.conffiles
  debian/packetfence.preinst
  debian/patches/debianize.patch
  debian/rules
  docs/installation/enforcement/inline.asciidoc
  go/api-frontend/aaa/authorization.go
  html/pfappserver/lib/pfappserver/Form/Config/TrafficShaping.pm
  html/pfappserver/root/src/store/modules/config.js
  html/pfappserver/root/src/views/Configuration/_components/TheTabsNetworks.vue
  html/pfappserver/root/src/views/Configuration/index.vue
  html/pfappserver/root/src/views/Configuration/networks/_api.js
  html/pfappserver/root/src/views/Configuration/networks/_router.js
  html/pfappserver/root/src/views/Configuration/networks/trafficShapingPolicies/_api.js
  html/pfappserver/root/src/views/Configuration/networks/trafficShapingPolicies/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/networks/trafficShapingPolicies/_components/TheSearch.vue
  html/pfappserver/root/src/views/Configuration/networks/trafficShapingPolicies/_components/TheView.js
  html/pfappserver/root/src/views/Configuration/networks/trafficShapingPolicies/_components/index.js
  html/pfappserver/root/src/views/Configuration/networks/trafficShapingPolicies/_composables/useCollection.js
  html/pfappserver/root/src/views/Configuration/networks/trafficShapingPolicies/_router.js
  html/pfappserver/root/src/views/Configuration/networks/trafficShapingPolicies/_store.js
  html/pfappserver/root/src/views/Configuration/networks/trafficShapingPolicies/schema.js
  html/pfappserver/root/src/views/Configuration/roles/_components/TheSearch.vue
  html/pfappserver/root/src/views/Configuration/roles/_router.js
  html/pfappserver/root/src/views/Configuration/services/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/services/_components/index.js
  lib/pf/ConfigStore/TrafficShaping.pm
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config/TrafficShapingPolicies.pm
  lib/pf/api.pm
  lib/pf/cmd/pf/service.pm
  lib/pf/config/traffic_shaping.pm
  lib/pf/constants/admin_roles.pm
  lib/pf/file_paths.pm
  lib/pf/ipset.pm
  lib/pf/iptables.pm
  lib/pf/services/manager/tc.pm
  lib/pfconfig/namespaces/config/TrafficShaping.pm
  packetfence.sudoers
  rpm/packetfence.spec
  t/unittest/UnifiedApi/Controller/Config/TrafficShapingPolicies.t
Labels: Status: For review, Priority: High

#7710 feature/pfdhcp-optimize
  go/cmd/pfdhcp/keysoption.go
  go/cmd/pfdhcp/main.go
  go/cmd/pfdhcp/utils.go
  go/dhcp/pool/mysql.go
  go/dhcp/pool/mysql_bench_test.go
  go/dhcp/pool/mysql_test.go
Labels: Priority: High

#7477 fix/7471
  conf/stats.conf.defaults
Labels: Status: For review, Priority: Medium

#7620 fix/move-switch-reload-to-pfqueue
  lib/pf/ConfigStore/Switch.pm
  lib/pf/api.pm
Labels: Status: For review, Priority: High

#7596 feature/os-pick-port
  go/chisel/server/server_handler.go
  go/chisel/share/tunnel/tunnel_in_proxy.go
  go/chisel/share/tunnel/tunnel_in_proxy_udp.go
  go/go.mod
  go/go.sum
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#7707 feature/pfdns_audit_log_to_redis
  conf/pfcron.conf.defaults
  go/common/dns_audit_log.go
  go/cron/config.go
  go/cron/flush_dns_audit_log.go
  go/cron/flush_dns_audit_log_job_test.go
  go/plugin/coredns/pfdns/pfdns.go
  go/plugin/coredns/pfdns/setup.go
  go/redis_cache/client.go
  html/pfappserver/lib/pfappserver/Form/Config/Pfcron/flush_dns_audit_log.pm
Labels: Status: For review, Priority: High

#7692 Feature/remove Symantec Endpoint Protection Manager (SEPM)
  conf/I18N/api/en.po
  conf/I18N/api/fr.po
  conf/locale/nl/LC_MESSAGES/packetfence.po
  docs/images/sepm-add-client.png
  docs/images/sepm-app-config.png
  docs/images/sepm-content-config.png
  docs/images/sepm-export-location.png
  docs/images/sepm-pf-config.png
  docs/images/sepm-portal.png
  docs/installation/integrating_provisioning_agents.asciidoc
  docs/installation/provisioner/sepm.asciidoc
  html/captive-portal/templates/provisioner/sepm.html
  html/pfappserver/lib/pfappserver/Form/Config/Provisioning/sepm.pm
  html/pfappserver/lib/pfappserver/I18N/en.po
  html/pfappserver/lib/pfappserver/I18N/fr.po
  html/pfappserver/root/src/views/Configuration/provisioners/_components/FormTypeSepm.vue
  html/pfappserver/root/src/views/Configuration/provisioners/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/provisioners/config.js
  lib/pf/UnifiedApi/Controller/Config/Provisionings.pm
  lib/pf/iptables.pm
  lib/pf/provisioner/sepm.pm
Labels: Status: For review

#7726 Add support for serverAuth and DNS SAN in CSR
  html/pfappserver/root/src/views/Configuration/sslCertificates/_components/TheCsr.vue
  html/pfappserver/root/src/views/Configuration/sslCertificates/_components/index.js
  html/pfappserver/root/src/views/Configuration/sslCertificates/_composables/useCsr.js
  lib/pf/ssl.pm
  t/unittest/UnifiedApi/Controller/Config/Certificates.t
Labels: Status: For review

#7721 Notify admins when unexpected devices pop up on network
  conf/security_events.conf.defaults
  html/pfappserver/lib/pfappserver/Form/Field/Trigger.pm
  html/pfappserver/root/src/views/Configuration/securityEvents/config.js
  lib/pf/condition/fingerbank/device_is_not_a.pm
  lib/pf/factory/condition/security_event.pm
  lib/pf/security_event.pm
  t/data/security_events.conf
  t/unittest/security_events.t
Labels: Status: For review
