Repository inverse-inc/packetfence, pull requests merged in 2023-04, with the labels that each got.

#7617 Feature/venom samba4
  addons/vagrant/Vagrantfile
  addons/vagrant/inventory/group_vars/all/common.yml
  addons/vagrant/inventory/group_vars/linux_servers/samba4ad.yml
  addons/vagrant/inventory/group_vars/winservers/ansible.yml
  addons/vagrant/inventory/group_vars/winservers/domain_setup.yml
  addons/vagrant/inventory/group_vars/winservers/init_directory.yml
  addons/vagrant/inventory/hosts
  addons/vagrant/playbooks/linux_servers.yml
  addons/vagrant/playbooks/linux_servers/samba4ad.yml
  addons/vagrant/playbooks/winservers.yml
  addons/vagrant/playbooks/winservers/init_directory.yml
  addons/vagrant/requirements.yml
  addons/vagrant/site.yml
  addons/vagrant/winservers/Vagrantfile
  docs/developer/integration_tests/virtual_machines.asciidoc
  t/venom/vars/all.yml
Labels: Type: Feature / Enhancement, Status: For review

#7595 Feature/go dal
  go/.gitignore
  go/admin_api_audit_log/db.go
  go/caddy/api/api.go
  go/caddy/api/dal_admin_api_audit_log.go
  go/caddy/api/dal_admin_api_audit_log_test.go
  go/caddy/api/dal_auth_log.go
  go/caddy/api/dal_auth_log_test.go
  go/caddy/api/dal_dns_audit_log.go
  go/caddy/api/dal_dns_audit_log_test.go
  go/caddy/api/dal_radacct_log.go
  go/caddy/api/dal_radacct_log_test.go
  go/caddy/api/dal_radius_audit_log.go
  go/caddy/api/dal_radius_audit_log_test.go
  go/caddy/api/dal_wrix.go
  go/caddy/api/dal_wrix_test.go
  go/caddy/dal/models/admin_api_audit_log_models.go
  go/caddy/dal/models/auth_log_model.go
  go/caddy/dal/models/dns_audit_log.go
  go/caddy/dal/models/models.go
  go/caddy/dal/models/radacct_log.go
  go/caddy/dal/models/radius_audit_log.go
  go/caddy/dal/models/wrix.go
Labels: Status: For review

#7627 Improve UI dev setup
  docs/PacketFence_Developers_Guide.asciidoc
  docs/developer/admin_gui.asciidoc
  html/pfappserver/root/vue.config.js
Labels: Status: In progress

#7533 Use Nodejs 14 to build web admin
  ci/packer/provisionners_cpanbuild/inventory/group_vars/common_centos/gitlab_buildpkg_tools.yml
  ci/packer/provisionners_cpanbuild/inventory/group_vars/common_debian/gitlab_buildpkg_tools.yml
  ci/packer/provisionners_pfbuild/inventory/group_vars/common_centos/gitlab_buildpkg_tools.yml
  ci/packer/provisionners_pfbuild/inventory/group_vars/common_debian/gitlab_buildpkg_tools.yml
  ci/packer/vagrant_img/provisioners/playbooks/install_utils.yml
  debian/control
  docs/developer/dev_env_setup.asciidoc
  html/pfappserver/root/Makefile
  t/venom/scenarios/dot1x_eap_peap/playbooks/configure.yml
Labels: Priority: High

#7635 Fix issue with unpretty_bandwidth
  lib/pf/util.pm
  t/util.t
Labels: Status: For review, Priority: Critical

#7640 fix/7638
  lib/pf/factory/condition/profile.pm
  t/data/profiles.conf
  t/unittest/Portal/ProfileFactory.t
  t/unittest/factory/condition/profile.t
Labels: Status: For review, Priority: High
