Repository inverse-inc/packetfence, pull requests merged in 2023-09, with the labels that each got.

#7808 support ip address column for bulk node import
  NEWS.asciidoc
  html/pfappserver/root/src/views/Nodes/_config/index.js
  lib/pf/UnifiedApi/Controller/Nodes.pm
Labels: Type: Feature / Enhancement, Priority: High

#7803 fix/7366
  html/pfappserver/root/src/views/Users/_components/TheViewCreate.vue
  html/pfappserver/root/src/views/Users/_components/TheViewUpdate.vue
  html/pfappserver/root/src/views/Users/_config/index.js
Labels: Status: For review

#7817 bump nodejs version from 14 to 16
  addons/dev-helpers/setup-dev-env.sh
  addons/vagrant/playbooks/local_dev.yml
  ci/packer/provisionners_cpanbuild/inventory/group_vars/common_centos/gitlab_buildpkg_tools.yml
  ci/packer/provisionners_cpanbuild/inventory/group_vars/common_debian/gitlab_buildpkg_tools.yml
  ci/packer/provisionners_pfbuild/inventory/group_vars/common_centos/gitlab_buildpkg_tools.yml
  ci/packer/provisionners_pfbuild/inventory/group_vars/common_debian/gitlab_buildpkg_tools.yml
  ci/packer/vagrant_img/provisioners/playbooks/install_utils.yml
  debian/control
  docs/developer/dev_env_setup.asciidoc
  t/venom/scenarios/dot1x_eap_peap/playbooks/configure.yml
  t/venom/scenarios/pfappserver/playbooks/configure.yml
Labels: Status: For review, Priority: High

#7818 bump nodejs version from 16 to 18
  addons/dev-helpers/setup-dev-env.sh
  ci/packer/provisionners_cpanbuild/inventory/group_vars/common_centos/gitlab_buildpkg_tools.yml
  ci/packer/provisionners_cpanbuild/inventory/group_vars/common_debian/gitlab_buildpkg_tools.yml
  ci/packer/provisionners_pfbuild/inventory/group_vars/common_centos/gitlab_buildpkg_tools.yml.rej
  ci/packer/provisionners_pfbuild/inventory/group_vars/common_debian/gitlab_buildpkg_tools.yml
  ci/packer/vagrant_img/provisioners/playbooks/install_utils.yml
  debian/control
  docs/developer/dev_env_setup.asciidoc
  t/venom/scenarios/dot1x_eap_peap/playbooks/configure.yml
  t/venom/scenarios/pfappserver/playbooks/configure.yml
Labels: Status: For review, Priority: High
