Repository inverse-inc/packetfence, pull requests merged in 2023-07, with the labels that each got.

#7715 Certificate doc
  docs/PacketFence_Installation_Guide.asciidoc
  docs/images/certificate/1-HTTP.png
  docs/images/certificate/10-Radius-CA.png
  docs/images/certificate/11-Services.png
  docs/images/certificate/12-Radius-status.png
  docs/images/certificate/13-Radius-intermediate-chain.png
  docs/images/certificate/14-HTTP-CSR.png
  docs/images/certificate/15-Radius-CSR.png
  docs/images/certificate/16-CSR.png
  docs/images/certificate/17-CSR-radius.png
  docs/images/certificate/2-HTTP-Certificate.png
  docs/images/certificate/3-HTTP-Private-key.png
  docs/images/certificate/4-HTTP-intermediate-chain.png
  docs/images/certificate/5-Services.png
  docs/images/certificate/6-HTTP-View.png
  docs/images/certificate/7-Radius-edit.png
  docs/images/certificate/8-Radius-certificate.png
  docs/images/certificate/9-Radius-key.png
  docs/installation/certificate.asciidoc
Labels: Status: For review, Documentation

#7634 Feature/ldap explorer back end
  .gitlab-ci.yml
  conf/caddy-services/pfldapexplorer.conf.example
  conf/documentation.conf
  conf/pf.conf.defaults
  conf/systemd/packetfence-pfldapexplorer.service
  containers/pfldapexplorer/Dockerfile
  debian/packetfence-pfldapexplorer.service
  debian/rules
  go/caddy/caddy/caddy/caddymain/run.go
  go/caddy/caddy/caddyhttp/httpserver/plugin.go
  go/caddy/log-tailer/logmeta.go
  go/caddy/pfldapexplorer/pfldapexplorer.go
  go/common/languageUtils/map_utils.go
  go/common/ldapClient/ILdapClient.go
  go/common/ldapClient/ProxyLdapClient.go
  go/common/ldapClient/StandardLdapClient.go
  go/common/ldapSearchClient/LdapSearchClient.go
  go/common/ldapSearchClient/ldapSearchClient_suite_test.go
  go/common/ldapSearchClient/ldapSearch_infra_test.go
  go/common/ldapSearchClient/ldapSearch_test.go
  go/connector/connectors.go
  go/firewallsso/base.go
  go/go.mod
  go/go.sum
  go/pfconfigdriver/structs.go
  html/pfappserver/lib/pfappserver/Form/Field/SourceRuleCondition.pm
  lib/pf/Authentication/Condition.pm
  lib/pf/Authentication/Source/LDAPSource.pm
  lib/pf/cmd/pf/service.pm
  lib/pf/services/manager/pfldapexplorer.pm
  lib/pf/services/manager/roles/env_golang_service.pm
  lib/pfconfig/namespaces/config/Authentication.pm
  rpm/packetfence.spec
  sbin/pfldapexplorer-docker-wrapper
  t/data/authentication.conf
  t/unittest/Authentication/Source/LDAPSource.t
  t/unittest/UnifiedApi/Controller/Config/Sources/LDAP.t
  t/unittest/authentication.t
Labels: Status: For review

#7689 Feature/switch module per version
  addons/upgrade/to-13.0-convert-switch-types.pl
  conf/switches.conf.example
  docs/network/networkdevice/cisco.asciidoc
  lib/pf/Switch.pm
  lib/pf/Switch/Cisco/Catalyst_2960G.pm
  lib/pf/Switch/Cisco/Catalyst_2970.pm
  lib/pf/Switch/Cisco/Catalyst_3550.pm
  lib/pf/Switch/Cisco/Catalyst_3560.pm
  lib/pf/Switch/Cisco/Catalyst_3560G.pm
  lib/pf/Switch/Cisco/Catalyst_3750.pm
  lib/pf/Switch/Cisco/Catalyst_3750G.pm
  lib/pf/Switch/Cisco/Catalyst_4500.pm
  lib/pf/Switch/Cisco/Catalyst_6500.pm
  lib/pf/Switch/Cisco/Cisco_IOS.pm
  lib/pf/Switch/Cisco/Cisco_IOS_12_x.pm
  lib/pf/Switch/Cisco/Cisco_IOS_15_0.pm
  lib/pf/Switch/Cisco/Cisco_IOS_15_5.pm
  lib/pf/Switch/Cisco/SG300.pm
  lib/pf/constants/switch_acls.pm
  t/SwitchFactory.t
  t/data/all-switch-types.conf
  t/data/switches.conf
  t/hardware-snmp-objects.t
  t/switch_supports.t
  t/unittest/UnifiedApi/Controller/Config/Switches.t
  t/unittest/pfcron/task/option82_query.t
Labels: Status: Not ready, Status: In progress

#7747 Cache the roles
  html/pfappserver/lib/pfappserver/Role/Form/RolesAttribute.pm
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller.pm
Labels: Priority: High

#7644 Push acls with ansible
  .gitlab-ci.yml
  addons/ansible.pl
  conf/pf.conf.defaults
  conf/pfsetacls/acl.cfg
  conf/pfsetacls/ansible.cfg
  conf/pfsetacls/collections/requirements.yml
  conf/pfsetacls/inventory.cfg
  conf/pfsetacls/switch_acls.yml
  conf/switches.conf.defaults
  conf/systemd/packetfence-pfsetacls.service
  containers/pfsetacls/Dockerfile
  debian/packetfence-pfsetacls.service
  docs/images/PushACLs-Cisco-WLC.png
  docs/images/PushACLs-role.png
  docs/installation/enforcement/supported_enforcement_modes.asciidoc
  html/pfappserver/lib/pfappserver/Form/Config/Switch.pm
  html/pfappserver/root/src/views/Configuration/switchGroups/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/switchGroups/_components/index.js
  html/pfappserver/root/src/views/Configuration/switches/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/switches/_components/index.js
  lib/pf/Switch.pm
  lib/pf/Switch/Aruba/5400.pm
  lib/pf/Switch/Aruba/CX.pm
  lib/pf/Switch/Cisco.pm
  lib/pf/Switch/Cisco/Cisco_IOS_12_x.pm
  lib/pf/Switch/Cisco/Cisco_IOS_15_0.pm
  lib/pf/Switch/Cisco/Cisco_IOS_15_5.pm
  lib/pf/Switch/Cisco/WLC.pm
  lib/pf/Switch/Dell/N1500.pm
  lib/pf/Switch/MockedSwitch.pm
  lib/pf/UnifiedApi/Controller/Config.pm
  lib/pf/UnifiedApi/Controller/Config/Roles.pm
  lib/pf/UnifiedApi/Controller/Config/Switches.pm
  lib/pf/acls_push.pm
  lib/pf/api.pm
  lib/pf/services/manager/pfsetacls.pm
  lib/pf/util.pm
  rpm/packetfence.spec
  sbin/pfsetacls-docker-wrapper
  t/data/switches.conf
  t/unittest/Switch.t
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#7753 fix 7659
  addons/dev-helpers/bin/switch_options_table.pl
Labels: Priority: Medium

#7752 fix/7733
  go/cron/flush_dns_audit_log.go
  go/cron/flush_dns_audit_log_job_test.go
  go/cron/flush_radius_audit_log_job.go
  go/cron/flush_radius_audit_log_job_test.go
  go/cron/redis_client.go
  t/venom/lib/pfcron_command_line.yml
  t/venom/lib/pfcron_flush_radius_audit_log.yml
  t/venom/test_suites/wired_mac_auth/25_check_radius_audit_log.yml
Labels: Priority: Critical
