Repository inverse-inc/packetfence, pull requests merged in 2023-08, with the labels that each got.

#7787 add example for download the certificate
  docs/images/certificate/18-Choice.png
  docs/installation/certificate.asciidoc
Labels: Documentation

#7793 Fix for 7790
  t/venom/test_suites/wired_dot1x_eap_peap_firewall_sso_https/56_check_firewall_sso_start.yml
  t/venom/test_suites/wired_dot1x_eap_peap_firewall_sso_radius/56_check_firewall_sso_start.yml
Labels: Priority: Medium

#7725 Allow duplicate keys
  lib/pf/WebAPI/REST.pm
Labels: Priority: Critical

#7810 Update ip4log from pfdhcp
  go/cmd/pfdhcp/main.go
  go/cmd/pfdhcp/utils.go
  lib/pf/dhcp/processor.pm
  lib/pf/dhcp/processor_v4.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: High, Status: Tested and works
