Repository inverse-inc/packetfence, pull requests merged in 2023-12, with the labels that each got.

#7886 Feature/FortiSwitch Module Update
  addons/upgrade/to-13.1-convert-fortiswitch-types.pl
  docs/network/networkdevice/fortinet_switches.asciidoc
  lib/pf/Switch/Fortinet/FortiSwitchOS_v7_x.pm
Labels: Type: Feature / Enhancement, Status: In progress

#7932 Fixes #7928
  go/caddy/pfpki/cloud/intune.go
Labels: Type: Bug, Status: For review, Priority: Critical

#7923 Force mechanism LOGIN PLAIN
  lib/pf/config/util.pm
Labels: Priority: High
