Repository inverse-inc/packetfence, pull requests merged in 2023-05, with the labels that each got.

#7639 Added Acct-Session-Id = $last_accounting.acctsessionid in Mist.def
  lib/pf/Switch/Juniper/Mist.def
Labels: Type: Feature / Enhancement, Status: For review, Priority: High, Status: Fix confirmed

#7643 Palo Alto switch module (PAN-OS) for web admin login + documentation
  conf/template_switches.conf.defaults
  docs/PacketFence_Network_Devices_Configuration_Guide.asciidoc
  docs/network/firewall_configuration.asciidoc
  docs/network/networkdevice/palo_alto.asciidoc
  lib/pf/Switch/PaloAlto/PanOS.def
Labels: Status: For review

#7649 WMI documentation removed
  NEWS.asciidoc
  docs/PacketFence_Upgrade_Guide.asciidoc
  docs/installation/performing_compliance_checks.asciidoc
  docs/upgrade-notes/archived_upgrade_notes.asciidoc
Labels: Documentation

#7673 Remove encoding utf8
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Application.pm
Labels: Priority: High
