Repository inverse-inc/packetfence, pull requests merged in 2023-01, with the labels that each got.

#7440 Fix/7438 for maintenance patches and major/minor upgrades
  addons/full-upgrade/run-upgrade.sh
  docs/common/upgrade_packages.asciidoc
Labels: Status: For review

#7434 feature/node-on-off-online
  conf/pfcron.conf.defaults
  db/pf-schema-X.Y.sql
  db/upgrade-X.X-X.Y.sql
  go/cmd/pfacct/radius.go
  go/cron/config.go
  html/pfappserver/lib/pfappserver/Form/Config/Pfcron/node_current_session_cleanup.pm
  html/pfappserver/root/src/views/Configuration/maintenanceTasks/_composables/useCollection.js
  lib/pf/UnifiedApi/Controller/Config/MaintenanceTasks.pm
  lib/pf/UnifiedApi/Search/Builder/Nodes.pm
  lib/pf/dal/_node_current_session.pm
  lib/pf/dal/node_current_session.pm
  t/unittest/UnifiedApi/Search/Builder/Nodes.t
Labels: Priority: High

#7468 Flatten ACLs after reading
  lib/pf/ConfigStore/Roles.pm
  t/unittest/UnifiedApi/Controller/Config/Roles.t
Labels: Status: For review, Priority: Medium

#7467 Make sure data is sent as bytes
  lib/pf/config/util.pm
Labels: Priority: High

#7390 fix/3976
  lib/pf/services/manager/radiusd_child.pm
Labels: Priority: Low

#7449 fix/7439
  html/pfappserver/lib/pfappserver/Form/Config/Source/SAML.pm
  t/unittest/UnifiedApi/Controller/Config/Sources/SAML.t
Labels: Priority: Medium

#7351 allow to make the VLAN filters actions synchronous
  html/pfappserver/lib/pfappserver/Form/Config/FilterEngines/VlanFilter.pm
  html/pfappserver/root/src/views/Configuration/filterEngines/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/filterEngines/_components/index.js
  lib/pf/access_filter.pm
Labels: Status: Not ready

#7186 Remove kubernetes and move to github.com/go-kit/log
  go/caddy/pfpki/scep/scep.go
  go/coredns/core/plugin/zplugin.go
  go/coredns/plugin/kubernetes/README.md
  go/coredns/plugin/kubernetes/autopath.go
  go/coredns/plugin/kubernetes/controller.go
  go/coredns/plugin/kubernetes/external.go
  go/coredns/plugin/kubernetes/handler.go
  go/coredns/plugin/kubernetes/kubernetes.go
  go/coredns/plugin/kubernetes/local.go
  go/coredns/plugin/kubernetes/metadata.go
  go/coredns/plugin/kubernetes/metrics.go
  go/coredns/plugin/kubernetes/namespace.go
  go/coredns/plugin/kubernetes/ns.go
  go/coredns/plugin/kubernetes/object/endpoint.go
  go/coredns/plugin/kubernetes/object/informer.go
  go/coredns/plugin/kubernetes/object/object.go
  go/coredns/plugin/kubernetes/object/pod.go
  go/coredns/plugin/kubernetes/object/service.go
  go/coredns/plugin/kubernetes/parse.go
  go/coredns/plugin/kubernetes/ready.go
  go/coredns/plugin/kubernetes/reverse.go
  go/coredns/plugin/kubernetes/setup.go
  go/coredns/plugin/kubernetes/watch.go
  go/coredns/plugin/kubernetes/xfr.go
  go/go.mod
  go/go.sum
Labels: Priority: Medium

#7474 Remove useless Debian packages to avoid conflicts during upgrades
  debian/control
Labels: Status: For review

#7470 Create a dedicated switch module to handle WebAuth (full HTTP) on Aruba AP
  lib/pf/Switch/Aruba/Instant.pm
Labels: Status: For review

#7457 Remove pf::schdeule - feature/remove-pf-schedule
  lib/pf/cmd/pf.pm
  lib/pf/cmd/pf/schedule.pm
  lib/pf/schedule.pm
Labels: Status: For review, Type: Nice to have, Priority: Low

#7476 Template to track problems related to tests
  .github/ISSUE_TEMPLATE/test_problem.md
Labels: tests

#7469 fix/7175
  go/caddy/job-status/job-status.go
  lib/pf/UnifiedApi/Controller/Pfqueue.pm
  lib/pf/pfqueue/status_updater/redis.pm
Labels: Priority: Medium

#7359 Fix Aruba DACL
  lib/pf/Switch/Aruba/2930M.pm
  lib/pf/Switch/Aruba/5400.pm
Labels: Type: Bug, Status: For review, Priority: High, Status: Fix confirmed

#7466 feature/cisco_dacl
  addons/dev-helpers/bin/generator-switch-acls.pl
  addons/dev-helpers/templates/pf-switch-acls.pm.tt
  conf/chi.conf.defaults
  conf/radiusd/packetfence-cli.example
  conf/switches.conf.defaults
  containers/pfdebian/Dockerfile
  db/pf-schema-X.Y.sql
  db/upgrade-X.X-X.Y.sql
  debian/control
  docs/installation/enforcement/supported_enforcement_modes.asciidoc
  docs/network/networkdevice/cisco.asciidoc
  docs/network/networkdevice/dell.asciidoc
  html/pfappserver/lib/pfappserver/Base/Form.pm
  html/pfappserver/lib/pfappserver/Form/Config/Roles.pm
  html/pfappserver/lib/pfappserver/Form/Config/Switch.pm
  html/pfappserver/lib/pfappserver/Util/ACLs.pm
  html/pfappserver/root/src/globals/mysql.js
  html/pfappserver/root/src/views/Configuration/switchGroups/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/switchGroups/_components/index.js
  html/pfappserver/root/src/views/Configuration/switches/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/switches/_components/index.js
  html/pfappserver/root/src/views/Nodes/_components/TheFormUpdate.vue
  html/pfappserver/root/src/views/Nodes/_components/index.js
  html/pfappserver/root/src/views/Nodes/_config/index.js
  html/pfappserver/root/src/views/Nodes/_search.js
  html/pfappserver/root/src/views/Nodes/network/_search.js
  html/pfappserver/root/src/views/Users/_config/index.js
  lib/pf/CHI.pm
  lib/pf/Connection.pm
  lib/pf/Switch.pm
  lib/pf/Switch/Cisco.pm
  lib/pf/Switch/Cisco/ASA.pm
  lib/pf/Switch/Cisco/Catalyst_2960.pm
  lib/pf/Switch/Cisco/Catalyst_3500XL.pm
  lib/pf/Switch/Cisco/Catalyst_3550.pm
  lib/pf/Switch/Cisco/Catalyst_3560.pm
  lib/pf/Switch/Cisco/Catalyst_3560G.pm
  lib/pf/Switch/Cisco/SG300.pm
  lib/pf/Switch/Dell/N1500.pm
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config.pm
  lib/pf/UnifiedApi/Controller/Config/Roles.pm
  lib/pf/UnifiedApi/Controller/Nodes.pm
  lib/pf/constants/config.pm
  lib/pf/constants/switch_acls.pm
  lib/pf/dal/_node.pm
  lib/pf/error/switch.pm
  lib/pf/radius.pm
  lib/pf/radius/rest.pm
  rpm/packetfence.spec
  t/data/roles.conf
  t/data/switches.conf
  t/hardware-snmp-objects.t
  t/unittest/Switch.t
  t/unittest/UnifiedApi/Controller/Config/Roles.t
  t/unittest/UnifiedApi/Controller/Config/Switches.t
  t/unittest/UnifiedApi/Controller/Nodes.t
  t/unittest/pfconfig/cached_hash.t
Labels: Type: Feature / Enhancement, Status: For review, Priority: Critical
