Repository inverse-inc/packetfence, pull requests merged in 2023-02, with the labels that each got.

#7495 Fix/7490
  addons/full-upgrade/run-upgrade.sh
  docs/common/upgrade_packages.asciidoc
Labels: Status: For review

#7491 Use the ENV variable for the logging level
  conf/log.conf.d/httpd.aaa.conf.example
  conf/log.conf.d/httpd.collector.conf.example
  conf/log.conf.d/httpd.portal.conf.example
  conf/log.conf.d/httpd.proxy.conf.example
  conf/log.conf.d/httpd.webservices.conf.example
  conf/log.conf.d/pfconfig.conf.example
  conf/log.conf.d/pfdhcplistener.conf.example
  conf/log.conf.d/pfdns.conf.example
  conf/log.conf.d/pffilter.conf.example
  conf/log.conf.d/pfperl-api.conf.example
  conf/log.conf.d/pfqueue.conf.example
  conf/log.conf.d/rlm_perl.conf.example
  conf/log.conf.d/winbindd-wrapper.conf.example
  conf/log.conf.example
  lib/pf/log.pm
Labels: Priority: Medium

#7502 Add bulk_apply_bypass_acls
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Nodes.pm
  t/unittest/UnifiedApi/Controller/Nodes.t
Labels: Priority: High

#7507 Improve pfconnector dynreverse error handling
  go/chisel/server/server_handler.go
Labels: Status: For review

#7521 Add not_before to PKI revoked certificates, fixes #7509
  db/pf-schema-X.Y.sql
  db/upgrade-X.X-X.Y.sql
  go/caddy/pfpki/models/models.go
  html/pfappserver/root/src/views/Configuration/pki/certs/_composables/useCollection.js
  html/pfappserver/root/src/views/Configuration/pki/revokedCerts/_composables/useCollection.js
Labels: Status: For review, Priority: High

#7516 Upgrade note for pfacct containerization
  docs/PacketFence_Upgrade_Guide.asciidoc
Labels: Status: For review

#7532 fix/7504
  containers/manage-images.sh
  html/pfappserver/root/src/components/AppDocumentation.vue
  html/pfappserver/root/src/store/modules/documentation.js
Labels: Status: For review, Priority: High

#7542 fix/7539
  html/pfappserver/lib/pfappserver/Form/Field/FingerbankSelect.pm
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller.pm
Labels: Priority: Critical

#7551 Fix/iptables in venom
  t/venom/lib/perl_iptables_restart.yml
  t/venom/lib/perl_iptables_restore.yml
  t/venom/test_suites/common/restart_iptables_service.yml
  t/venom/test_suites/inline/l2/05_setup_packetfence.yml
  t/venom/test_suites/inline/l2/teardown/05_deconfigure_packetfence.yml
  t/venom/test_suites/inline/l3/10_setup_packetfence.yml
  t/venom/test_suites/inline/l3/teardown/05_deconfigure_packetfence.yml
  t/venom/test_suites/security_event_random_mac/05_setup_packetfence.yml
  t/venom/test_suites/security_event_random_mac/teardown/05_deconfigure_packetfence.yml
  t/venom/test_suites/security_event_suricata/05_setup_packetfence.yml
  t/venom/test_suites/security_event_suricata/teardown/05_deconfigure_packetfence.yml
Labels: Priority: Medium, Status: Fix confirmed
