Repository inverse-inc/packetfence, pull requests merged in 2023-10, with the labels that each got.

#7836 Fix 7835
  addons/vagrant/requirements.yml
  ci/packer/provisionners_cpanbuild/requirements.yml
  ci/packer/provisionners_pfbuild/requirements.yml
  ci/packer/vagrant_img/provisioners/requirements.yml
  t/venom/requirements.yml
Labels: Priority: Critical

#7856 Use https and a fqdn to test the network connectivity
  conf/pf.conf.defaults
  html/common/pf.js
Labels: Type: Bug, Status: For review, Priority: High

#7855 Feature/upgrade to ansible-core 2.15 vagrant and vagrant-plugin
  .gitlab-ci.yml
  addons/vagrant/Vagrantfile
  addons/vagrant/cumulus/Vagrantfile
  addons/vagrant/inventory/group_vars/all/common.yml
  addons/vagrant/inventory/group_vars/clusters/venom_local_vars.yml
  addons/vagrant/inventory/group_vars/cumulus/switch_settings.yml
  addons/vagrant/inventory/group_vars/pfservers/environment.yml
  addons/vagrant/inventory/group_vars/pfservers/packetfence_install.yml
  addons/vagrant/inventory/group_vars/standalones/venom_local_vars.yml
  addons/vagrant/inventory/hosts
  addons/vagrant/linux_servers/Vagrantfile
  addons/vagrant/pfservers/Vagrantfile
  addons/vagrant/playbooks/cumulus.yml
  addons/vagrant/playbooks/tasks/vagrant_iptables.yml
  addons/vagrant/requirements.yml
  addons/vagrant/wireless/Vagrantfile
  ci/packer/cpanbuild.json
  ci/packer/pfbuild.json
  ci/packer/provisionners_cpanbuild/playbooks/python3.yml
  ci/packer/provisionners_cpanbuild/requirements.yml
  ci/packer/provisionners_pfbuild/playbooks/python3.yml
  ci/packer/provisionners_pfbuild/requirements.yml
  ci/packer/vagrant_img/provisioners/requirements.yml
  t/venom/requirements.yml
  t/venom/test-wrapper.sh
Labels: Status: For review, Status: Tested and works

#7811 Fix netdata mysql graph on standalone
  conf/monitoring/python.d/mysql.conf.example
  lib/pf/services/manager/netdata.pm
Labels: Type: Bug, Status: For review, Priority: High, Status: Tested and works

#7837 Added advanced proxy configuration
  docs/installation/advanced_radius_configuration.asciidoc
Labels: Status: For review, Priority: High, Documentation
