Repository inverse-inc/packetfence, pull requests merged in 2024-07, with the labels that each got.

#8174 Fixes Aruba CX deauthentication on 802.1x connection.
  lib/pf/Switch/Aruba/ArubaOS_CX_10_x.pm
Labels: Type: Bug, Status: For review, Priority: High, Status: Fix confirmed

#8207 Added option to permit firewall sso load balance on a cluster (disabled
  conf/documentation.conf
  conf/pf.conf.defaults
  html/pfappserver/root/src/views/Configuration/activeActive/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/activeActive/_components/index.js
  lib/pf/firewallsso.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#8205 Fix/dedicated machine account for cluster
  addons/upgrade/to-13.1-move-ntlm-auth-to-rest.pl
  addons/upgrade/to-14.0-update-domain-config-section.pl
  bin/pyntlm_auth/config_generator.py
  bin/pyntlm_auth/config_loader.py
  bin/pyntlm_auth/global_vars.py
  bin/pyntlm_auth/rpc.py
  bin/pyntlm_auth/utils.py
  docs/installation/authentication_mechanisms.asciidoc
  go/plugin/caddy2/api/ntlm.go
  html/pfappserver/lib/pfappserver/Form/Config/Domain.pm
  lib/pf/ConfigStore/Domain.pm
  lib/pf/UnifiedApi/Controller/Config/Domains.pm
  lib/pf/services/manager/ntlm_auth_api.pm
  lib/pfconfig/namespaces/config/Domain.pm
Labels: Type: Feature / Enhancement, Priority: High
