Repository inverse-inc/packetfence, pull requests merged in 2024-04, with the labels that each got.

#8000 Split in 2 the search on usernameattribute value
  lib/pf/services/manager/radiusd_child.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium

#8018 Feature/Meraki switch module per version
  addons/upgrade/to-13.2-convert-merakiswitch-types.pl
  docs/network/networkdevice/meraki.asciidoc
  lib/pf/Switch/Meraki/MS.pm
  lib/pf/Switch/Meraki/MS_v15.pm
  lib/pf/web/constants.pm
  lib/pf/web/externalportal.pm
Labels: Type: Feature / Enhancement

#8074 feature/faster-pfconfig-start
  lib/pfconfig/backend/mysql.pm
  lib/pfconfig/manager.pm
  sbin/pfconfig
Labels: Status: For review, Priority: High

#8022 Support for a fqdn as switch id with Aruba webauth
  html/pfappserver/lib/pfappserver/Form/Config/Switch.pm
  html/pfappserver/lib/pfappserver/Form/Field/SwitchID.pm
  lib/pf/Switch/Aruba.pm
  lib/pf/Switch/Aruba/Instant.pm
  lib/pf/util.pm
  t/SwitchFactory.t
  t/data/switches.conf
  t/unittest/UnifiedApi/Controller/Config/Switches.t
Labels: Status: For review, Priority: High

#8058 Update proxysql version and use pxc_sheduler_handler
  conf/config.toml.example
  conf/documentation.conf
  conf/pf.conf.defaults
  conf/proxysql.conf.example
  containers/proxysql/Dockerfile
  debian/packetfence.conffiles
  html/pfappserver/root/src/views/Configuration/database/proxysql/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/database/proxysql/_components/index.js
  lib/pf/services/manager/proxysql.pm
  rpm/packetfence.spec
  sbin/proxysql-docker-wrapper
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#8060 feature/jamfCloud
  html/captive-portal/templates/provisioner/jamfcloud.html
  html/pfappserver/lib/pfappserver/Form/Config/Provisioning/jamfcloud.pm
  html/pfappserver/root/src/views/Configuration/provisioners/_components/FormTypeJamfCloud.vue
  html/pfappserver/root/src/views/Configuration/provisioners/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/provisioners/config.js
  lib/pf/UnifiedApi/Controller/Config/Provisionings.pm
  lib/pf/provisioner/jamfCloud.pm
Labels: Status: For review

#8005 Select on which destination ip the dhcp reply needs to be sent
  go/cmd/pfdhcp/config.go
  go/cmd/pfdhcp/main.go
  go/cmd/pfdhcp/server.go
  go/cmd/pfdhcp/workers_pool.go
  go/pfconfigdriver/structs.go
  html/pfappserver/lib/pfappserver/Form/Config/Network.pm
  html/pfappserver/root/src/views/Configuration/networks/routedNetworks/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/networks/routedNetworks/_components/index.js
  lib/pf/constants/dhcp.pm
Labels: Type: Feature / Enhancement, Status: For review, Status: Not ready, Priority: Medium

#8052 Create help docs for NT Key caching
  docs/images/domain-event-trigger-in-task-scheduler.png
  docs/images/domain-nt-key-cache-task-scheduler-actions.jpg
  docs/images/domain-nt-key-cache-task-scheduler-triggers.jpg
  docs/images/domain-nt-key-cache-task-scheduler.jpg
  docs/images/domain-nt-key-cache.jpg
  docs/images/domain-windows-account-policy.png
  docs/images/domain-windows-events-viewer.png
  docs/installation/performance_optimizations.asciidoc
Labels: Status: For review, Priority: High

#8009 Cisco 9800 documentation
  docs/images/wlc-9800-acl-pre-auth-flex.jpg
  docs/images/wlc-9800-acl-pre-auth-for-webredirect-v2.jpg
  docs/images/wlc-9800-acl-pre-auth-for-webredirect.jpg
  docs/images/wlc-9800-acl-pre-webauth.jpg
  docs/network/networkdevice/cisco_ap.asciidoc
Labels: Documentation

#8089 Send username, ip and role to PaloAlto Firewall SSO payload
  go/firewallsso/paloalto.go
  go/firewallsso/paloalto_test.go
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium, Status: Tested and works

#8038 NACaaS Remote Database
  debian/control
  html/pfappserver/lib/pfappserver/Form/Config/Pf.pm
  html/pfappserver/lib/pfappserver/Model/DB.pm
  html/pfappserver/root/src/utils/regex.js
  html/pfappserver/root/src/utils/yup.js
  html/pfappserver/root/src/views/Configurator/packetfence/_components/FormDatabase.vue
  lib/pf/UnifiedApi/Controller/Config/Bases.pm
  t/html/pfappserver/cypress/specs/e2e/00-configurator/01-configurator.cy.js
  t/venom/test_suites/configurator/20_run_configurator_step2.yml
  t/venom/test_suites/configurator_inline/20_run_configurator_step2.yml
  t/venom/test_suites/configurator_inline_l2/20_run_configurator_step2.yml
Labels: Status: Not ready, Priority: High, Status: In progress

#7436 Disable CLI by default in fortigate switch module
  lib/pf/Connection.pm
  lib/pf/Switch/Fortinet/FortiGate.pm
  lib/pf/radius.pm
Labels: Type: Bug, Status: For review, Priority: High

#8106 Fix issue 8105
  addons/full-import/import.sh
Labels: Status: For review, Priority: High, Status: Tested and works
