Repository inverse-inc/packetfence, pull requests merged in 2024-08, with the labels that each got.

#8193 Fix 8105 handle previous PF export file version (11.x, 12.x and 13.0 )
  addons/full-import/import.sh
Labels: Priority: High, Status: Fix confirmed, Status: Tested and works

#8242 feature/remove-pfconfigpool2
  conf/caddy-services/api.conf.example
  conf/caddy-services/httpdispatcher.conf.example
  conf/caddy-services/pfipset.conf.example
  conf/caddy-services/pfsso.conf.example
  go/api-frontend/aaa/db_token_backend.go
  go/chisel/server/server.go
  go/chisel/server/server_handler.go
  go/cmd/pfdhcp/config.go
  go/cmd/pfdhcp/main.go
  go/cmd/pfdhcp/utils.go
  go/connector/redis.go
  go/db/db.go
  go/firewallsso/base.go
  go/firewallsso/base_test.go
  go/firewallsso/factory.go
  go/firewallsso/factory_test.go
  go/firewallsso/firewalls.go
  go/httpdispatcher/proxy.go
  go/httpdispatcher/proxy_test.go
  go/pfconfigdriver/cached_hash.go
  go/pfconfigdriver/config_store.go
  go/pfconfigdriver/pool.go
  go/pfconfigdriver/pool_config.go
  go/pfconfigdriver/pool_config_test.go
  go/pfconfigdriver/pool_test.go
  go/pfconfigdriver/structs.go
  go/plugin/caddy2/httpdispatcher/httpdispatcher.go
  go/plugin/caddy2/job-status/job-status.go
  go/plugin/caddy2/pfconfig/pool.go
  go/plugin/caddy2/pfipset/pfipset.go
  go/plugin/caddy2/pfipset/utils.go
  go/plugin/caddy2/pfpki/models/models.go
  go/plugin/caddy2/pfsso/pfsso.go
  go/plugin/caddy2/pfsso/pfsso_test.go
  go/plugin/caddy2/plugins.go
  go/plugin/coredns/pfdns/pfconfig.go
  go/plugin/coredns/pfdns/pfdns.go
  go/plugin/coredns/pfdns/setup.go
  go/redisclient/redisclient.go
Labels: Priority: High

#8249 Added fingerbank_lookup action in eventHandlers
  html/pfappserver/root/src/views/Configuration/eventHandlers/config.js
  lib/pf/api.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium, Status: Tested and works
