Repository inverse-inc/packetfence, pull requests merged in 2024-12, with the labels that each got.

#8380 Parse RADIUS request attributes during Redis cache extraction
  go/cron/flush_radius_audit_log_job.go
Labels: Type: Feature / Enhancement, Priority: Medium

#8356 Feature/improve dpsk
  db/pf-schema-X.Y.sql
  db/upgrade-X.X-X.Y.sql
  html/captive-portal/lib/captiveportal/PacketFence/Controller/Status.pm
  html/captive-portal/lib/captiveportal/PacketFence/Controller/WirelessProfile.pm
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Provisioning.pm
  lib/pf/Switch/OpenWiFi.pm
  lib/pf/Switch/Ruckus/SmartZone.pm
  lib/pf/provisioner/mobileconfig.pm
  lib/pf/radius.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: High, Status: Tested and works

#8418 Improve Mikrotik Disconnect
  lib/pf/Switch/Mikrotik.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium, Status: Tested and works

#8400 Select the first device that match the MFA method
  lib/pf/Switch/Aruba.pm
  lib/pf/Switch/Aruba/5400.pm
  lib/pf/Switch/Aruba/ArubaOS_CX_10_x.pm
  lib/pf/Switch/Avaya.pm
  lib/pf/Switch/Brocade.pm
  lib/pf/Switch/Cisco.pm
  lib/pf/Switch/Cisco/ASA.pm
  lib/pf/Switch/Cisco/Cisco_WLC_AireOS.pm
  lib/pf/Switch/Dell/N1500.pm
  lib/pf/Switch/Extreme.pm
  lib/pf/Switch/F5.pm
  lib/pf/Switch/Fortinet/FortiGate.pm
  lib/pf/Switch/Generic.pm
  lib/pf/Switch/GenericVPN.pm
  lib/pf/Switch/H3C.pm
  lib/pf/Switch/HP.pm
  lib/pf/Switch/Juniper.pm
  lib/pf/Switch/OpenVPN.pm
  lib/pf/Switch/Template.pm
  lib/pf/Switch/Ubiquiti/EdgeSwitch.pm
  lib/pf/Switch/Xirrus.pm
  lib/pf/mfa/Akamai.pm
  lib/pf/mfa/TOTP.pm
  lib/pf/radius.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#8419 Improve DB connection in pfdhcp
  go/cmd/pfdhcp/api.go
  go/cmd/pfdhcp/config.go
  go/cmd/pfdhcp/keysoption.go
  go/cmd/pfdhcp/main.go
  go/cmd/pfdhcp/server.go
  go/cmd/pfdhcp/utils.go
  go/cmd/pfdhcp/workers_pool.go
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium

#8421 feature/kakfa-config
  docs/api/spec/openapi.json
  docs/api/spec/openapi.yaml
  html/pfappserver/lib/pfappserver/Form/Config/Kafka.pm
  html/pfappserver/lib/pfappserver/Form/Config/Pfcron/pfflow.pm
  html/pfappserver/lib/pfappserver/Form/Field/NameVal.pm
  html/pfappserver/lib/pfappserver/Form/Field/UserPass.pm
  html/pfappserver/root/src/components/new/BaseFormGroupArray.vue
  html/pfappserver/root/src/composables/useInputValidator.js
  html/pfappserver/root/src/views/Configuration/_router/index.js
  html/pfappserver/root/src/views/Configuration/index.vue
  html/pfappserver/root/src/views/Configuration/kafka/_api.js
  html/pfappserver/root/src/views/Configuration/kafka/_components/BaseAuth.vue
  html/pfappserver/root/src/views/Configuration/kafka/_components/BaseClusterConfig.vue
  html/pfappserver/root/src/views/Configuration/kafka/_components/BaseFormGroupAuths.js
  html/pfappserver/root/src/views/Configuration/kafka/_components/BaseFormGroupClusterConfig.js
  html/pfappserver/root/src/views/Configuration/kafka/_components/BaseFormGroupHostConfig.js
  html/pfappserver/root/src/views/Configuration/kafka/_components/BaseFormGroupHostConfigs.js
  html/pfappserver/root/src/views/Configuration/kafka/_components/BaseFormGroupIptables.js
  html/pfappserver/root/src/views/Configuration/kafka/_components/BaseHostConfig.vue
  html/pfappserver/root/src/views/Configuration/kafka/_components/BaseHostConfigConfig.vue
  html/pfappserver/root/src/views/Configuration/kafka/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/kafka/_components/TheView.js
  html/pfappserver/root/src/views/Configuration/kafka/_components/index.js
  html/pfappserver/root/src/views/Configuration/kafka/_composables/useResource.js
  html/pfappserver/root/src/views/Configuration/kafka/_router.js
  html/pfappserver/root/src/views/Configuration/kafka/_store.js
  html/pfappserver/root/src/views/Configuration/kafka/config.js
  html/pfappserver/root/src/views/Configuration/kafka/schema.js
  html/pfappserver/root/src/views/Configuration/maintenanceTasks/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/maintenanceTasks/_components/index.js
  lib/pf/UnifiedApi.pm
  lib/pf/UnifiedApi/Controller/Config.pm
  lib/pf/UnifiedApi/Controller/Config/Kafka.pm
  lib/pf/UnifiedApi/OpenAPI/Generator/Config.pm
  t/unittest/UnifiedApi/Controller/Config/Kafka.t
Labels: Status: For review, Priority: Critical

#7908 Fix update to the Debian sudoers file
  debian/packetfence.sudoers
Labels: Type: Nice to have, Priority: Low

#8417 Allow sflow to be processed
  go/cron/pfflowjob.go
Labels: Status: For review, Priority: Critical

#8435 Update go version because of https://github.com/golang/go/issues/70198
  config.mk
  go/go.mod
Labels: Status: For review, Priority: Critical

#8436 feature/pfflow sflow
  config.mk
  go/cmd/pfkafka/main.go
  go/cron/aggregator.go
  go/cron/aggregator_test.go
  go/cron/kafka_submitter.go
  go/cron/pfflow.go
  rpm/packetfence.spec
Labels: Status: For review, Priority: Critical

#8439 Use source from profile if none is set in Module.
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication.pm
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Email.pm
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/SMS.pm
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication/Sponsor.pm
Labels: Status: For review, Priority: High

#8455 updated the WiSM module to Cisco_WLC_AireOS in the unit test
  t/network-devices/wireless.t
Labels: Priority: High
