Repository inverse-inc/packetfence, pull requests merged in 2024-10, with the labels that each got.

#8326 Fix packetfence maintenance branch to match related tag
  ci/debian-installer/Makefile
  ci/debian-installer/build-and-upload.sh
  ci/packer/zen/build-and-upload.sh
Labels: Priority: Medium

#8331 Change ReturnRole attribute for ArubaOS_CX
  addons/upgrade/to-14.1-convert-switch-types.pl
  lib/pf/Switch/Aruba/ArubaOS_CX_10_x.pm
  lib/pf/Switch/Aruba/CX.pm
Labels: Type: Feature / Enhancement, Priority: Medium

#8335 Feature/118 smb multi thread
  addons/upgrade/to-14.1-adds-domain-multi-machine-account-support.pl
  bin/pyntlm_auth/app.py
  bin/pyntlm_auth/config_loader.py
  bin/pyntlm_auth/entrypoint.py
  bin/pyntlm_auth/global_vars.py
  bin/pyntlm_auth/gunicorn.conf.py
  bin/pyntlm_auth/handlers.py
  bin/pyntlm_auth/redis_client.py
  bin/pyntlm_auth/t_api.py
  bin/pyntlm_auth/t_async_job.py
  bin/pyntlm_auth/t_health_checker.py
  bin/pyntlm_auth/t_sdnotify.py
  bin/pyntlm_auth/t_worker_register.py
  bin/pyntlm_auth/utils.py
  containers/ntlm-auth-api/Dockerfile
  docs/installation/authentication_mechanisms.asciidoc
  docs/installation/performance_optimizations.asciidoc
  html/pfappserver/lib/pfappserver/Form/Config/Domain.pm
  html/pfappserver/root/src/views/Configuration/domains/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/domains/_components/index.js
  lib/pf/UnifiedApi/Controller/Config/Domains.pm
  lib/pf/services/manager/ntlm_auth_api.pm
Labels: Type: Feature / Enhancement, Priority: High
