Repository inverse-inc/packetfence, pull requests merged in 2024-09, with the labels that each got.

#8273 Resolve the ip address of a mac in acl
  lib/pf/Switch.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: Critical

#8260 VoIP on Aruba CX switch
  lib/pf/Switch/Aruba/ArubaOS_CX_10_x.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: High, Status: Tested and works, Customer

#8267 Use proxysql from packetfence repo for proxysql container
  containers/proxysql/Dockerfile
Labels: Priority: Medium, Status: Tested and works

#8290 Use new FreeRADIUS 3.2.6 version
  containers/radiusd/Dockerfile
  debian/control
  rpm/packetfence.spec
Labels: Type: Feature / Enhancement, Status: For review, Priority: Critical

#8270 Fix GenericVPN switch module
  lib/pf/Switch/GenericVPN.pm
Labels: Type: Bug, Status: For review, Priority: High

#8269 Fix broken "restart services" link in import/export section
  docs/installation/export_import_mechanism.asciidoc
Labels: Type: Bug, Priority: Medium

#8297 Reworked logic on the dhcp reply
  go/cmd/pfdhcp/config.go
  go/cmd/pfdhcp/main.go
  go/cmd/pfdhcp/workers_pool.go
Labels: Type: Bug, Status: For review, Priority: Critical, Status: Tested and works

#8299 Fixes Captive portal FQDN matches hostname, so it resolves to 127.0.1.1
  go/cmd/pfdns/main.go
Labels: Type: Bug, Status: For review, Priority: High

#8289 Option for sso stop on accounting stop
  go/firewallsso/base.go
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/BarracudaNG.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/CiscoIsePic.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/ContentKeeper.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/FamilyZone.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/FortiGate.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/Iboss.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/JSONRPC.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/JuniperSRX.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/PaloAlto.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/WatchGuard.pm
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeBarracudaNg.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeCheckpoint.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeCiscoIsePic.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeContentKeeper.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeFamilyZone.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeFortiGate.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeIboss.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeJsonRpc.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeJuniperSrx.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeLightSpeedRocket.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypePaloAlto.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeSmoothWall.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeWatchGuard.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/index.js
  lib/pf/api.pm
  lib/pf/dhcp/processor.pm
  lib/pf/firewallsso.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#8306 fixes #8248
  html/captive-portal/lib/captiveportal/PacketFence/DynamicRouting/Module/Authentication.pm
Labels: Type: Bug, Status: For review, Priority: Medium

#8310 Feature/pki multi cert cn
  db/pf-schema-X.Y.sql
  db/upgrade-X.X-X.Y.sql
  go/plugin/caddy2/pfpki/models/models.go
  html/pfappserver/root/src/views/Configuration/pki/certs/schema.js
  html/pfappserver/root/src/views/Configuration/pki/profiles/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/pki/profiles/_components/index.js
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium

#8303 move form toggles from bases/advanced to firewalls
  NEWS.asciidoc
  addons/upgrade/to-14.1-firewallsso.pl
  conf/documentation.conf
  conf/pf.conf.defaults
  go/firewallsso/base.go
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/BarracudaNG.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/CiscoIsePic.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/ContentKeeper.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/FamilyZone.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/FortiGate.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/Iboss.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/JSONRPC.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/JuniperSRX.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/PaloAlto.pm
  html/pfappserver/lib/pfappserver/Form/Config/Firewall_SSO/WatchGuard.pm
  html/pfappserver/root/src/views/Configuration/advanced/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/advanced/_components/index.js
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeBarracudaNg.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeCheckpoint.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeCiscoIsePic.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeContentKeeper.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeFamilyZone.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeFortiGate.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeIboss.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeJsonRpc.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeJuniperSrx.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeLightSpeedRocket.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypePaloAlto.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeSmoothWall.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/FormTypeWatchGuard.vue
  html/pfappserver/root/src/views/Configuration/firewalls/_components/index.js
  html/pfappserver/root/src/views/Configurator/status/_components/TheStep.vue
  lib/pf/api.pm
  lib/pf/constants/firewallsso.pm
  lib/pf/dhcp/processor.pm
  lib/pf/enforcement.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium

#8315 Improvement in Ruckus Unbound DPSK
  NEWS.asciidoc
  lib/pf/Switch/Ruckus/SmartZone.pm
  lib/pf/util/wpa.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: High

#8321 Updated pfconnector-remote install procedure
  docs/installation/linode/linode.asciidoc
Labels: Type: Feature / Enhancement, Status: For review, Priority: Low

#8313 Add upgrade, limitation and information for Debian12 and el8 in documentation
  docs/PacketFence_Upgrade_Guide.asciidoc
  docs/installation/automation_of_upgrades.asciidoc
  docs/installation/export_import_mechanism.asciidoc
  docs/upgrade-notes/archived_upgrade_notes.asciidoc
Labels: Priority: High, Documentation

#8319 Support for updating CIDR switch network from event handler.
  html/pfappserver/root/src/views/Configuration/eventHandlers/config.js
  lib/pf/api.pm
  t/unittest/UnifiedApi/Controller/Config/OPTIONS.t
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium
