Repository inverse-inc/packetfence, pull requests merged in 2025-05, with the labels that each got.

#8175 Fixes logic when pfacct and radius-acct are enabled
  README.md
  lib/pf/services/manager/pfacct.pm
  lib/pf/services/manager/radiusd_child.pm
  sbin/pfacct-docker-wrapper
Labels: Type: Bug, Status: For review, Priority: High, Status: Fix confirmed

#8643 Support for dACLs on Cisco WLC IOS XE
  lib/pf/Switch/Cisco/Cisco_WLC_IOS_XE.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: High, Status: Tested and works

#8603 fix/8522
  lib/pf/domain/ntlm_cache.pm
Labels: Status: For review, Priority: High

#8646 Arista Switch Support
  conf/pfsetacls/acl.cfg
  conf/pfsetacls/collections/requirements.yml
  conf/pfsetacls/inventory.cfg
  conf/pfsetacls/switch_acls.yml
  lib/pf/Switch.pm
  lib/pf/Switch/Arista/AristaSwitch.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: High, Status: Tested and works

#8638 Feature/pfflows fingerprint
  conf/pfcron.conf.defaults
  go/cron/aggregator.go
  go/cron/kafka_submitter.go
  go/cron/pfflow_fingerprinting.go
  go/cron/pfflow_fingerprinting_test.go
  go/cron/pfflowjob.go
  go/go.mod
  go/go.sum
  html/pfappserver/lib/pfappserver/Form/Config/Pfcron/pfflow.pm
  html/pfappserver/root/src/views/Configuration/maintenanceTasks/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/maintenanceTasks/_components/index.js
  lib/pfconfig/namespaces/config/Cron.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: High, Status: Tested and works

#8631 Reduce CPU and memory usage for pfdhcp and refactored code
  go/cmd/pfdhcp/api.go
  go/cmd/pfdhcp/config.go
  go/cmd/pfdhcp/keysoption.go
  go/cmd/pfdhcp/main.go
  go/cmd/pfdhcp/utils.go
  go/cmd/pfdhcp/utils_test.go
  go/cmd/pfdhcp/workers_pool.go
  go/dhcp/pool/memory.go
Labels: Type: Feature / Enhancement, Status: For review, Priority: Critical, Status: Tested and works
