Repository inverse-inc/packetfence, pull requests merged in 2025-07, with the labels that each got.

#8529 Adding the Downloadable and Dynamic ACL enforcement to FortiSwitch
  lib/pf/Switch/Fortinet/FortiSwitchOS_v7_x.pm
Labels: Type: Feature / Enhancement, Priority: Medium

#8614 Added more detailled documentation
  docs/installation/kafka.asciidoc
Labels: Status: For review, Priority: Medium, Documentation

#8699 fix/8693
  go/dal/models/radius_audit_log.go
  go/go.mod
  go/go.sum
  go/plugin/caddy2/api/dal_radius_audit_log.go
  go/plugin/caddy2/pfpki/sql/search_ops.go
  go/plugin/caddy2/pfpki/sql/search_ops_test.go
  go/plugin/caddy2/pfpki/sql/var2.go
Labels: Priority: Medium

#8637 Feature/cisco easy psk
  docs/images/wlc-9800-wlan-pf-easy-psk-security.jpg
  docs/images/wlc-9800-wlan-pf-easy-psk.jpg
  docs/network/networkdevice/cisco_ap.asciidoc
  lib/pf/Switch.pm
  lib/pf/Switch/Cisco/Cisco_WLC_IOS_XE.pm
Labels: Type: Feature / Enhancement, Status: For review, Status: Not ready, Priority: Medium, Status: Tested and works

#8519 Simplified Unbound DPSK code
  lib/pf/Switch.pm
  lib/pf/Switch/Juniper/MistAP.pm
  lib/pf/Switch/OpenWiFi.pm
  lib/pf/Switch/Ruckus/SmartZone.pm
  lib/pf/Switch/Ruckus/Unleashed.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium

#8711 Default kafka configuration
  addons/perl-client/conf/fingerbank.conf.defaults
  addons/upgrade/to-15.0-replace-kafka-values.sh
  conf/kafka.conf.example
  conf/pfcron.conf.defaults
  debian/packetfence.postinst
  lib/pf/services/manager/kafka.pm
  rpm/packetfence.spec
Labels: Type: Feature / Enhancement, Status: For review, Priority: High, Status: Tested and works
