Repository inverse-inc/packetfence, pull requests merged in 2025-01, with the labels that each got.

#8468 Only update things with value
  lib/pf/fingerbank.pm
Labels: Priority: High

#8470 Improved regex for fortinanalyser
  go/detectparser/fortianalyser.go
Labels: Type: Feature / Enhancement, Status: For review, Priority: Low

#8460 fix/8451
  lib/pf/UnifiedApi/Controller/Crud.pm
  lib/pf/UnifiedApi/Controller/Users.pm
  lib/pf/lookup/person.pm
Labels: Type: Bug, Status: For review, Priority: High

#8500 Support for Ruckus unleashed AP
  docs/images/ruckus_unleashed_hotspot-1.png
  docs/images/ruckus_unleashed_hotspot-2.png
  docs/images/ruckus_unleashed_hotspot-3.png
  docs/images/ruckus_unleashed_hotspot-4.png
  docs/images/ruckus_unleashed_hotspot-5.png
  docs/images/ruckus_unleashed_mac_auth.png
  docs/images/ruckus_unleashed_secure-1.png
  docs/network/networkdevice/ruckus_unleashed.asciidoc
  docs/network/wireless_controllers_and_access_point_configuration.asciidoc
  lib/pf/Switch/Ruckus/Unleashed.pm
  lib/pf/web/constants.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium

#8495 Added support for Webauth, dpsk and unbound dpsk for Juniper Mist
  lib/pf/Switch/Juniper/MistAP.pm
  lib/pf/web/constants.pm
Labels: Type: Feature / Enhancement, Status: For review, Priority: Medium

#8496 Fix unbound dpsk in Ruckus and OpenWifi switch module
  lib/pf/Switch/OpenWiFi.pm
  lib/pf/Switch/Ruckus/SmartZone.pm
Labels: Type: Bug, Status: For review, Priority: High

#8521 Update the ip4log on radius authentication request (if Framed-Ip-Address exists)
  conf/documentation.conf
  conf/pf.conf.defaults
  go/pfconfigdriver/structs.go
  html/pfappserver/root/src/views/Configuration/advanced/_components/TheForm.vue
  html/pfappserver/root/src/views/Configuration/advanced/_components/index.js
  lib/pf/radius.pm
Labels: Priority: High, Customer
